package system

// cicdDictSeeds CI/CD 域内置字典种子：平台配置（字典优先，config.yaml 兜底）与流水线枚举。
func cicdDictSeeds() []DictEntryCreateRequest {
	return []DictEntryCreateRequest{
		// CI/CD 平台配置（字典优先，config.yaml 兜底）
		{DictType: "cicd_enabled", Label: "启用 CI/CD", Value: "true", Sort: intRef(1), Status: 1, Remark: "CI/CD 插件总开关"},
		{DictType: "cicd_jenkins_base_url", Label: "Jenkins 地址", Value: "http://127.0.0.1:8080", Sort: intRef(1), Status: 0, Remark: "Jenkins 根 URL"},
		{DictType: "cicd_jenkins_username", Label: "Jenkins 用户", Value: "admin", Sort: intRef(1), Status: 0, Remark: "Basic Auth 用户名"},
		{DictType: "cicd_jenkins_api_token", Label: "Jenkins API Token", Value: "", Sort: intRef(1), Status: 0, Remark: "敏感：Jenkins API Token"},
		{DictType: "cicd_jenkinsfile_repo", Label: "Jenkinsfile 仓库", Value: "git@gitee.com:wxd_ops/jenkinsfile-new.git", Sort: intRef(1), Status: 1, Remark: "Pipeline SCM 仓库"},
		{DictType: "cicd_jenkinsfile_branch", Label: "Jenkinsfile 分支", Value: "main", Sort: intRef(1), Status: 1, Remark: "Pipeline SCM 分支"},
		{DictType: "cicd_jenkinsfile_front", Label: "前端 Jenkinsfile", Value: "front.jenkinsfile", Sort: intRef(1), Status: 1, Remark: "前端流水线 Script Path"},
		{DictType: "cicd_jenkinsfile_backend", Label: "后端 Jenkinsfile", Value: "backend.jenkinsfile", Sort: intRef(1), Status: 1, Remark: "后端流水线 Script Path"},
		{DictType: "cicd_git_credential_id", Label: "Git 凭据 ID", Value: "gitee_registry_ssh", Sort: intRef(1), Status: 1, Remark: "Jenkins 拉代码 SSH 凭据"},
		{DictType: "cicd_ssh_deploy_credential_id", Label: "SSH 部署凭据 ID", Value: "target-server-credential", Sort: intRef(1), Status: 1, Remark: "SSH_KEY_CREDENTIAL_ID"},
		{DictType: "cicd_minio_credential_id", Label: "MinIO 凭据 ID", Value: "minio-credentials", Sort: intRef(1), Status: 1, Remark: "Jenkins 流水线 withCredentials 使用；Yunshu 无法读取 Jenkins 凭据库"},
		{DictType: "cicd_minio_access_key", Label: "MinIO AccessKey（Yunshu）", Value: "", Sort: intRef(1), Status: 0, Remark: "与 Jenkins minio-credentials Username 一致；空则回退 minio_access_key"},
		{DictType: "cicd_minio_secret_key", Label: "MinIO SecretKey（Yunshu）", Value: "", Sort: intRef(1), Status: 0, Remark: "与 Jenkins minio-credentials Password 一致；空则回退 minio_secret_key"},
		{DictType: "cicd_minio_endpoint", Label: "MinIO S3 地址", Value: "", Sort: intRef(1), Status: 0, Remark: "Jenkins MINIO_ENDPOINT；空则回退 minio_endpoint 字典"},
		{DictType: "cicd_minio_bucket_frontend", Label: "前端制品桶", Value: "frontend-artifacts", Sort: intRef(1), Status: 1, Remark: "MINIO_BUCKET 前端"},
		{DictType: "cicd_minio_bucket_backend", Label: "后端制品桶", Value: "backend-artifacts", Sort: intRef(1), Status: 1, Remark: "MINIO_BUCKET 后端"},
		{DictType: "cicd_jenkinsfile_k8s", Label: "容器化 Jenkinsfile", Value: "cigroovy.jenkinsfile", Sort: intRef(1), Status: 1, Remark: "K8s/Harbor 流水线 Script Path"},
		{DictType: "cicd_harbor_url", Label: "Harbor 地址", Value: "harbor.deploy.local", Sort: intRef(1), Status: 1, Remark: "Jenkins HARBOR_URL（不含协议）"},
		{DictType: "cicd_harbor_host_ip", Label: "Harbor 解析 IP", Value: "10.10.10.103", Sort: intRef(1), Status: 1, Remark: "Jenkins HARBOR_HOST_IP；K8s Agent Pod hostAliases 将 cicd_harbor_url 解析到此 IP"},
		{DictType: "cicd_harbor_credential_id", Label: "Harbor 凭据 ID", Value: "HARBOR_ID", Sort: intRef(1), Status: 1, Remark: "Jenkins Username/Password 凭据 ID，用于 docker login"},
		{DictType: "cicd_harbor_project_group", Label: "Harbor 项目", Value: "registry", Sort: intRef(1), Status: 1, Remark: "Jenkins PROJECT_GROUP（镜像仓库项目名）"},
		{DictType: "cicd_harbor_username", Label: "Harbor 用户名", Value: "admin", Sort: intRef(1), Status: 1, Remark: "Helm 拉取 Harbor OCI Chart 与 Chart API 鉴权"},
		{DictType: "cicd_harbor_password", Label: "Harbor 密码", Value: "", Sort: intRef(1), Status: 0, Remark: "Helm/Harbor API 密码（敏感，启用后填写）"},
		{DictType: "cicd_default_wait_mins", Label: "手动发布超时(分钟)", Value: "60", Sort: intRef(1), Status: 1, Remark: "waitMins 默认值"},
		{DictType: "cicd_default_artifact_retain_count", Label: "制品保留数", Value: "10", Sort: intRef(1), Status: 1, Remark: "artifactRetainCount 默认"},
		{DictType: "cicd_run_sync_interval_seconds", Label: "Run 同步间隔(秒)", Value: "15", Sort: intRef(1), Status: 1, Remark: "后台轮询 Jenkins 状态"},
		{DictType: "cicd_approval_sla_hours", Label: "审批超时阈值(小时)", Value: "24", Sort: intRef(1), Status: 1, Remark: "待审批超过该时长后向审批人发邮件提醒"},
		{DictType: "cicd_approval_reminder_interval_hours", Label: "审批提醒间隔(小时)", Value: "4", Sort: intRef(1), Status: 1, Remark: "同一审批节点重复提醒的最小间隔"},
		{DictType: "cicd_forbid_self_approve", Label: "禁止自审自批", Value: "true", Sort: intRef(1), Status: 1, Remark: "cicd.forbid_self_approve：提交人不可审批自己的发布"},
		{DictType: "cicd_prod_force_audit", Label: "生产环境强制审批", Value: "true", Sort: intRef(1), Status: 1, Remark: "cicd.prod_force_audit：生产 Tenv 忽略 deploy_config.audit_enabled=false"},
		{DictType: "cicd_sonar_enabled", Label: "启用 SonarQube 门禁", Value: "false", Sort: intRef(1), Status: 1, Remark: "true/false：CI 构建是否跑 Sonar 并上报质量门禁；关闭时不注入 enableSonar"},
		{DictType: "cicd_sonar_url", Label: "SonarQube 地址", Value: "", Sort: intRef(1), Status: 0, Remark: "如 https://sonar.example.com；启用门禁后填写"},
		{DictType: "cicd_sonar_token", Label: "SonarQube Token", Value: "", Sort: intRef(1), Status: 0, Remark: "敏感：注入 Jenkins SONAR_TOKEN（或流水线凭据）"},
		{DictType: "cicd_sonar_gate_block", Label: "门禁失败拦截发布", Value: "true", Sort: intRef(1), Status: 1, Remark: "true/false：质量门禁 ERROR/未通过时禁止进入审批与执行发布"},
		{DictType: "cicd_jenkins_callback_hmac_secret", Label: "Jenkins 回调 HMAC Secret", Value: "", Sort: intRef(1), Status: 0, Remark: "敏感：校验 X-Yunshu-Signature；与流水线共享密钥"},
		{DictType: "cicd_jenkins_callback_url", Label: "Jenkins 回调 URL", Value: "", Sort: intRef(1), Status: 0, Remark: "完整地址，如 https://yunshu.example.com/api/v1/cicd/jenkins/callback"},
		// CI/CD 枚举
		{DictType: "cicd_pipeline_type", Label: "前端服务", Value: "frontend", Sort: intRef(1), Status: 1, Remark: "应用类型"},
		{DictType: "cicd_pipeline_type", Label: "后端服务", Value: "backend", Sort: intRef(2), Status: 1, Remark: "应用类型"},
		{DictType: "cicd_pipeline_type", Label: "容器化服务", Value: "microservice", Sort: intRef(3), Status: 1, Remark: "应用类型（Harbor+K8s 流水线）"},
		{DictType: "cicd_publish_mode", Label: "自动发布", Value: "自动发布", Sort: intRef(1), Status: 1, Remark: "publishMode"},
		{DictType: "cicd_publish_mode", Label: "手动发布", Value: "手动发布", Sort: intRef(2), Status: 1, Remark: "publishMode"},
		{DictType: "cicd_publish_mode", Label: "仅构建", Value: "仅构建", Sort: intRef(3), Status: 1, Remark: "publishMode"},
		{DictType: "cicd_publish_mode", Label: "制品发布", Value: "制品发布", Sort: intRef(4), Status: 1, Remark: "Yunshu CD 发布已选 MinIO 制品，跳过编译与 Jenkins input"},
		{DictType: "cicd_publish_mode", Label: "回滚", Value: "回滚", Sort: intRef(5), Status: 1, Remark: "publishMode：Jenkins UI 选手动回滚历史版本"},
		{DictType: "cicd_release_op_frontend", Label: "服务上线", Value: "frontend_online", Sort: intRef(1), Status: 1, Remark: "前端 CD 操作类型"},
		{DictType: "cicd_release_op_frontend", Label: "服务回滚", Value: "frontend_rollback", Sort: intRef(2), Status: 1, Remark: "前端 CD 操作类型"},
		{DictType: "cicd_release_op_backend", Label: "服务初次部署", Value: "backend_initial", Sort: intRef(1), Status: 1, Remark: "后端 CD 操作类型"},
		{DictType: "cicd_release_op_backend", Label: "服务更新", Value: "backend_update", Sort: intRef(2), Status: 1, Remark: "后端 CD 操作类型（含选历史包回滚）"},
		{DictType: "cicd_tenv", Label: "开发环境", Value: "dev", Sort: intRef(1), Status: 1, Remark: "Tenv"},
		{DictType: "cicd_tenv", Label: "测试环境", Value: "test", Sort: intRef(2), Status: 1, Remark: "Tenv"},
		{DictType: "cicd_tenv", Label: "生产环境", Value: "prod", Sort: intRef(3), Status: 1, Remark: "Tenv"},
		{DictType: "cicd_build_type_frontend", Label: "npm", Value: "npm", Sort: intRef(1), Status: 1, Remark: "前端 buildType"},
		{DictType: "cicd_build_type_frontend", Label: "yarn", Value: "yarn", Sort: intRef(2), Status: 1, Remark: "前端 buildType"},
		{DictType: "cicd_build_type_backend", Label: "Maven", Value: "mvn", Sort: intRef(1), Status: 1, Remark: "后端 buildType"},
		{DictType: "cicd_build_type_backend", Label: "Gradle", Value: "gradle", Sort: intRef(2), Status: 1, Remark: "后端 buildType"},
		{DictType: "cicd_build_type_backend", Label: "Python", Value: "python", Sort: intRef(3), Status: 1, Remark: "后端 buildType"},
		{DictType: "cicd_build_type_backend", Label: "Golang", Value: "golang", Sort: intRef(4), Status: 1, Remark: "后端 buildType"},
		{DictType: "cicd_npm_install_mode", Label: "install", Value: "install", Sort: intRef(1), Status: 1, Remark: "npmInstallMode"},
		{DictType: "cicd_npm_install_mode", Label: "ci", Value: "ci", Sort: intRef(2), Status: 1, Remark: "npmInstallMode"},
		{DictType: "cicd_npm_install_mode", Label: "skip", Value: "skip", Sort: intRef(3), Status: 1, Remark: "npmInstallMode"},
		{DictType: "cicd_deploy_kind", Label: "常规发布", Value: "regular", Sort: intRef(1), Status: 1, Remark: "SSH+MinIO"},
		{DictType: "cicd_deploy_kind", Label: "容器化发布", Value: "container", Sort: intRef(2), Status: 1, Remark: "Harbor+K8s"},
		{DictType: "cicd_deploy_strategy", Label: "滚动发布", Value: "rolling", Sort: intRef(1), Status: 1, Remark: "默认滚动更新"},
		{DictType: "cicd_deploy_strategy", Label: "金丝雀发布", Value: "canary", Sort: intRef(2), Status: 1, Remark: "deploy_strategy=canary；平台晋级 + Jenkins 参数"},
		{DictType: "cicd_deploy_strategy", Label: "蓝绿发布", Value: "blue_green", Sort: intRef(3), Status: 1, Remark: "deploy_strategy=blue_green；切换 Service selector"},
		{DictType: "cicd_deploy_action", Label: "初始化部署", Value: "初始化部署", Sort: intRef(1), Status: 1, Remark: "deployAction"},
		{DictType: "cicd_deploy_action", Label: "服务更新", Value: "服务更新", Sort: intRef(2), Status: 1, Remark: "deployAction"},
		{DictType: "cicd_start_script_type", Label: "脚本模板", Value: "脚本模板", Sort: intRef(1), Status: 1, Remark: "startScriptType"},
		{DictType: "cicd_start_script_type", Label: "自定义脚本", Value: "自定义脚本", Sort: intRef(2), Status: 1, Remark: "startScriptType"},
		{DictType: "cicd_k8s_credential", Label: "dev", Value: "k8s-dev-config", Sort: intRef(1), Status: 1, Remark: "K8S_CREDENTIAL_ID"},
		{DictType: "cicd_k8s_credential", Label: "test", Value: "k8s-test-config", Sort: intRef(2), Status: 1, Remark: "K8S_CREDENTIAL_ID"},
		{DictType: "cicd_k8s_credential", Label: "prod", Value: "k8s-prod-config", Sort: intRef(3), Status: 1, Remark: "K8S_CREDENTIAL_ID"},
		{DictType: "cicd_importance_level", Label: "一般", Value: "normal", Sort: intRef(1), Status: 1, Remark: "重要级别"},
		{DictType: "cicd_importance_level", Label: "重要", Value: "important", Sort: intRef(2), Status: 1, Remark: "重要级别"},
		{DictType: "cicd_importance_level", Label: "核心", Value: "critical", Sort: intRef(3), Status: 1, Remark: "重要级别"},
	}
}
