/**
 * 与后端 `internal/router/register_*_routes.go` 中 `/api/v1` 路由对齐，便于在控制台核对「接口 ↔ 页面」映射。
 * 若后端增删路由，请同步更新本文件与 `cmd/seed.go` 中 Casbin 能力项（`Name` 与本文件 `summary` 保持一致，便于 API 管理页「一键补全接口」与权限名对齐）。
 */
export type ApiCatalogRow = {
  method: string;
  path: string;
  summary: string;
  /** 对应前端入口；无独立页面时说明调用场景 */
  ui: string;
  /** 是否需要 Bearer Token（健康检查等除外） */
  auth: boolean;
};

export const API_CATALOG_GROUPS: { title: string; routes: ApiCatalogRow[] }[] = [
  {
    title: "系统",
    routes: [
      {
        method: "GET",
        path: "/api/v1/health",
        summary: "健康检查与进程运行信息",
        ui: "总览页面 · 系统状态",
        auth: false,
      },
    ],
  },
  {
    title: "认证（多数无需登录）",
    routes: [
      { method: "POST", path: "/api/v1/auth/verification-code", summary: "发送邮箱验证码", ui: "登录页 / 注册页", auth: false },
      {
        method: "POST",
        path: "/api/v1/auth/login-code",
        summary: "按用户名向绑定邮箱发登录验证码",
        ui: "可与邮箱登录配合（前端当前走邮箱直发）",
        auth: false,
      },
      { method: "POST", path: "/api/v1/auth/password-login-code", summary: "获取图形验证码", ui: "登录页 · 用户名密码", auth: false },
      { method: "POST", path: "/api/v1/auth/login", summary: "用户名密码登录", ui: "登录页 · 用户名密码", auth: false },
      { method: "POST", path: "/api/v1/auth/email-login", summary: "邮箱验证码登录", ui: "登录页 · 邮箱验证码", auth: false },
      { method: "POST", path: "/api/v1/auth/register", summary: "提交注册申请", ui: "登录页 · 注册账号", auth: false },
      { method: "POST", path: "/api/v1/auth/logout", summary: "注销当前 Token", ui: "顶栏用户菜单 · 退出登录", auth: true },
      { method: "POST", path: "/api/v1/auth/ws-ticket", summary: "申请 WebSocket 一次性握手 ticket", ui: "Pod Exec / 服务器终端", auth: true },
      { method: "GET", path: "/api/v1/auth/me", summary: "当前用户与角色", ui: "全局（进入控制台时拉取）", auth: true },
      { method: "PUT", path: "/api/v1/auth/me", summary: "更新个人资料", ui: "个人设置", auth: true },
      { method: "PUT", path: "/api/v1/auth/password", summary: "修改个人密码", ui: "个人设置", auth: true },
    ],
  },
  {
    title: "账号",
    routes: [
      { method: "GET", path: "/api/v1/users", summary: "分页列表", ui: "账号管理", auth: true },
      { method: "POST", path: "/api/v1/users", summary: "创建用户", ui: "账号管理", auth: true },
      { method: "GET", path: "/api/v1/users/:id", summary: "用户详情", ui: "账号管理", auth: true },
      { method: "PUT", path: "/api/v1/users/:id", summary: "更新用户", ui: "账号管理", auth: true },
      { method: "DELETE", path: "/api/v1/users/:id", summary: "删除用户", ui: "账号管理", auth: true },
      { method: "PUT", path: "/api/v1/users/:id/roles", summary: "分配角色", ui: "账号管理", auth: true },
      { method: "GET", path: "/api/v1/users/import-template", summary: "下载用户导入模板", ui: "账号管理", auth: true },
    ],
  },
  {
    title: "组织架构",
    routes: [
      { method: "GET", path: "/api/v1/departments/tree", summary: "部门树", ui: "组织架构", auth: true },
      { method: "GET", path: "/api/v1/departments/:id", summary: "部门详情", ui: "组织架构", auth: true },
      { method: "POST", path: "/api/v1/departments", summary: "创建部门", ui: "组织架构", auth: true },
      { method: "PUT", path: "/api/v1/departments/:id", summary: "更新部门（支持迁移子树）", ui: "组织架构", auth: true },
      { method: "DELETE", path: "/api/v1/departments/:id", summary: "删除部门", ui: "组织架构", auth: true },
    ],
  },
  {
    title: "角色",
    routes: [
      { method: "GET", path: "/api/v1/roles", summary: "分页列表", ui: "角色管理", auth: true },
      { method: "POST", path: "/api/v1/roles", summary: "创建角色", ui: "角色管理", auth: true },
      { method: "GET", path: "/api/v1/roles/:id", summary: "角色详情", ui: "角色管理", auth: true },
      { method: "PUT", path: "/api/v1/roles/:id", summary: "更新角色", ui: "角色管理", auth: true },
      { method: "DELETE", path: "/api/v1/roles/:id", summary: "删除角色", ui: "角色管理", auth: true },
    ],
  },
  {
    title: "接口能力（权限元数据）",
    routes: [
      { method: "GET", path: "/api/v1/permissions", summary: "分页列表", ui: "API 管理", auth: true },
      { method: "POST", path: "/api/v1/permissions", summary: "新建能力项", ui: "API 管理", auth: true },
      { method: "GET", path: "/api/v1/permissions/:id", summary: "详情", ui: "API 管理", auth: true },
      { method: "PUT", path: "/api/v1/permissions/:id", summary: "更新", ui: "API 管理", auth: true },
      { method: "DELETE", path: "/api/v1/permissions/:id", summary: "删除", ui: "API 管理", auth: true },
    ],
  },
  {
    title: "授权策略（Casbin）",
    routes: [
      { method: "GET", path: "/api/v1/policies", summary: "策略列表", ui: "授权管理", auth: true },
      { method: "POST", path: "/api/v1/policies", summary: "授予：角色绑定能力项", ui: "授权管理", auth: true },
      {
        method: "DELETE",
        path: "/api/v1/policies",
        summary: "撤销：请求体携带 role_id + permission_id",
        ui: "授权管理",
        auth: true,
      },
    ],
  },
  {
    title: "注册审核",
    routes: [
      { method: "GET", path: "/api/v1/registrations", summary: "申请列表", ui: "注册审核", auth: true },
      { method: "POST", path: "/api/v1/registrations/:id/review", summary: "审核", ui: "注册审核", auth: true },
    ],
  },
  {
    title: "菜单",
    routes: [
      { method: "GET", path: "/api/v1/menus/tree", summary: "侧栏菜单树（登录即可，不走 Casbin）", ui: "侧栏", auth: true },
      { method: "GET", path: "/api/v1/menus", summary: "菜单管理列表", ui: "菜单管理", auth: true },
      { method: "POST", path: "/api/v1/menus", summary: "创建菜单", ui: "菜单管理", auth: true },
      { method: "PUT", path: "/api/v1/menus/:id", summary: "更新菜单", ui: "菜单管理", auth: true },
      { method: "DELETE", path: "/api/v1/menus/:id", summary: "删除菜单", ui: "菜单管理", auth: true },
    ],
  },
  {
    title: "审计",
    routes: [
      { method: "GET", path: "/api/v1/login-logs", summary: "登录日志", ui: "登录日志", auth: true },
      { method: "DELETE", path: "/api/v1/login-logs/:id", summary: "删除单条", ui: "登录日志", auth: true },
      { method: "POST", path: "/api/v1/login-logs/delete", summary: "批量删除", ui: "登录日志", auth: true },
      { method: "GET", path: "/api/v1/operation-logs", summary: "操作历史", ui: "操作历史", auth: true },
      { method: "DELETE", path: "/api/v1/operation-logs/:id", summary: "删除单条", ui: "操作历史", auth: true },
      { method: "POST", path: "/api/v1/operation-logs/delete", summary: "批量删除", ui: "操作历史", auth: true },
    ],
  },
  {
    title: "告警中心",
    routes: [
      {
        method: "POST",
        path: "/api/v1/alerts/ingress/k8s-events",
        summary: "接收 K8s Event 内部入站（非 Alertmanager）",
        ui: "K8s Event 转发",
        auth: false,
      },
      { method: "GET", path: "/api/v1/alerts/channels", summary: "告警通道列表", ui: "告警通道", auth: true },
      { method: "POST", path: "/api/v1/alerts/channels", summary: "创建告警通道", ui: "告警通道", auth: true },
      { method: "PUT", path: "/api/v1/alerts/channels/:id", summary: "更新告警通道", ui: "告警通道", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/channels/:id", summary: "删除告警通道", ui: "告警通道", auth: true },
      { method: "POST", path: "/api/v1/alerts/channels/:id/test", summary: "测试告警通道", ui: "告警通道", auth: true },
      {
        method: "POST",
        path: "/api/v1/alerts/channels/preview-template",
        summary: "预览通道消息模板",
        ui: "告警通道 · 模板预览",
        auth: true,
      },
      { method: "GET", path: "/api/v1/alerts/events", summary: "告警事件列表（支持 category 筛选）", ui: "历史告警记录", auth: true },
      { method: "GET", path: "/api/v1/alerts/history/stats", summary: "告警历史统计", ui: "告警配置中心", auth: true },
      { method: "POST", path: "/api/v1/alerts/acks", summary: "认领告警", ui: "告警监控平台 · 事件台", auth: true },
      { method: "GET", path: "/api/v1/alerts/notes", summary: "告警进展列表", ui: "告警监控平台 · 事件台", auth: true },
      { method: "POST", path: "/api/v1/alerts/notes", summary: "添加告警进展", ui: "告警监控平台 · 事件台", auth: true },
      { method: "GET", path: "/api/v1/alerts/datasources", summary: "告警数据源列表", ui: "告警监控平台 · 数据源", auth: true },
      { method: "POST", path: "/api/v1/alerts/datasources", summary: "创建告警数据源", ui: "告警监控平台 · 数据源", auth: true },
      { method: "PUT", path: "/api/v1/alerts/datasources/:id", summary: "更新告警数据源", ui: "告警监控平台 · 数据源", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/datasources/:id", summary: "删除告警数据源", ui: "告警监控平台 · 数据源", auth: true },
      { method: "GET", path: "/api/v1/alerts/datasources/:id/prometheus-alerts", summary: "Prometheus 活跃告警快照", ui: "告警监控平台 · 静默", auth: true },
      { method: "POST", path: "/api/v1/alerts/datasources/:id/query", summary: "PromQL 即时查询", ui: "告警监控平台 · PromQL 控制台", auth: true },
      { method: "POST", path: "/api/v1/alerts/datasources/:id/query_range", summary: "PromQL 范围查询", ui: "告警监控平台 · PromQL 控制台", auth: true },
      { method: "GET", path: "/api/v1/alerts/silences", summary: "告警静默列表", ui: "告警监控平台 · 静默", auth: true },
      { method: "POST", path: "/api/v1/alerts/silences", summary: "创建告警静默", ui: "告警监控平台 · 静默", auth: true },
      { method: "POST", path: "/api/v1/alerts/silences/batch", summary: "批量创建告警静默", ui: "告警监控平台 · 静默", auth: true },
      { method: "PUT", path: "/api/v1/alerts/silences/:id", summary: "更新告警静默", ui: "告警监控平台 · 静默", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/silences/:id", summary: "删除告警静默", ui: "告警监控平台 · 静默", auth: true },
      { method: "GET", path: "/api/v1/alerts/inhibition-rules", summary: "告警抑制规则列表", ui: "告警监控平台 · 告警抑制", auth: true },
      { method: "POST", path: "/api/v1/alerts/inhibition-rules", summary: "创建告警抑制规则", ui: "告警监控平台 · 告警抑制", auth: true },
      { method: "PUT", path: "/api/v1/alerts/inhibition-rules/:id", summary: "更新告警抑制规则", ui: "告警监控平台 · 告警抑制", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/inhibition-rules/:id", summary: "删除告警抑制规则", ui: "告警监控平台 · 告警抑制", auth: true },
      { method: "POST", path: "/api/v1/alerts/inhibition-rules/refresh-cache", summary: "刷新抑制规则缓存", ui: "告警监控平台 · 告警抑制", auth: true },
      { method: "GET", path: "/api/v1/alerts/rule-templates", summary: "内置告警规则模板列表（按 cpu/disk/memory/availability 分组）", ui: "告警监控平台 · 从模板创建", auth: true },
      { method: "GET", path: "/api/v1/alerts/monitor-rules", summary: "监控告警规则列表", ui: "告警监控平台 · 监控规则", auth: true },
      { method: "POST", path: "/api/v1/alerts/monitor-rules", summary: "创建监控告警规则", ui: "告警监控平台 · 监控规则", auth: true },
      { method: "POST", path: "/api/v1/alerts/monitor-rules/from-template", summary: "从模板创建监控规则（写入 category label）", ui: "告警监控平台 · 从模板创建", auth: true },
      { method: "PUT", path: "/api/v1/alerts/monitor-rules/:id", summary: "更新监控告警规则", ui: "告警监控平台 · 监控规则", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/monitor-rules/:id", summary: "删除监控告警规则", ui: "告警监控平台 · 监控规则", auth: true },
      { method: "GET", path: "/api/v1/alerts/monitor-rules/:id/assignees", summary: "监控规则处理人", ui: "告警监控平台 · 处理人", auth: true },
      { method: "PUT", path: "/api/v1/alerts/monitor-rules/:id/assignees", summary: "配置监控规则处理人", ui: "告警监控平台 · 处理人", auth: true },
      { method: "GET", path: "/api/v1/alerts/duty-blocks", summary: "规则值班班次列表（按 monitor_rule_id）", ui: "告警监控平台 · 规则与值班绑定", auth: true },
      { method: "POST", path: "/api/v1/alerts/duty-blocks", summary: "创建规则值班班次", ui: "告警监控平台 · 规则与值班绑定", auth: true },
      { method: "PUT", path: "/api/v1/alerts/duty-blocks/:id", summary: "更新规则值班班次", ui: "告警监控平台 · 规则与值班绑定", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/duty-blocks/:id", summary: "删除规则值班班次", ui: "告警监控平台 · 规则与值班绑定", auth: true },
      { method: "GET", path: "/api/v1/alerts/subscriptions/tree", summary: "订阅路由树", ui: "告警配置中心 · 订阅路由", auth: true },
      { method: "POST", path: "/api/v1/alerts/subscriptions", summary: "创建订阅节点", ui: "告警配置中心 · 订阅路由", auth: true },
      { method: "POST", path: "/api/v1/alerts/subscriptions/wizard", summary: "路由向导创建节点", ui: "告警配置中心 · 订阅路由", auth: true },
      { method: "PUT", path: "/api/v1/alerts/subscriptions/:id", summary: "更新订阅节点", ui: "告警配置中心 · 订阅路由", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/subscriptions/:id", summary: "删除订阅节点", ui: "告警配置中心 · 订阅路由", auth: true },
      { method: "GET", path: "/api/v1/alerts/receiver-groups", summary: "接收组列表", ui: "告警配置中心 · 接收组", auth: true },
      { method: "POST", path: "/api/v1/alerts/receiver-groups", summary: "创建接收组", ui: "告警配置中心 · 接收组", auth: true },
      { method: "PUT", path: "/api/v1/alerts/receiver-groups/:id", summary: "更新接收组", ui: "告警配置中心 · 接收组", auth: true },
      { method: "DELETE", path: "/api/v1/alerts/receiver-groups/:id", summary: "删除接收组", ui: "告警配置中心 · 接收组", auth: true },
      { method: "GET", path: "/api/v1/alerts/cloud-expiry-rules", summary: "云到期规则列表", ui: "告警监控平台 · 云到期", auth: true },
      { method: "POST", path: "/api/v1/alerts/cloud-expiry-rules/evaluate-now", summary: "立即评估云到期规则", ui: "告警监控平台 · 云到期", auth: true },
    ],
  },
  {
    title: "K8s 集群与 Event 转发",
    routes: [
      { method: "GET", path: "/api/v1/clusters", summary: "集群列表", ui: "集群管理", auth: true },
      { method: "POST", path: "/api/v1/clusters", summary: "创建集群", ui: "集群管理", auth: true },
      { method: "PUT", path: "/api/v1/clusters/:id", summary: "更新集群", ui: "集群管理", auth: true },
      { method: "DELETE", path: "/api/v1/clusters/:id", summary: "删除集群", ui: "集群管理", auth: true },
      { method: "PUT", path: "/api/v1/clusters/:id/status", summary: "启停集群", ui: "集群管理", auth: true },
      { method: "GET", path: "/api/v1/clusters/:id/status", summary: "集群连接状态", ui: "集群管理", auth: true },
      { method: "GET", path: "/api/v1/clusters/:id/namespaces", summary: "集群命名空间", ui: "集群管理", auth: true },
      { method: "GET", path: "/api/v1/clusters/:id/component-statuses", summary: "组件状态列表", ui: "集群管理", auth: true },
      { method: "GET", path: "/api/v1/clusters/:id/api-resources", summary: "集群 API 资源发现", ui: "集群管理", auth: true },
      { method: "GET", path: "/api/v1/k8s/event-forward/rules", summary: "K8s Event 转发规则列表", ui: "K8s Event 转发", auth: true },
      { method: "GET", path: "/api/v1/k8s/event-forward/rules/:id", summary: "K8s Event 转发规则详情", ui: "K8s Event 转发", auth: true },
      { method: "POST", path: "/api/v1/k8s/event-forward/rules", summary: "K8s Event 转发规则创建", ui: "K8s Event 转发", auth: true },
      { method: "PUT", path: "/api/v1/k8s/event-forward/rules/:id", summary: "K8s Event 转发规则更新", ui: "K8s Event 转发", auth: true },
      { method: "DELETE", path: "/api/v1/k8s/event-forward/rules/:id", summary: "K8s Event 转发规则删除", ui: "K8s Event 转发", auth: true },
      { method: "GET", path: "/api/v1/k8s/event-forward/settings", summary: "K8s Event 转发 Worker 参数", ui: "K8s Event 转发", auth: true },
      { method: "PUT", path: "/api/v1/k8s/event-forward/settings", summary: "K8s Event 转发 Worker 更新", ui: "K8s Event 转发", auth: true },
    ],
  },
  {
    title: "K8s 工作负载",
    routes: [
      { method: "GET", path: "/api/v1/deployments", summary: "Deployment 列表", ui: "工作负载 · Deployment", auth: true },
      { method: "GET", path: "/api/v1/deployments/detail", summary: "Deployment 详情", ui: "工作负载 · Deployment", auth: true },
      { method: "GET", path: "/api/v1/deployments/rollout-status", summary: "Deployment 发布状态", ui: "工作负载 · Deployment", auth: true },
      { method: "GET", path: "/api/v1/deployments/pods", summary: "Deployment 关联 Pod", ui: "工作负载 · 关联 Pod", auth: true },
      { method: "POST", path: "/api/v1/deployments/scale", summary: "Deployment 水平扩缩", ui: "工作负载 · Deployment", auth: true },
      { method: "POST", path: "/api/v1/deployments/container-resources", summary: "Deployment 垂直扩缩", ui: "工作负载 · Deployment", auth: true },
      { method: "POST", path: "/api/v1/deployments/restart", summary: "Deployment 滚动重启", ui: "工作负载 · Deployment", auth: true },
      { method: "GET", path: "/api/v1/statefulsets", summary: "StatefulSet 列表", ui: "工作负载 · StatefulSet", auth: true },
      { method: "POST", path: "/api/v1/statefulsets/scale", summary: "StatefulSet 水平扩缩", ui: "工作负载 · StatefulSet", auth: true },
      { method: "POST", path: "/api/v1/statefulsets/container-resources", summary: "StatefulSet 垂直扩缩", ui: "工作负载 · StatefulSet", auth: true },
      { method: "GET", path: "/api/v1/daemonsets", summary: "DaemonSet 列表", ui: "工作负载 · DaemonSet", auth: true },
      { method: "POST", path: "/api/v1/daemonsets/container-resources", summary: "DaemonSet 垂直扩缩", ui: "工作负载 · DaemonSet", auth: true },
      { method: "GET", path: "/api/v1/jobs", summary: "Job 列表", ui: "工作负载 · Job", auth: true },
      { method: "GET", path: "/api/v1/jobs/pods", summary: "Job 关联 Pod", ui: "工作负载 · Job", auth: true },
      { method: "POST", path: "/api/v1/jobs/rerun", summary: "Job 重新执行", ui: "工作负载 · Job", auth: true },
      { method: "POST", path: "/api/v1/jobs/container-resources", summary: "Job 垂直扩缩", ui: "工作负载 · Job", auth: true },
      { method: "GET", path: "/api/v1/cronjobs", summary: "CronJob 列表", ui: "工作负载 · CronJob", auth: true },
      { method: "GET", path: "/api/v1/cronjobs/v2", summary: "CronJob 列表（增强字段）", ui: "工作负载 · CronJob", auth: true },
      { method: "GET", path: "/api/v1/cronjobs/pods", summary: "CronJob 关联 Pod", ui: "工作负载 · CronJob", auth: true },
      { method: "POST", path: "/api/v1/cronjobs/suspend", summary: "CronJob 挂起/恢复", ui: "工作负载 · CronJob", auth: true },
      { method: "POST", path: "/api/v1/cronjobs/trigger", summary: "CronJob 手动触发", ui: "工作负载 · CronJob", auth: true },
      { method: "POST", path: "/api/v1/cronjobs/container-resources", summary: "CronJob 垂直扩缩", ui: "工作负载 · CronJob", auth: true },
    ],
  },
  {
    title: "项目管理",
    routes: [
      { method: "GET", path: "/api/v1/projects", summary: "项目分页列表", ui: "项目管理", auth: true },
      { method: "POST", path: "/api/v1/projects", summary: "创建项目", ui: "项目管理", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id", summary: "更新项目", ui: "项目管理", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id", summary: "删除项目", ui: "项目管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/members", summary: "项目成员列表", ui: "项目成员", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/members", summary: "添加项目成员", ui: "项目成员", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/members/:memberId", summary: "更新项目成员角色", ui: "项目成员", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/members/:memberId", summary: "移除项目成员", ui: "项目成员", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/server-groups/tree", summary: "服务器分组树", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/server-groups", summary: "创建/更新服务器分组", ui: "服务器管理", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/server-groups/:groupId", summary: "更新服务器分组", ui: "服务器管理", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/server-groups/:groupId", summary: "删除服务器分组", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers", summary: "服务器分页列表", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers", summary: "创建/更新服务器", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers/:serverId", summary: "服务器详情", ui: "服务器管理/操作台", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers/:serverId/my-access", summary: "当前用户对该服务器的有效权限", ui: "服务器操作台", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/servers/:serverId", summary: "删除服务器", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers/:serverId/exec", summary: "执行服务器命令", ui: "服务器操作台", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers/:serverId/terminal/ws", summary: "交互式终端 WebSocket", ui: "服务器操作台", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers/test", summary: "单机连通性测试", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers/test/batch", summary: "批量连通性测试", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers/sync", summary: "同步服务器状态", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/servers/import", summary: "导入服务器", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers/import-template", summary: "下载服务器导入模板", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/servers/export", summary: "导出服务器", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/server-access-grants", summary: "服务器资源授权列表", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/server-access-grants", summary: "保存服务器资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/server-access-grants/bulk", summary: "批量保存服务器资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/server-access-grants/bootstrap", summary: "存量成员服务器授权迁移", ui: "项目成员 · 资源授权", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/server-access-grants/:grantId", summary: "删除服务器资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cloud-accounts", summary: "云账号列表", ui: "服务器管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cloud-accounts", summary: "创建云账号", ui: "服务器管理", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cloud-accounts/:accountId", summary: "更新云账号", ui: "服务器管理", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cloud-accounts/:accountId/sync", summary: "同步云实例", ui: "服务器管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/services", summary: "项目服务列表", ui: "服务配置", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/services", summary: "创建/更新项目服务", ui: "服务配置", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/services/:serviceId", summary: "删除项目服务", ui: "服务配置", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/service-catalog", summary: "服务目录列表", ui: "服务目录", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/service-catalog", summary: "创建/更新服务目录", ui: "服务目录", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/service-catalog/:catalogId", summary: "服务目录详情", ui: "服务画像", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/service-catalog/:catalogId/portrait", summary: "服务画像聚合", ui: "服务画像", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/service-catalog/:catalogId", summary: "删除服务目录", ui: "服务目录", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/service-catalog/:catalogId/links", summary: "绑定服务关联", ui: "服务目录", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/service-catalog/:catalogId/links/:linkId", summary: "解绑服务关联", ui: "服务目录", auth: true },
      { method: "GET", path: "/api/v1/alerts/quality-report", summary: "告警质量报告", ui: "告警质量", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/:runId/verify", summary: "发布后验证", ui: "CI/CD", auth: true },
      { method: "POST", path: "/api/v1/deployments/preview-apply", summary: "工作负载预检 diff", ui: "K8s", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/log-sources", summary: "日志源列表", ui: "日志源配置", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/log-sources", summary: "创建/更新日志源", ui: "日志源配置", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/log-sources/:logSourceId", summary: "删除日志源", ui: "日志源配置", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/logs/search", summary: "日志检索（ES）", ui: "日志平台", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/logs/export", summary: "导出日志（ES）", ui: "日志平台", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/bootstrap", summary: "Agent 引导登记", ui: "Agent 管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/loggie/status", summary: "Agent 状态列表", ui: "Agent 管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/loggie/bootstrap-sources", summary: "引导日志源预览", ui: "Agent 管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/loggie/pipeline/download", summary: "下载 Agent 配置", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/deploy", summary: "SSH 热更配置", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/install", summary: "SSH 安装 Agent", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/uninstall", summary: "SSH 卸载并删除登记", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/start", summary: "SSH 启动 Agent", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/stop", summary: "SSH 停止 Agent", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/restart", summary: "SSH 重启 Agent", ui: "Agent 管理", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/loggie/sync", summary: "从日志源同步并下发", ui: "Agent 管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/mysql-backup/instances", summary: "MySQL备份实例列表", ui: "MySQL 备份", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/mysql-backup/instances", summary: "MySQL备份实例创建", ui: "MySQL 备份", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/mysql-backup/instances/:instanceId", summary: "MySQL备份实例更新", ui: "MySQL 备份", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/mysql-backup/instances/:instanceId", summary: "MySQL备份实例删除", ui: "MySQL 备份", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/ping", summary: "MySQL备份连通测试", ui: "MySQL 备份", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/check-remote", summary: "MySQL远端备份检查", ui: "MySQL 备份", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/run", summary: "MySQL执行备份", ui: "MySQL 备份", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/mysql-backup/jobs", summary: "MySQL备份任务列表", ui: "MySQL 备份", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/mysql-backup/jobs/:jobId/presign", summary: "MySQL备份预签名下载", ui: "MySQL 备份", auth: true },
    ],
  },
  {
    title: "CI/CD",
    routes: [
      { method: "GET", path: "/api/v1/projects/:id/cicd-access-grants", summary: "CI/CD 资源授权列表", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd-access-grants", summary: "保存 CI/CD 资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd-access-grants/bulk", summary: "批量保存 CI/CD 资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd-access-grants/bootstrap", summary: "存量成员 CI/CD 授权迁移", ui: "项目成员 · 资源授权", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/cicd-access-grants/:grantId", summary: "删除 CI/CD 资源授权", ui: "项目成员 · 资源授权", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services", summary: "CI/CD 应用服务列表", ui: "应用服务", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/services", summary: "CI/CD 创建应用服务", ui: "应用服务", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services/:serviceId", summary: "CI/CD 应用服务详情", ui: "应用服务", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cicd/services/:serviceId", summary: "CI/CD 更新应用服务", ui: "应用服务", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/cicd/services/:serviceId", summary: "CI/CD 删除应用服务", ui: "应用服务", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services/:serviceId/ci-config", summary: "CI/CD CI 配置查询", ui: "应用服务 · CI 配置", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cicd/services/:serviceId/ci-config", summary: "CI/CD CI 配置保存", ui: "应用服务 · CI 配置", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs", summary: "CI/CD 发布配置列表", ui: "应用服务 · 发布配置", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs", summary: "CI/CD 创建发布配置", ui: "应用服务 · 发布配置", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs/:configId", summary: "CI/CD 更新发布配置", ui: "应用服务 · 发布配置", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs/:configId", summary: "CI/CD 删除发布配置", ui: "应用服务 · 发布配置", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services/:serviceId/artifacts", summary: "CI/CD MinIO 制品列表", ui: "应用服务 · 发布", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/services/:serviceId/helm-scaffold", summary: "下载 Helm 脚手架 zip", ui: "应用服务 · 容器化发布", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/helm-scaffold", summary: "预览下载 Helm 脚手架", ui: "应用服务 · 容器化发布", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/services/:serviceId/builds", summary: "CI/CD 触发 CI 构建", ui: "应用服务 · CI 打包", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/services/:serviceId/releases", summary: "CI/CD 触发 CD 发布", ui: "应用服务 · 发布", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/build-runs", summary: "CI/CD CI 打包记录列表", ui: "CI 打包记录", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/build-runs/:runId", summary: "CI/CD CI 打包记录详情", ui: "CI 打包记录", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/build-runs/:runId/log", summary: "CI/CD CI 构建日志", ui: "CI 打包记录", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/cicd/build-runs/:runId", summary: "CI/CD 删除 CI 打包记录", ui: "CI 打包记录", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/approval-flow", summary: "CI/CD 审批流查询", ui: "审批管理", auth: true },
      { method: "PUT", path: "/api/v1/projects/:id/cicd/approval-flow", summary: "CI/CD 审批流保存", ui: "审批管理", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/release-runs", summary: "CI/CD CD 工单列表", ui: "待办列表 / CD 历史工单", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/release-runs/:runId", summary: "CI/CD CD 工单详情", ui: "待办列表 / CD 历史工单", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/release-runs/:runId/approval-steps", summary: "CI/CD 工单审批步骤", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/:runId/approve", summary: "CI/CD 审批通过", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/:runId/reject", summary: "CI/CD 审批驳回", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/:runId/execute", summary: "CI/CD 执行发布", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/:runId/terminate", summary: "CI/CD 终止发布", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/batch-approve", summary: "CI/CD 批量审批通过", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/batch-reject", summary: "CI/CD 批量审批驳回", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/batch-execute", summary: "CI/CD 批量执行发布", ui: "待办列表", auth: true },
      { method: "POST", path: "/api/v1/projects/:id/cicd/release-runs/batch-terminate", summary: "CI/CD 批量终止发布", ui: "待办列表", auth: true },
      { method: "GET", path: "/api/v1/projects/:id/cicd/release-runs/:runId/log", summary: "CI/CD CD 发布日志", ui: "CD 历史工单", auth: true },
      { method: "DELETE", path: "/api/v1/projects/:id/cicd/release-runs/:runId", summary: "CI/CD 删除 CD 工单", ui: "CD 历史工单", auth: true },
    ],
  },
];
