package logplatform

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"yunshu/internal/config"
	"yunshu/internal/model"
)

const defaultClusterLogRateLimitQPS = 2000
const minInheritedRateLimitQPS = 50

var defaultExcludeNamespaces = []string{
	"kube-system", "kube-public", "kube-node-lease", "yunshu-logging",
}

// BuildClusterPipelinesYAML 按集群规则生成 pipelines.yml（DaemonSet 共用一份）。
func BuildClusterPipelinesYAML(
	projectID, clusterID uint,
	rules []model.ClusterLogRule,
	esCfg config.ElasticsearchConfig,
	kafkaCfg config.KafkaConfig,
	projectRateLimitQPS int,
) string {
	if projectRateLimitQPS <= 0 {
		projectRateLimitQPS = defaultClusterLogRateLimitQPS
	}
	alloc := allocateRuleRateLimits(rules, projectRateLimitQPS)
	var body strings.Builder
	body.WriteString("# Generated by Yunshu — K8s cluster log pipelines\n")
	body.WriteString(fmt.Sprintf("# project_id=%d cluster_id=%d collector_mode=k8s project_rate_limit_qps=%d\n", projectID, clusterID, projectRateLimitQPS))
	body.WriteString("# rate_limit: fixed rules keep rate_limit_qps; others share remaining project budget equally\n")
	body.WriteString("pipelines:\n")

	sink := renderClusterSinkBlock(clusterID, esCfg, kafkaCfg)
	n := 0
	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}
		paths := clusterRulePaths(rule)
		if len(paths) == 0 {
			continue
		}
		n++
		profile := strings.TrimSpace(rule.ParseProfile)
		if profile == "" {
			profile = "cri"
		}
		qps := alloc[rule.ID]
		if qps <= 0 {
			qps = projectRateLimitQPS
		}
		body.WriteString(renderClusterPipelineEntry(projectID, clusterID, rule, paths, profile, sink, qps))
	}
	if n == 0 {
		body.WriteString(renderClusterPipelineEntry(
			projectID,
			clusterID,
			model.ClusterLogRule{ID: 0, Name: "default", ParseProfile: "cri"},
			[]string{"/var/log/pods/*_*_*/*/*.log"},
			"cri",
			sink,
			projectRateLimitQPS,
		))
	}
	return body.String()
}

// allocateRuleRateLimits 将项目 QPS 配额拆到启用规则：
// - rate_limit_qps>0：固定占用
// - =0：均分剩余配额（至少 minInheritedRateLimitQPS）
func allocateRuleRateLimits(rules []model.ClusterLogRule, projectQPS int) map[uint]int {
	if projectQPS <= 0 {
		projectQPS = defaultClusterLogRateLimitQPS
	}
	out := make(map[uint]int)
	inheritIDs := make([]uint, 0, len(rules))
	fixedSum := 0
	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}
		if len(clusterRulePaths(rule)) == 0 {
			continue
		}
		if rule.RateLimitQPS > 0 {
			out[rule.ID] = rule.RateLimitQPS
			fixedSum += rule.RateLimitQPS
			continue
		}
		inheritIDs = append(inheritIDs, rule.ID)
	}
	if len(inheritIDs) == 0 {
		return out
	}
	remain := projectQPS - fixedSum
	if remain < 0 {
		remain = 0
	}
	base := remain / len(inheritIDs)
	extra := remain % len(inheritIDs)
	for i, id := range inheritIDs {
		q := base
		if i < extra {
			q++
		}
		if q < minInheritedRateLimitQPS {
			q = minInheritedRateLimitQPS
		}
		out[id] = q
	}
	return out
}

func renderClusterPipelineEntry(
	projectID, clusterID uint,
	rule model.ClusterLogRule,
	paths []string,
	profileName, sinkBlock string,
	rateLimitQPS int,
) string {
	pn := strings.TrimSpace(profileName)
	parseProfile := detectParseProfile(paths[0], &pn)
	if parseProfile.multilinePattern == "" {
		parseProfile = profileCRI()
	}
	var pathsLines strings.Builder
	for _, p := range paths {
		pathsLines.WriteString("          - ")
		pathsLines.WriteString(quoteYAML(p))
		pathsLines.WriteByte('\n')
	}
	excludeBlock := ""
	if excludes := clusterRuleExcludeFiles(rule); len(excludes) > 0 {
		var b strings.Builder
		b.WriteString("        excludeFiles:\n")
		for _, e := range excludes {
			b.WriteString("          - ")
			b.WriteString(quoteYAML(e))
			b.WriteByte('\n')
		}
		excludeBlock = b.String()
	}
	pipeName := fmt.Sprintf("yunshu-k8s-p%d-c%d-r%d", projectID, clusterID, rule.ID)
	if rule.ID == 0 {
		pipeName = fmt.Sprintf("yunshu-k8s-p%d-c%d-default", projectID, clusterID)
	}
	sourceName := fmt.Sprintf("rule-%d", rule.ID)
	if rule.ID == 0 {
		sourceName = "default"
	}
	interceptorBlock := ""
	if parseProfile.hasTransformer() {
		interceptorBlock = parseProfile.renderTransformerActions()
	}
	interceptorBlock = ensureFileMetaActions(interceptorBlock, paths)
	interceptorBlock = ensureRateLimitInterceptor(interceptorBlock, rateLimitQPS)
	multiBlock := ""
	if pat := strings.TrimSpace(parseProfile.multilinePattern); pat != "" {
		multiBlock = fmt.Sprintf(`        multi:
          active: true
          pattern: '%s'
          maxLines: %d
          timeout: 5s
`, pat, parseProfile.multilineMaxLines())
	}
	ruleName := strings.TrimSpace(rule.Name)
	if ruleName == "" {
		ruleName = "default"
	}
	return fmt.Sprintf(`  - name: %s
    sources:
      - type: file
        name: %s
        paths:
%s%s        addonMeta: true
        readFromTail: false
        fields:
          project_id: %q
          cluster_id: %q
          collector_mode: "k8s"
          log_rule_id: %q
          log_rule_name: %q
%s%s%s
`,
		pipeName,
		sourceName,
		pathsLines.String(),
		excludeBlock,
		fmt.Sprintf("%d", projectID),
		fmt.Sprintf("%d", clusterID),
		fmt.Sprintf("%d", rule.ID),
		ruleName,
		multiBlock,
		interceptorBlock,
		sinkBlock,
	)
}

func ensureRateLimitInterceptor(interceptorBlock string, qps int) string {
	if qps <= 0 {
		return interceptorBlock
	}
	rateEntry := fmt.Sprintf("      - type: rateLimit\n        qps: %d\n", qps)
	block := strings.TrimSpace(interceptorBlock)
	if block == "" {
		return "    interceptors:\n" + rateEntry
	}
	const head = "    interceptors:\n"
	if strings.HasPrefix(interceptorBlock, head) {
		return head + rateEntry + strings.TrimPrefix(interceptorBlock, head)
	}
	return interceptorBlock + rateEntry
}

func clusterRulePaths(rule model.ClusterLogRule) []string {
	nss := parseJSONStringSlice(rule.MatchNamespaces)
	workloads := parseJSONStringSlice(rule.MatchWorkloads)
	excludes := parseJSONStringSlice(rule.ExcludeNamespaces)
	if len(excludes) == 0 {
		excludes = append([]string{}, defaultExcludeNamespaces...)
	}
	excludeSet := map[string]struct{}{}
	for _, e := range excludes {
		excludeSet[e] = struct{}{}
	}

	var paths []string
	appendPath := func(ns, workload string) {
		if ns != "" {
			if _, skip := excludeSet[ns]; skip {
				return
			}
		}
		switch {
		case ns != "" && workload != "":
			paths = append(paths, fmt.Sprintf("/var/log/pods/%s_%s-*_*/*/*.log", ns, workload))
		case ns != "":
			paths = append(paths, fmt.Sprintf("/var/log/pods/%s_*_*/*/*.log", ns))
		case workload != "":
			paths = append(paths, fmt.Sprintf("/var/log/pods/*_%s-*_*/*/*.log", workload))
		}
	}

	if len(nss) == 0 && len(workloads) == 0 {
		// 宽采：glob 无法否定系统 ns，配合 excludeFiles
		return []string{"/var/log/pods/*_*_*/*/*.log"}
	}
	if len(nss) == 0 {
		for _, w := range workloads {
			appendPath("", w)
		}
		return dedupeStrings(paths)
	}
	if len(workloads) == 0 {
		for _, ns := range nss {
			appendPath(ns, "")
		}
		return dedupeStrings(paths)
	}
	for _, ns := range nss {
		for _, w := range workloads {
			appendPath(ns, w)
		}
	}
	return dedupeStrings(paths)
}

// clusterRuleExcludeFiles 宽采或仅按 workload 匹配时，用 excludeFiles 排除系统命名空间路径。
func clusterRuleExcludeFiles(rule model.ClusterLogRule) []string {
	nss := parseJSONStringSlice(rule.MatchNamespaces)
	if len(nss) > 0 {
		return nil
	}
	excludes := parseJSONStringSlice(rule.ExcludeNamespaces)
	if len(excludes) == 0 {
		excludes = append([]string{}, defaultExcludeNamespaces...)
	}
	out := make([]string, 0, len(excludes))
	for _, e := range excludes {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		// /var/log/pods/{ns}_{pod}_{uid}/...
		out = append(out, `/var/log/pods/`+regexp.QuoteMeta(e)+`_`)
	}
	return out
}

func parseJSONStringSlice(raw string) []string {
	raw = strings.TrimSpace(raw)
	if raw == "" || raw == "null" {
		return nil
	}
	var arr []string
	if err := json.Unmarshal([]byte(raw), &arr); err != nil {
		parts := strings.FieldsFunc(raw, func(r rune) bool {
			return r == ',' || r == '\n' || r == ';'
		})
		out := make([]string, 0, len(parts))
		for _, p := range parts {
			if v := strings.TrimSpace(p); v != "" {
				out = append(out, v)
			}
		}
		return out
	}
	out := make([]string, 0, len(arr))
	for _, it := range arr {
		if v := strings.TrimSpace(it); v != "" {
			out = append(out, v)
		}
	}
	return out
}

func dedupeStrings(in []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}

func renderClusterSinkBlock(clusterID uint, esCfg config.ElasticsearchConfig, kafkaCfg config.KafkaConfig) string {
	esCfg = esCfg.Normalized()
	kafkaCfg = kafkaCfg.Normalized()
	if kafkaCfg.Enabled {
		var brokers strings.Builder
		for _, b := range kafkaCfg.Brokers {
			b = strings.TrimSpace(b)
			if b == "" {
				continue
			}
			brokers.WriteString("        - ")
			brokers.WriteString(quoteYAML(b))
			brokers.WriteByte('\n')
		}
		if brokers.Len() == 0 {
			brokers.WriteString("        - \"127.0.0.1:9092\"\n")
		}
		sasl := ""
		if u := strings.TrimSpace(kafkaCfg.Username); u != "" {
			mech := kafkaCfg.SASLMechanism
			if mech == "" || mech == "none" {
				mech = "plain"
			}
			sasl = fmt.Sprintf(`
      sasl:
        type: %s
        userName: %s
        password: %s`, quoteYAML(mech), quoteYAML(u), quoteYAML(kafkaCfg.Password))
		}
		topic := K8sKafkaTopicTemplate(clusterID, defaultK8sIndexPrefix)
		return fmt.Sprintf(`    sink:
      type: kafka
      brokers:
%s      topic: %s
      codec:
        type: json%s
`, brokers.String(), quoteYAML(topic), sasl)
	}

	indexSink := K8sIndexSink(clusterID)
	var hostsLines strings.Builder
	for _, h := range esCfg.Addresses {
		h = strings.TrimSpace(h)
		if h == "" {
			continue
		}
		hostsLines.WriteString("        - ")
		hostsLines.WriteString(quoteYAML(h))
		hostsLines.WriteByte('\n')
	}
	if hostsLines.Len() == 0 {
		hostsLines.WriteString("        - \"http://127.0.0.1:9200\"\n")
	}
	sinkAuth := ""
	if u := strings.TrimSpace(esCfg.Username); u != "" {
		sinkAuth += fmt.Sprintf("\n      username: %s", quoteYAML(u))
	}
	if p := strings.TrimSpace(esCfg.Password); p != "" {
		sinkAuth += fmt.Sprintf("\n      password: %s", quoteYAML(p))
	}
	return fmt.Sprintf(`    sink:
      type: elasticsearch
      hosts:
%s      index: %s
      codec:
        type: json
        beatsFormat: true%s
`, hostsLines.String(), quoteYAML(indexSink), sinkAuth)
}

// RenderClusterSystemConfigYAML DaemonSet 内 Loggie 系统配置。
func RenderClusterSystemConfigYAML(projectID, clusterID uint, monitorPort int) string {
	if monitorPort <= 0 {
		monitorPort = 9196
	}
	return fmt.Sprintf(`# Generated by Yunshu — K8s DaemonSet system config
# project_id=%d cluster_id=%d
loggie:
  reload:
    enabled: true
    period: 10s
  http:
    enabled: true
    host: "0.0.0.0"
    port: %d
  defaults:
    interceptors:
      - type: schema
        name: global
        order: 700
        addMeta:
          timestamp:
            key: "@timestamp"
            location: Local
            layout: "2006-01-02T15:04:05.000Z07:00"
  monitor:
    enabled: true
    listeners:
      filesource: ~
      filewatcher: ~
      sink: ~
      queue: ~
`, projectID, clusterID, monitorPort)
}
