package cmd

import "yunshu/internal/model"

func seedPermissionsSystem() []model.Permission {
	return []model.Permission{
		{Name: "用户列表", Resource: "/api/v1/users", Action: "GET", Description: "View user list"},
		{Name: "创建用户", Resource: "/api/v1/users", Action: "POST", Description: "Create user"},
		{Name: "用户详情", Resource: "/api/v1/users/:id", Action: "GET", Description: "View user detail"},
		{Name: "更新用户", Resource: "/api/v1/users/:id", Action: "PUT", Description: "Update user"},
		{Name: "删除用户", Resource: "/api/v1/users/:id", Action: "DELETE", Description: "Delete user"},
		{Name: "分配用户角色", Resource: "/api/v1/users/:id/roles", Action: "PUT", Description: "Assign roles to user"},
		{Name: "导出用户", Resource: "/api/v1/users/export", Action: "GET", Description: "Export users to Excel"},
		{Name: "用户导入模板", Resource: "/api/v1/users/import-template", Action: "GET", Description: "Download users import template"},
		{Name: "导入用户", Resource: "/api/v1/users/import", Action: "POST", Description: "Import users from Excel"},
		{Name: "角色列表", Resource: "/api/v1/roles", Action: "GET", Description: "View role list"},
		{Name: "创建角色", Resource: "/api/v1/roles", Action: "POST", Description: "Create role"},
		{Name: "角色详情", Resource: "/api/v1/roles/:id", Action: "GET", Description: "View role detail"},
		{Name: "更新角色", Resource: "/api/v1/roles/:id", Action: "PUT", Description: "Update role"},
		{Name: "删除角色", Resource: "/api/v1/roles/:id", Action: "DELETE", Description: "Delete role"},
		{Name: "用户组列表", Resource: "/api/v1/user-groups", Action: "GET", Description: "List user groups"},
		{Name: "创建用户组", Resource: "/api/v1/user-groups", Action: "POST", Description: "Create user group"},
		{Name: "用户组详情", Resource: "/api/v1/user-groups/:id", Action: "GET", Description: "View user group detail"},
		{Name: "更新用户组", Resource: "/api/v1/user-groups/:id", Action: "PUT", Description: "Update user group"},
		{Name: "删除用户组", Resource: "/api/v1/user-groups/:id", Action: "DELETE", Description: "Delete user group"},
		{Name: "分配用户组成员", Resource: "/api/v1/user-groups/:id/users", Action: "PUT", Description: "Replace members of user group"},
		{Name: "部门树", Resource: "/api/v1/departments/tree", Action: "GET", Description: "View department tree"},
		{Name: "部门详情", Resource: "/api/v1/departments/:id", Action: "GET", Description: "View department detail"},
		{Name: "创建部门", Resource: "/api/v1/departments", Action: "POST", Description: "Create department"},
		{Name: "更新部门", Resource: "/api/v1/departments/:id", Action: "PUT", Description: "Update department"},
		{Name: "删除部门", Resource: "/api/v1/departments/:id", Action: "DELETE", Description: "Delete department"},
		{Name: "API列表", Resource: "/api/v1/permissions", Action: "GET", Description: "View permission list"},
		{Name: "创建API", Resource: "/api/v1/permissions", Action: "POST", Description: "Create permission"},
		{Name: "批量更新 K8s 范围校验", Resource: "/api/v1/permissions/k8s-scope/batch", Action: "POST", Description: "Batch enable or disable k8s scope for cluster APIs"},
		{Name: "API详情", Resource: "/api/v1/permissions/:id", Action: "GET", Description: "View permission detail"},
		{Name: "更新API", Resource: "/api/v1/permissions/:id", Action: "PUT", Description: "Update permission"},
		{Name: "删除API", Resource: "/api/v1/permissions/:id", Action: "DELETE", Description: "Delete permission"},
		{Name: "授权列表", Resource: "/api/v1/policies", Action: "GET", Description: "View policy list"},
		{Name: "创建授权策略", Resource: "/api/v1/policies", Action: "POST", Description: "Grant permission to role"},
		{Name: "删除授权策略", Resource: "/api/v1/policies", Action: "DELETE", Description: "Revoke permission from role (JSON body)"},
		{Name: "权限菜单关联", Resource: "/api/v1/policies/menu-links", Action: "GET", Description: "List permission to menu path links"},
		{Name: "策略冲突分析", Resource: "/api/v1/policies/conflicts", Action: "GET", Description: "Analyze role policy conflicts"},
		{Name: "一键补齐入口API", Resource: "/api/v1/policies/conflicts/fix-menu-entry", Action: "POST", Description: "Create missing menu entry permissions and grant to role"},
		{Name: "清理禁用插件策略", Resource: "/api/v1/policies/conflicts/fix-disabled-plugin", Action: "POST", Description: "Revoke Casbin policies whose API belongs to a disabled plugin"},
		{Name: "统一权限树", Resource: "/api/v1/policies/permission-tree", Action: "GET", Description: "Get menu+API permission tree for role"},
		{Name: "策略模拟", Resource: "/api/v1/policies/simulate", Action: "POST", Description: "Simulate API authorization layers"},
		{Name: "注册审核列表", Resource: "/api/v1/registrations", Action: "GET", Description: "View registration requests"},
		{Name: "审核注册申请", Resource: "/api/v1/registrations/:id/review", Action: "POST", Description: "Review registration request"},
		{Name: "菜单管理列表", Resource: "/api/v1/menus", Action: "GET", Description: "List all menus for administration"},
		{Name: "创建菜单", Resource: "/api/v1/menus", Action: "POST", Description: "Create menu"},
		{Name: "批量更新菜单状态", Resource: "/api/v1/menus/status", Action: "PUT", Description: "Batch update menu status"},
		{Name: "更新菜单", Resource: "/api/v1/menus/:id", Action: "PUT", Description: "Update menu"},
		{Name: "删除菜单", Resource: "/api/v1/menus/:id", Action: "DELETE", Description: "Delete menu"},
		{Name: "菜单入口权限绑定", Resource: "/api/v1/menus/:id/bindings", Action: "GET", Description: "Get menu entry permission bindings"},
		{Name: "更新菜单入口权限绑定", Resource: "/api/v1/menus/:id/bindings", Action: "PUT", Description: "Replace menu entry permission bindings"},
		{Name: "数据字典列表", Resource: "/api/v1/dict/entries", Action: "GET", Description: "List dict entries"},
		{Name: "数据字典新增", Resource: "/api/v1/dict/entries", Action: "POST", Description: "Create dict entry"},
		{Name: "数据字典更新", Resource: "/api/v1/dict/entries/:id", Action: "PUT", Description: "Update dict entry"},
		{Name: "数据字典删除", Resource: "/api/v1/dict/entries/:id", Action: "DELETE", Description: "Delete dict entry"},
		{Name: "数据字典下拉", Resource: "/api/v1/dict/options/:dictType", Action: "GET", Description: "Dict options for UI"},
		{Name: "数据字典敏感明文", Resource: "/api/v1/dict/entries/:id/reveal-value", Action: "POST", Description: "Reveal sensitive dict entry value"},
		{Name: "登录日志列表", Resource: "/api/v1/login-logs", Action: "GET", Description: "View login logs"},
		{Name: "导出登录日志", Resource: "/api/v1/login-logs/export", Action: "GET", Description: "Export login logs to Excel"},
		{Name: "删除登录日志", Resource: "/api/v1/login-logs/:id", Action: "DELETE", Description: "Delete login log"},
		{Name: "批量删除登录日志", Resource: "/api/v1/login-logs/delete", Action: "POST", Description: "Batch delete login logs"},
		{Name: "操作历史列表", Resource: "/api/v1/operation-logs", Action: "GET", Description: "View operation logs"},
		{Name: "导出操作历史", Resource: "/api/v1/operation-logs/export", Action: "GET", Description: "Export operation logs to Excel"},
		{Name: "删除操作历史", Resource: "/api/v1/operation-logs/:id", Action: "DELETE", Description: "Delete operation log"},
		{Name: "批量删除操作历史", Resource: "/api/v1/operation-logs/delete", Action: "POST", Description: "Batch delete operation logs"},
		{Name: "查看封禁 IP 列表", Resource: "/api/v1/security/banned-ips", Action: "GET", Description: "View banned IPs list"},
		{Name: "解除封禁 IP", Resource: "/api/v1/security/banned-ips/unban", Action: "POST", Description: "Unban IP"},
		{Name: "总览页面", Resource: "/api/v1/overview", Action: "GET", Description: "Get system overview metrics"},
		{Name: "总览项目上线统计", Resource: "/api/v1/overview/project-launches", Action: "GET", Description: "Get project launch stats for last 30 days"},
		{Name: "总览工单按人统计", Resource: "/api/v1/overview/release-by-person", Action: "GET", Description: "Get release runs by submitter for last 30 days"},
		{Name: "插件列表", Resource: "/api/v1/plugins", Action: "GET", Description: "List enabled plugins"},
	}
}

