package cmd

import "yunshu/internal/model"

func seedPermissionsDbmgmt() []model.Permission {
	return []model.Permission{
		{Name: "MySQL备份实例列表", Resource: "/api/v1/projects/:id/mysql-backup/instances", Action: "GET", Description: "List MySQL backup instances"},
		{Name: "MySQL备份实例创建", Resource: "/api/v1/projects/:id/mysql-backup/instances", Action: "POST", Description: "Create MySQL backup instance"},
		{Name: "MySQL备份实例更新", Resource: "/api/v1/projects/:id/mysql-backup/instances/:instanceId", Action: "PUT", Description: "Update MySQL backup instance"},
		{Name: "MySQL备份实例删除", Resource: "/api/v1/projects/:id/mysql-backup/instances/:instanceId", Action: "DELETE", Description: "Delete MySQL backup instance"},
		{Name: "MySQL备份连通测试", Resource: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/ping", Action: "POST", Description: "Ping MySQL backup instance"},
		{Name: "MySQL远端备份检查", Resource: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/check-remote", Action: "POST", Description: "Check remote xtrabackup backup"},
		{Name: "MySQL执行备份", Resource: "/api/v1/projects/:id/mysql-backup/instances/:instanceId/run", Action: "POST", Description: "Run MySQL backup job"},
		{Name: "MySQL备份任务列表", Resource: "/api/v1/projects/:id/mysql-backup/jobs", Action: "GET", Description: "List MySQL backup jobs"},
		{Name: "MySQL备份任务停止", Resource: "/api/v1/projects/:id/mysql-backup/jobs/:jobId/stop", Action: "POST", Description: "Stop running MySQL backup job"},
		{Name: "MySQL备份任务删除", Resource: "/api/v1/projects/:id/mysql-backup/jobs/:jobId", Action: "DELETE", Description: "Delete MySQL backup job record"},
		{Name: "MySQL备份预签名下载", Resource: "/api/v1/projects/:id/mysql-backup/jobs/:jobId/presign", Action: "GET", Description: "Presign MySQL backup download URL"},
		{Name: "MySQL备份Dump选项", Resource: "/api/v1/projects/:id/mysql-backup/mysqldump-options", Action: "GET", Description: "List mysqldump backup options"},
		{Name: "数据库实例列表", Resource: "/api/v1/projects/:id/dbmgmt/instances", Action: "GET", Description: "List DB instances"},
		{Name: "数据库实例创建", Resource: "/api/v1/projects/:id/dbmgmt/instances", Action: "POST", Description: "Create DB instance"},
		{Name: "数据库实例详情", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId", Action: "GET", Description: "Get DB instance"},
		{Name: "数据库实例更新", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId", Action: "PUT", Description: "Update DB instance"},
		{Name: "数据库实例删除", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId", Action: "DELETE", Description: "Delete DB instance"},
		{Name: "数据库实例探活", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/ping", Action: "POST", Description: "Ping DB instance"},
		{Name: "数据库元数据库列表", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/metadata/databases", Action: "GET", Description: "List databases"},
		{Name: "数据库元数据表列表", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/metadata/tables", Action: "GET", Description: "List tables"},
		{Name: "数据库元数据列列表", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/metadata/columns", Action: "GET", Description: "List columns"},
		{Name: "数据库只读查询", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/query", Action: "POST", Description: "Execute read-only SQL"},
		{Name: "数据库写操作", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/execute", Action: "POST", Description: "Execute SQL with approval"},
		{Name: "数据库SQL导入", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/import", Action: "POST", Description: "Import SQL file"},
		{Name: "数据库授权列表", Resource: "/api/v1/projects/:id/dbmgmt/grants", Action: "GET", Description: "List DB grants"},
		{Name: "数据库授权创建", Resource: "/api/v1/projects/:id/dbmgmt/grants", Action: "POST", Description: "Create DB grant"},
		{Name: "数据库授权删除", Resource: "/api/v1/projects/:id/dbmgmt/grants/:grantId", Action: "DELETE", Description: "Delete DB grant"},
		{Name: "数据库授权更新", Resource: "/api/v1/projects/:id/dbmgmt/grants/:grantId", Action: "PUT", Description: "Update DB grant"},
		{Name: "数据库SQL预检", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/check", Action: "POST", Description: "Check SQL via goInception"},
		{Name: "数据库工单详情", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId", Action: "GET", Description: "Get DB SQL ticket detail"},
		{Name: "数据库工单审批步骤", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/steps", Action: "GET", Description: "List DB ticket approval steps"},
		{Name: "数据库工单回滚SQL", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/rollback", Action: "GET", Description: "Get DB ticket rollback SQL"},
		{Name: "数据库工单回滚预览", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/rollback/preview", Action: "GET", Description: "Preview DB rollback ticket"},
		{Name: "数据库工单回滚提交", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/rollback/submit", Action: "POST", Description: "Submit DB rollback ticket"},
		{Name: "数据库工单OSC列表", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/osc", Action: "GET", Description: "List DB ticket OSC jobs"},
		{Name: "数据库工单OSC进度", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/osc/:sqlsha1", Action: "GET", Description: "Get DB ticket OSC percent"},
		{Name: "数据库工单OSC控制", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/osc/:sqlsha1/control", Action: "POST", Description: "Control DB ticket OSC job"},
		{Name: "数据库有效权限", Resource: "/api/v1/projects/:id/dbmgmt/grants/effective", Action: "GET", Description: "Get effective DB permission"},
		{Name: "数据库审批流查询", Resource: "/api/v1/projects/:id/dbmgmt/approval-flow", Action: "GET", Description: "Get DB approval flow"},
		{Name: "数据库审批流保存", Resource: "/api/v1/projects/:id/dbmgmt/approval-flow", Action: "PUT", Description: "Upsert DB approval flow"},
		{Name: "数据库权限申请列表", Resource: "/api/v1/projects/:id/dbmgmt/access-requests", Action: "GET", Description: "List DB access requests"},
		{Name: "数据库权限申请创建", Resource: "/api/v1/projects/:id/dbmgmt/access-requests", Action: "POST", Description: "Create DB access request"},
		{Name: "数据库权限申请通过", Resource: "/api/v1/projects/:id/dbmgmt/access-requests/:requestId/approve", Action: "POST", Description: "Approve DB access request"},
		{Name: "数据库权限申请拒绝", Resource: "/api/v1/projects/:id/dbmgmt/access-requests/:requestId/reject", Action: "POST", Description: "Reject DB access request"},
		{Name: "应用用户权限申请列表", Resource: "/api/v1/projects/:id/dbmgmt/app-user-requests", Action: "GET", Description: "List DB app user requests"},
		{Name: "应用用户权限申请创建", Resource: "/api/v1/projects/:id/dbmgmt/app-user-requests", Action: "POST", Description: "Create DB app user request"},
		{Name: "应用用户权限申请通过", Resource: "/api/v1/projects/:id/dbmgmt/app-user-requests/:requestId/approve", Action: "POST", Description: "Approve DB app user request"},
		{Name: "应用用户权限申请拒绝", Resource: "/api/v1/projects/:id/dbmgmt/app-user-requests/:requestId/reject", Action: "POST", Description: "Reject DB app user request"},
		{Name: "实例 MySQL 用户列表", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/mysql-users", Action: "GET", Description: "List MySQL users on instance"},
		{Name: "实例 MySQL 用户权限查询", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/mysql-user-privileges", Action: "GET", Description: "Get MySQL user privileges for apply form"},
		{Name: "列脱敏规则列表", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/column-mask-rules", Action: "GET", Description: "List DB column mask rules"},
		{Name: "列脱敏规则保存", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/column-mask-rules", Action: "POST", Description: "Upsert DB column mask rule"},
		{Name: "列脱敏规则删除", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/column-mask-rules/:ruleId", Action: "DELETE", Description: "Delete DB column mask rule"},
		{Name: "实例账号密码查看", Resource: "/api/v1/projects/:id/dbmgmt/instances/:instanceId/accounts/:accountId/password", Action: "GET", Description: "Reveal platform-managed account password"},
		{Name: "数据库工单列表", Resource: "/api/v1/projects/:id/dbmgmt/tickets", Action: "GET", Description: "List DB SQL tickets"},
		{Name: "数据库工单审批通过", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/approve", Action: "POST", Description: "Approve DB SQL ticket"},
		{Name: "数据库工单审批拒绝", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/reject", Action: "POST", Description: "Reject DB SQL ticket"},
		{Name: "数据库工单执行", Resource: "/api/v1/projects/:id/dbmgmt/tickets/:ticketId/execute", Action: "POST", Description: "Execute approved DB SQL ticket"},
		{Name: "数据库执行历史", Resource: "/api/v1/projects/:id/dbmgmt/executions", Action: "GET", Description: "List DB SQL executions"},
		{Name: "数据库审计日志", Resource: "/api/v1/projects/:id/dbmgmt/audit-logs", Action: "GET", Description: "List DB audit logs"},
	}
}

