package cmd

import "yunshu/internal/model"

func seedPermissionsAI() []model.Permission {
	return []model.Permission{
		{Name: "AI 状态查询", Resource: "/api/v1/ai/status", Action: "GET", Description: "Get AI status"},
		{Name: "AI 连通测试", Resource: "/api/v1/ai/ping", Action: "POST", Description: "Ping AI provider"},
		{Name: "AI 运维对话", Resource: "/api/v1/ai/chat", Action: "POST", Description: "AI ops assistant chat"},
		{Name: "AI 运维对话流式", Resource: "/api/v1/ai/chat/stream", Action: "POST", Description: "AI ops assistant chat SSE progress"},
		{Name: "AI 会话列表", Resource: "/api/v1/ai/sessions", Action: "GET", Description: "List AI chat sessions"},
		{Name: "AI 创建会话", Resource: "/api/v1/ai/sessions", Action: "POST", Description: "Create AI chat session"},
		{Name: "AI 会话详情", Resource: "/api/v1/ai/sessions/:id", Action: "GET", Description: "Get AI chat session"},
		{Name: "AI 更新会话", Resource: "/api/v1/ai/sessions/:id", Action: "PATCH", Description: "Update AI chat session"},
		{Name: "AI 删除会话", Resource: "/api/v1/ai/sessions/:id", Action: "DELETE", Description: "Delete AI chat session"},
		{Name: "AI 清空会话消息", Resource: "/api/v1/ai/sessions/:id/clear", Action: "POST", Description: "Clear AI chat session messages"},
		{Name: "AI 发起调查", Resource: "/api/v1/ai/investigations", Action: "POST", Description: "Start AI investigation"},
		{Name: "AI 调查列表", Resource: "/api/v1/ai/investigations", Action: "GET", Description: "List AI investigations"},
		{Name: "AI 调查详情", Resource: "/api/v1/ai/investigations/:id", Action: "GET", Description: "Get AI investigation"},
		{Name: "AI Pod 排障分析", Resource: "/api/v1/ai/k8s/pod-diagnose", Action: "POST", Description: "AI analyze pod diagnose"},
		{Name: "AI 生成 K8s YAML", Resource: "/api/v1/ai/k8s/generate-yaml", Action: "POST", Description: "AI generate Kubernetes YAML from description"},
		{Name: "AI CI 构建失败分析", Resource: "/api/v1/ai/cicd/build-fail", Action: "POST", Description: "AI analyze CI build failure"},
		{Name: "AI 告警解释", Resource: "/api/v1/ai/alert/explain", Action: "POST", Description: "AI explain alert fingerprint delivery"},
		{Name: "AI 日志分析", Resource: "/api/v1/ai/logs/analyze", Action: "POST", Description: "AI analyze project logs with RCA"},
		{Name: "AI 审批列表", Resource: "/api/v1/ai/approvals", Action: "GET", Description: "List AI tool approvals"},
		{Name: "AI 审批审核", Resource: "/api/v1/ai/approvals/:id/review", Action: "POST", Description: "Review AI tool approval"},
		{Name: "AI 审批执行", Resource: "/api/v1/ai/approvals/:id/execute", Action: "POST", Description: "Execute approved AI tool"},
		{Name: "AI 知识库同步", Resource: "/api/v1/ai/knowledge/sync", Action: "POST", Description: "Sync AI knowledge base to ES"},
		{Name: "AI 知识库向量化", Resource: "/api/v1/ai/knowledge/embed", Action: "POST", Description: "Sync AI knowledge chunk embeddings"},
		{Name: "AI 能力中心概览", Resource: "/api/v1/ai/center/overview", Action: "GET", Description: "AI capability center overview"},
		{Name: "AI 能力中心重载种子", Resource: "/api/v1/ai/center/reseed", Action: "POST", Description: "Reseed AI center from data/ai"},
		{Name: "AI Prompt 列表", Resource: "/api/v1/ai/center/prompts", Action: "GET", Description: "List AI prompts"},
		{Name: "AI Prompt 创建", Resource: "/api/v1/ai/center/prompts", Action: "POST", Description: "Create AI prompt"},
		{Name: "AI Prompt 详情", Resource: "/api/v1/ai/center/prompts/:id", Action: "GET", Description: "Get AI prompt"},
		{Name: "AI Prompt 更新", Resource: "/api/v1/ai/center/prompts/:id", Action: "PUT", Description: "Update AI prompt"},
		{Name: "AI Prompt 删除", Resource: "/api/v1/ai/center/prompts/:id", Action: "DELETE", Description: "Delete AI prompt"},
		{Name: "AI Prompt 版本", Resource: "/api/v1/ai/center/prompts/:id/versions", Action: "GET", Description: "List prompt versions"},
		{Name: "AI Prompt 发布", Resource: "/api/v1/ai/center/prompts/:id/publish", Action: "POST", Description: "Publish prompt version"},
		{Name: "AI Prompt 回滚", Resource: "/api/v1/ai/center/prompts/:id/versions/:vid/rollback", Action: "POST", Description: "Rollback prompt version"},
		{Name: "AI 模型列表", Resource: "/api/v1/ai/center/models", Action: "GET", Description: "List LLM models"},
		{Name: "AI 创建模型", Resource: "/api/v1/ai/center/models", Action: "POST", Description: "Create LLM model"},
		{Name: "AI 更新模型", Resource: "/api/v1/ai/center/models/:id", Action: "PUT", Description: "Update LLM model"},
		{Name: "AI 删除模型", Resource: "/api/v1/ai/center/models/:id", Action: "DELETE", Description: "Delete LLM model"},
		{Name: "AI 设默认模型", Resource: "/api/v1/ai/center/models/:id/default", Action: "POST", Description: "Set default LLM model"},
		{Name: "AI Tool 列表", Resource: "/api/v1/ai/center/tools", Action: "GET", Description: "List AI tools"},
		{Name: "AI Tool 创建", Resource: "/api/v1/ai/center/tools", Action: "POST", Description: "Create AI tool"},
		{Name: "AI Tool 详情", Resource: "/api/v1/ai/center/tools/:id", Action: "GET", Description: "Get AI tool"},
		{Name: "AI Tool 全量更新", Resource: "/api/v1/ai/center/tools/:id", Action: "PUT", Description: "Update AI tool"},
		{Name: "AI Tool 启停", Resource: "/api/v1/ai/center/tools/:id", Action: "PATCH", Description: "Enable/disable AI tool"},
		{Name: "AI Tool 删除", Resource: "/api/v1/ai/center/tools/:id", Action: "DELETE", Description: "Delete AI tool"},
		{Name: "AI 故障案例", Resource: "/api/v1/ai/center/cases", Action: "GET", Description: "List incident cases"},
		{Name: "AI 创建故障案例", Resource: "/api/v1/ai/center/cases", Action: "POST", Description: "Create incident case"},
		{Name: "AI 故障案例详情", Resource: "/api/v1/ai/center/cases/:id", Action: "GET", Description: "Get incident case"},
		{Name: "AI 更新故障案例", Resource: "/api/v1/ai/center/cases/:id", Action: "PUT", Description: "Update incident case"},
		{Name: "AI 删除故障案例", Resource: "/api/v1/ai/center/cases/:id", Action: "DELETE", Description: "Delete incident case"},
		{Name: "AI SOP 列表", Resource: "/api/v1/ai/center/sops", Action: "GET", Description: "List SOPs"},
		{Name: "AI SOP 创建", Resource: "/api/v1/ai/center/sops", Action: "POST", Description: "Create SOP"},
		{Name: "AI SOP 详情", Resource: "/api/v1/ai/center/sops/:id", Action: "GET", Description: "Get SOP"},
		{Name: "AI SOP 更新", Resource: "/api/v1/ai/center/sops/:id", Action: "PUT", Description: "Update SOP"},
		{Name: "AI SOP 删除", Resource: "/api/v1/ai/center/sops/:id", Action: "DELETE", Description: "Delete SOP"},
		{Name: "AI 知识库列表", Resource: "/api/v1/ai/center/knowledge-bases", Action: "GET", Description: "List knowledge bases"},
		{Name: "AI 创建知识库", Resource: "/api/v1/ai/center/knowledge-bases", Action: "POST", Description: "Create knowledge base"},
		{Name: "AI 更新知识库", Resource: "/api/v1/ai/center/knowledge-bases/:id", Action: "PUT", Description: "Update knowledge base"},
		{Name: "AI 删除知识库", Resource: "/api/v1/ai/center/knowledge-bases/:id", Action: "DELETE", Description: "Delete knowledge base"},
		{Name: "AI KB 文档列表", Resource: "/api/v1/ai/center/kb-documents", Action: "GET", Description: "List KB documents"},
		{Name: "AI KB 文档创建", Resource: "/api/v1/ai/center/kb-documents", Action: "POST", Description: "Create KB document"},
		{Name: "AI KB 文档详情", Resource: "/api/v1/ai/center/kb-documents/:id", Action: "GET", Description: "Get KB document"},
		{Name: "AI KB 文档更新", Resource: "/api/v1/ai/center/kb-documents/:id", Action: "PUT", Description: "Update KB document"},
		{Name: "AI KB 文档删除", Resource: "/api/v1/ai/center/kb-documents/:id", Action: "DELETE", Description: "Delete KB document"},
		{Name: "AI 评估用例", Resource: "/api/v1/ai/center/eval/cases", Action: "GET", Description: "List eval cases"},
		{Name: "AI 创建评估用例", Resource: "/api/v1/ai/center/eval/cases", Action: "POST", Description: "Create eval case"},
		{Name: "AI 评估用例详情", Resource: "/api/v1/ai/center/eval/cases/:id", Action: "GET", Description: "Get eval case"},
		{Name: "AI 更新评估用例", Resource: "/api/v1/ai/center/eval/cases/:id", Action: "PUT", Description: "Update eval case"},
		{Name: "AI 删除评估用例", Resource: "/api/v1/ai/center/eval/cases/:id", Action: "DELETE", Description: "Delete eval case"},
		{Name: "AI 评估运行", Resource: "/api/v1/ai/center/eval/run", Action: "POST", Description: "Run eval suite"},
	}
}

