package cmd

import "yunshu/internal/model"

func seedPermissionsCicd() []model.Permission {
	return []model.Permission{
		{Name: "发布后验证", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/verify", Action: "POST", Description: "Verify release run"},
		{Name: "集群日志 Pipeline 预览", Resource: "/api/v1/projects/:id/cluster-log/pipelines/preview", Action: "GET", Description: "Preview K8s cluster pipelines.yml"},
		{Name: "保存集群日志 Pipeline", Resource: "/api/v1/projects/:id/cluster-log/pipelines", Action: "PUT", Description: "Save or reset custom K8s cluster pipelines.yml"},
		{Name: "Loggie 配置下载", Resource: "/api/v1/projects/:id/loggie/pipeline/download", Action: "GET", Description: "Download loggie pipeline bundle"},
		{Name: "巡检PDF静态库", Resource: "/api/v1/inspect/pdf-libs/:name", Action: "GET", Description: "Serve html2canvas/jspdf for inspect HTML"},
		{Name: "CI/CD 应用服务列表", Resource: "/api/v1/projects/:id/cicd/services", Action: "GET", Description: "List CI/CD services"},
		{Name: "CI/CD 授权列表", Resource: "/api/v1/projects/:id/cicd-access-grants", Action: "GET", Description: "List CI/CD access grants"},
		{Name: "CI/CD 授权保存", Resource: "/api/v1/projects/:id/cicd-access-grants", Action: "POST", Description: "Upsert CI/CD access grant"},
		{Name: "CI/CD 授权批量", Resource: "/api/v1/projects/:id/cicd-access-grants/bulk", Action: "POST", Description: "Bulk upsert CI/CD access grants"},
		{Name: "CI/CD 授权迁移", Resource: "/api/v1/projects/:id/cicd-access-grants/bootstrap", Action: "POST", Description: "Bootstrap CI/CD grants for members"},
		{Name: "CI/CD 授权删除", Resource: "/api/v1/projects/:id/cicd-access-grants/:grantId", Action: "DELETE", Description: "Delete CI/CD access grant"},
		{Name: "CI/CD 创建应用服务", Resource: "/api/v1/projects/:id/cicd/services", Action: "POST", Description: "Create CI/CD service"},
		{Name: "CI/CD 应用服务详情", Resource: "/api/v1/projects/:id/cicd/services/:serviceId", Action: "GET", Description: "Get CI/CD service"},
		{Name: "CI/CD 更新应用服务", Resource: "/api/v1/projects/:id/cicd/services/:serviceId", Action: "PUT", Description: "Update CI/CD service"},
		{Name: "CI/CD 删除应用服务", Resource: "/api/v1/projects/:id/cicd/services/:serviceId", Action: "DELETE", Description: "Delete CI/CD service"},
		{Name: "CI/CD CI 配置查询", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/ci-config", Action: "GET", Description: "Get CI config"},
		{Name: "CI/CD CI 配置保存", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/ci-config", Action: "PUT", Description: "Upsert CI config"},
		{Name: "CI/CD 发布配置列表", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs", Action: "GET", Description: "List deploy configs"},
		{Name: "CI/CD 创建发布配置", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs", Action: "POST", Description: "Create deploy config"},
		{Name: "CI/CD 更新发布配置", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs/:configId", Action: "PUT", Description: "Update deploy config"},
		{Name: "CI/CD 删除发布配置", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/deploy-configs/:configId", Action: "DELETE", Description: "Delete deploy config"},
		{Name: "CI/CD MinIO 制品列表", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/artifacts", Action: "GET", Description: "List MinIO artifacts"},
		{Name: "CI/CD 下载 Helm 脚手架", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/helm-scaffold", Action: "GET", Description: "Download Helm chart scaffold zip"},
		{Name: "CI/CD 预览 Helm 脚手架", Resource: "/api/v1/projects/:id/cicd/helm-scaffold", Action: "GET", Description: "Preview download Helm chart scaffold zip"},
		{Name: "CI/CD 触发 CI 构建", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/builds", Action: "POST", Description: "Trigger CI build"},
		{Name: "CI/CD 触发 CD 发布", Resource: "/api/v1/projects/:id/cicd/services/:serviceId/releases", Action: "POST", Description: "Trigger CD release"},
		{Name: "CI/CD CI 打包记录列表", Resource: "/api/v1/projects/:id/cicd/build-runs", Action: "GET", Description: "List CI build runs"},
		{Name: "CI/CD CI 打包记录详情", Resource: "/api/v1/projects/:id/cicd/build-runs/:runId", Action: "GET", Description: "Get CI build run"},
		{Name: "CI/CD CI 构建日志", Resource: "/api/v1/projects/:id/cicd/build-runs/:runId/log", Action: "GET", Description: "Get CI build log"},
		{Name: "CI/CD 删除 CI 打包记录", Resource: "/api/v1/projects/:id/cicd/build-runs/:runId", Action: "DELETE", Description: "Delete CI build run"},
		{Name: "CI/CD 审批流查询", Resource: "/api/v1/projects/:id/cicd/approval-flow", Action: "GET", Description: "Get CD approval flow"},
		{Name: "CI/CD 审批流保存", Resource: "/api/v1/projects/:id/cicd/approval-flow", Action: "PUT", Description: "Upsert CD approval flow"},
		{Name: "CI/CD CD 工单列表", Resource: "/api/v1/projects/:id/cicd/release-runs", Action: "GET", Description: "List CD release runs"},
		{Name: "CI/CD CD 工单详情", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId", Action: "GET", Description: "Get CD release run detail"},
		{Name: "CI/CD 工单审批步骤", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/approval-steps", Action: "GET", Description: "List release approval steps"},
		{Name: "CI/CD 审批通过", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/approve", Action: "POST", Description: "Approve release run"},
		{Name: "CI/CD 审批驳回", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/reject", Action: "POST", Description: "Reject release run"},
		{Name: "CI/CD 执行发布", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/execute", Action: "POST", Description: "Execute release run"},
		{Name: "CI/CD 终止发布", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/terminate", Action: "POST", Description: "Terminate release run"},
		{Name: "CI/CD 批量审批通过", Resource: "/api/v1/projects/:id/cicd/release-runs/batch-approve", Action: "POST", Description: "Batch approve release runs"},
		{Name: "CI/CD 批量审批驳回", Resource: "/api/v1/projects/:id/cicd/release-runs/batch-reject", Action: "POST", Description: "Batch reject release runs"},
		{Name: "CI/CD 批量执行发布", Resource: "/api/v1/projects/:id/cicd/release-runs/batch-execute", Action: "POST", Description: "Batch execute release runs"},
		{Name: "CI/CD 批量终止发布", Resource: "/api/v1/projects/:id/cicd/release-runs/batch-terminate", Action: "POST", Description: "Batch terminate release runs"},
		{Name: "CI/CD CD 发布日志", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/log", Action: "GET", Description: "Get CD release log"},
		{Name: "CI/CD 删除 CD 工单", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId", Action: "DELETE", Description: "Delete CD release run"},
		{Name: "CI/CD 构建阶段", Resource: "/api/v1/projects/:id/cicd/build-runs/:runId/stages", Action: "GET", Description: "List CI build stages"},
		{Name: "CI/CD 构建制品元数据", Resource: "/api/v1/projects/:id/cicd/build-runs/:runId/artifacts-meta", Action: "GET", Description: "List CI build artifacts meta"},
		{Name: "CI/CD 平台回滚", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/platform-rollback", Action: "POST", Description: "Platform rollback release"},
		{Name: "CI/CD 渐进式晋级", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/progressive/promote", Action: "POST", Description: "Promote canary or blue-green release"},
		{Name: "CI/CD 渐进式中止", Resource: "/api/v1/projects/:id/cicd/release-runs/:runId/progressive/abort", Action: "POST", Description: "Abort canary or blue-green release"},
		{Name: "镜像仓库列表", Resource: "/api/v1/registries", Action: "GET", Description: "List container registries"},
		{Name: "镜像仓库创建", Resource: "/api/v1/registries", Action: "POST", Description: "Create container registry"},
		{Name: "镜像仓库详情", Resource: "/api/v1/registries/:registryId", Action: "GET", Description: "Get container registry"},
		{Name: "镜像仓库更新", Resource: "/api/v1/registries/:registryId", Action: "PUT", Description: "Update container registry"},
		{Name: "镜像仓库删除", Resource: "/api/v1/registries/:registryId", Action: "DELETE", Description: "Delete container registry"},
		{Name: "镜像仓库探测", Resource: "/api/v1/registries/:registryId/ping", Action: "POST", Description: "Ping container registry"},
		{Name: "Harbor 项目浏览", Resource: "/api/v1/registries/browse/projects", Action: "GET", Description: "Browse Harbor projects"},
		{Name: "Harbor 仓库浏览", Resource: "/api/v1/registries/browse/repositories", Action: "GET", Description: "Browse Harbor repositories"},
		{Name: "Harbor 制品浏览", Resource: "/api/v1/registries/browse/artifacts", Action: "GET", Description: "Browse Harbor artifacts"},
		{Name: "Harbor 制品删除", Resource: "/api/v1/registries/browse/artifacts/delete", Action: "POST", Description: "Delete Harbor artifact"},
		{Name: "镜像清理策略列表", Resource: "/api/v1/registries/cleanup-policies", Action: "GET", Description: "List registry cleanup policies"},
		{Name: "镜像清理策略创建", Resource: "/api/v1/registries/cleanup-policies", Action: "POST", Description: "Create registry cleanup policy"},
		{Name: "镜像清理策略更新", Resource: "/api/v1/registries/cleanup-policies/:policyId", Action: "PUT", Description: "Update registry cleanup policy"},
		{Name: "镜像清理策略删除", Resource: "/api/v1/registries/cleanup-policies/:policyId", Action: "DELETE", Description: "Delete registry cleanup policy"},
		{Name: "镜像清理策略执行", Resource: "/api/v1/registries/cleanup-policies/:policyId/run", Action: "POST", Description: "Run registry cleanup policy"},
		{Name: "流水线模板列表", Resource: "/api/v1/pipeline-templates", Action: "GET", Description: "List pipeline templates"},
		{Name: "流水线模板创建", Resource: "/api/v1/pipeline-templates", Action: "POST", Description: "Create pipeline template"},
		{Name: "流水线模板更新", Resource: "/api/v1/pipeline-templates/:templateId", Action: "PUT", Description: "Update pipeline template"},
	}
}

