package cmd

import "yunshu/internal/model"

func seedPermissionsProject() []model.Permission {
	return []model.Permission{
		{Name: "项目列表", Resource: "/api/v1/projects", Action: "GET", Description: "List projects"},
		{Name: "创建项目", Resource: "/api/v1/projects", Action: "POST", Description: "Create project"},
		{Name: "更新项目", Resource: "/api/v1/projects/:id", Action: "PUT", Description: "Update project"},
		{Name: "删除项目", Resource: "/api/v1/projects/:id", Action: "DELETE", Description: "Delete project"},
		{Name: "归档项目", Resource: "/api/v1/projects/:id/archive", Action: "POST", Description: "Archive project"},
		{Name: "恢复项目", Resource: "/api/v1/projects/:id/restore", Action: "POST", Description: "Restore archived project"},
		{Name: "项目成员列表", Resource: "/api/v1/projects/:id/members", Action: "GET", Description: "List project members"},
		{Name: "添加项目成员", Resource: "/api/v1/projects/:id/members", Action: "POST", Description: "Add project member"},
		{Name: "更新项目成员", Resource: "/api/v1/projects/:id/members/:memberId", Action: "PUT", Description: "Update project member"},
		{Name: "移除项目成员", Resource: "/api/v1/projects/:id/members/:memberId", Action: "DELETE", Description: "Remove project member"},
		{Name: "项目服务器列表", Resource: "/api/v1/projects/:id/servers", Action: "GET", Description: "List project servers"},
		{Name: "项目服务器保存", Resource: "/api/v1/projects/:id/servers", Action: "POST", Description: "Upsert project server"},
		{Name: "项目服务器详情", Resource: "/api/v1/projects/:id/servers/:serverId", Action: "GET", Description: "Project server detail"},
		{Name: "项目服务器有效权限", Resource: "/api/v1/projects/:id/servers/:serverId/my-access", Action: "GET", Description: "Current user effective server access"},
		{Name: "删除项目服务器", Resource: "/api/v1/projects/:id/servers/:serverId", Action: "DELETE", Description: "Delete project server"},
		{Name: "项目服务器命令", Resource: "/api/v1/projects/:id/servers/:serverId/exec", Action: "POST", Description: "Exec on project server"},
		{Name: "项目服务器文件列表", Resource: "/api/v1/projects/:id/servers/:serverId/files", Action: "GET", Description: "List remote files on server"},
		{Name: "项目服务器文件上传", Resource: "/api/v1/projects/:id/servers/:serverId/files/upload", Action: "POST", Description: "Upload file to server via SFTP"},
		{Name: "项目服务器文件下载", Resource: "/api/v1/projects/:id/servers/:serverId/files/download", Action: "GET", Description: "Download file from server via SFTP"},
		{Name: "项目服务器文件删除", Resource: "/api/v1/projects/:id/servers/:serverId/files/delete", Action: "POST", Description: "Delete remote file on server"},
		{Name: "项目服务器云操作", Resource: "/api/v1/projects/:id/servers/:serverId/cloud-actions", Action: "POST", Description: "Run cloud provider action on server"},
		{Name: "项目服务器分组树", Resource: "/api/v1/projects/:id/server-groups/tree", Action: "GET", Description: "List server groups tree"},
		{Name: "项目服务器分组创建", Resource: "/api/v1/projects/:id/server-groups", Action: "POST", Description: "Upsert server group"},
		{Name: "项目服务器分组更新", Resource: "/api/v1/projects/:id/server-groups/:groupId", Action: "PUT", Description: "Update server group"},
		{Name: "项目服务器分组删除", Resource: "/api/v1/projects/:id/server-groups/:groupId", Action: "DELETE", Description: "Delete server group"},
		{Name: "项目云账号列表", Resource: "/api/v1/projects/:id/cloud-accounts", Action: "GET", Description: "List cloud accounts"},
		{Name: "项目云账号保存", Resource: "/api/v1/projects/:id/cloud-accounts", Action: "POST", Description: "Upsert cloud account"},
		{Name: "项目云账号更新", Resource: "/api/v1/projects/:id/cloud-accounts/:accountId", Action: "PUT", Description: "Update cloud account"},
		{Name: "项目云账号同步", Resource: "/api/v1/projects/:id/cloud-accounts/:accountId/sync", Action: "PUT", Description: "Sync cloud account"},
		{Name: "项目云账号删除", Resource: "/api/v1/projects/:id/cloud-accounts/:accountId", Action: "DELETE", Description: "Delete cloud account"},
		{Name: "项目服务器导入", Resource: "/api/v1/projects/:id/servers/import", Action: "POST", Description: "Import servers"},
		{Name: "项目服务器导入模板", Resource: "/api/v1/projects/:id/servers/import-template", Action: "GET", Description: "Servers import template"},
		{Name: "项目服务器导出", Resource: "/api/v1/projects/:id/servers/export", Action: "GET", Description: "Export servers"},
		{Name: "项目服务器连通测试", Resource: "/api/v1/projects/:id/servers/test", Action: "POST", Description: "Test server connection"},
		{Name: "项目服务器批量测试", Resource: "/api/v1/projects/:id/servers/test/batch", Action: "POST", Description: "Batch test servers"},
		{Name: "项目服务器同步", Resource: "/api/v1/projects/:id/servers/sync", Action: "POST", Description: "Sync servers"},
		{Name: "服务器授权列表", Resource: "/api/v1/projects/:id/server-access-grants", Action: "GET", Description: "List server access grants"},
		{Name: "服务器授权保存", Resource: "/api/v1/projects/:id/server-access-grants", Action: "POST", Description: "Upsert server access grant"},
		{Name: "服务器授权批量", Resource: "/api/v1/projects/:id/server-access-grants/bulk", Action: "POST", Description: "Bulk upsert server access grants"},
		{Name: "服务器授权迁移", Resource: "/api/v1/projects/:id/server-access-grants/bootstrap", Action: "POST", Description: "Bootstrap server grants for members"},
		{Name: "服务器授权删除", Resource: "/api/v1/projects/:id/server-access-grants/:grantId", Action: "DELETE", Description: "Delete server access grant"},
		{Name: "项目服务列表", Resource: "/api/v1/projects/:id/services", Action: "GET", Description: "List project services"},
		{Name: "项目服务保存", Resource: "/api/v1/projects/:id/services", Action: "POST", Description: "Upsert project service"},
		{Name: "删除项目服务", Resource: "/api/v1/projects/:id/services/:serviceId", Action: "DELETE", Description: "Delete project service"},
		{Name: "服务目录列表", Resource: "/api/v1/projects/:id/service-catalog", Action: "GET", Description: "List service catalog"},
		{Name: "服务目录保存", Resource: "/api/v1/projects/:id/service-catalog", Action: "POST", Description: "Upsert service catalog"},
		{Name: "服务目录详情", Resource: "/api/v1/projects/:id/service-catalog/:catalogId", Action: "GET", Description: "Get service catalog"},
		{Name: "服务画像", Resource: "/api/v1/projects/:id/service-catalog/:catalogId/portrait", Action: "GET", Description: "Service portrait aggregate"},
		{Name: "服务目录删除", Resource: "/api/v1/projects/:id/service-catalog/:catalogId", Action: "DELETE", Description: "Delete service catalog"},
		{Name: "服务目录绑定", Resource: "/api/v1/projects/:id/service-catalog/:catalogId/links", Action: "POST", Description: "Bind service catalog link"},
		{Name: "服务目录解绑", Resource: "/api/v1/projects/:id/service-catalog/:catalogId/links/:linkId", Action: "DELETE", Description: "Unbind service catalog link"},
		{Name: "项目日志源列表", Resource: "/api/v1/projects/:id/log-sources", Action: "GET", Description: "List log sources"},
		{Name: "项目日志源保存", Resource: "/api/v1/projects/:id/log-sources", Action: "POST", Description: "Upsert log source"},
		{Name: "删除项目日志源", Resource: "/api/v1/projects/:id/log-sources/:logSourceId", Action: "DELETE", Description: "Delete log source"},
		{Name: "项目日志检索", Resource: "/api/v1/projects/:id/logs/search", Action: "GET", Description: "Search project logs from Elasticsearch"},
		{Name: "项目日志概览", Resource: "/api/v1/projects/:id/logs/overview", Action: "GET", Description: "Log overview with histogram and signatures"},
		{Name: "项目日志模板", Resource: "/api/v1/projects/:id/logs/patterns", Action: "GET", Description: "List log pattern clusters"},
		{Name: "项目日志异常", Resource: "/api/v1/projects/:id/logs/anomalies", Action: "GET", Description: "List log anomalies"},
		{Name: "项目日志上下文", Resource: "/api/v1/projects/:id/logs/context", Action: "GET", Description: "Correlated log context with changes and alerts"},
		{Name: "项目日志导出", Resource: "/api/v1/projects/:id/logs/export", Action: "GET", Description: "Export project logs from Elasticsearch"},
		{Name: "项目日志保留查询", Resource: "/api/v1/projects/:id/log-retention", Action: "GET", Description: "Get project log retention policy"},
		{Name: "项目日志保留保存", Resource: "/api/v1/projects/:id/log-retention", Action: "PUT", Description: "Upsert project log retention policy"},
		{Name: "项目日志保留删除", Resource: "/api/v1/projects/:id/log-retention", Action: "DELETE", Description: "Delete project log retention override"},
		{Name: "Loggie 引导", Resource: "/api/v1/projects/:id/loggie/bootstrap", Action: "POST", Description: "Bootstrap loggie agent token"},
		{Name: "Loggie 状态列表", Resource: "/api/v1/projects/:id/loggie/status", Action: "GET", Description: "List loggie status by server"},
		{Name: "Loggie 引导日志源预览", Resource: "/api/v1/projects/:id/loggie/bootstrap-sources", Action: "GET", Description: "Preview log sources for loggie bootstrap"},
		{Name: "Loggie 配置下发", Resource: "/api/v1/projects/:id/loggie/deploy", Action: "POST", Description: "Deploy loggie pipeline over SSH"},
		{Name: "Loggie 安装", Resource: "/api/v1/projects/:id/loggie/install", Action: "POST", Description: "Install loggie agent over SSH"},
		{Name: "Loggie 卸载", Resource: "/api/v1/projects/:id/loggie/uninstall", Action: "POST", Description: "Uninstall loggie agent and clear registration"},
		{Name: "Loggie 启动", Resource: "/api/v1/projects/:id/loggie/start", Action: "POST", Description: "Start loggie service over SSH"},
		{Name: "Loggie 停止", Resource: "/api/v1/projects/:id/loggie/stop", Action: "POST", Description: "Stop loggie service over SSH"},
		{Name: "Loggie 重启", Resource: "/api/v1/projects/:id/loggie/restart", Action: "POST", Description: "Restart loggie service over SSH"},
		{Name: "Loggie 同步下发", Resource: "/api/v1/projects/:id/loggie/sync", Action: "POST", Description: "Sync pipelines from log sources and deploy"},
		{Name: "集群日志规则列表", Resource: "/api/v1/projects/:id/cluster-log/rules", Action: "GET", Description: "List K8s cluster log rules"},
		{Name: "创建集群日志规则", Resource: "/api/v1/projects/:id/cluster-log/rules", Action: "POST", Description: "Create K8s cluster log rule"},
		{Name: "更新集群日志规则", Resource: "/api/v1/projects/:id/cluster-log/rules/:rule_id", Action: "PUT", Description: "Update K8s cluster log rule"},
		{Name: "删除集群日志规则", Resource: "/api/v1/projects/:id/cluster-log/rules/:rule_id", Action: "DELETE", Description: "Delete K8s cluster log rule"},
		{Name: "集群日志 Agent 列表", Resource: "/api/v1/projects/:id/cluster-log/agents", Action: "GET", Description: "List K8s cluster log agents"},
		{Name: "部署集群日志采集", Resource: "/api/v1/projects/:id/cluster-log/deploy", Action: "POST", Description: "Deploy or sync Loggie DaemonSet"},
		{Name: "集群日志采集状态", Resource: "/api/v1/projects/:id/cluster-log/status", Action: "GET", Description: "Refresh K8s cluster log DaemonSet status"},
		{Name: "项目服务器终端 WS", Resource: "/api/v1/projects/:id/servers/:serverId/terminal/ws", Action: "GET", Description: "Server terminal websocket"},
		{Name: "项目仓库绑定查询", Resource: "/api/v1/projects/:id/registry-binding", Action: "GET", Description: "Get project registry binding"},
		{Name: "项目仓库绑定保存", Resource: "/api/v1/projects/:id/registry-binding", Action: "PUT", Description: "Upsert project registry binding"},
		{Name: "项目仓库绑定删除", Resource: "/api/v1/projects/:id/registry-binding", Action: "DELETE", Description: "Delete project registry binding"},
	}
}

