package cmd

import "yunshu/internal/model"

func seedPermissionsAlert() []model.Permission {
	return []model.Permission{
		{Name: "告警通道列表", Resource: "/api/v1/alerts/channels", Action: "GET", Description: "List alert channels"},
		{Name: "创建告警通道", Resource: "/api/v1/alerts/channels", Action: "POST", Description: "Create alert channel"},
		{Name: "更新告警通道", Resource: "/api/v1/alerts/channels/:id", Action: "PUT", Description: "Update alert channel"},
		{Name: "删除告警通道", Resource: "/api/v1/alerts/channels/:id", Action: "DELETE", Description: "Delete alert channel"},
		{Name: "测试告警通道", Resource: "/api/v1/alerts/channels/:id/test", Action: "POST", Description: "Send test alert to channel"},
		{Name: "预览告警通道模板", Resource: "/api/v1/alerts/channels/preview-template", Action: "POST", Description: "Preview alert channel template"},
		{Name: "告警路由调试", Resource: "/api/v1/alerts/routing/debug", Action: "POST", Description: "Debug alert routing"},
		{Name: "告警事件列表", Resource: "/api/v1/alerts/events", Action: "GET", Description: "List alert events"},
		{Name: "告警事件分组列表", Resource: "/api/v1/alerts/events/grouped", Action: "GET", Description: "List alert events grouped"},
		{Name: "告警指纹投递追溯", Resource: "/api/v1/alerts/events/by-fingerprint", Action: "GET", Description: "Explain alert delivery by fingerprint"},
		{Name: "告警证据包", Resource: "/api/v1/alerts/events/evidence", Action: "GET", Description: "Collect alert evidence pack (logs/changes/pod hint)"},
		{Name: "告警历史统计", Resource: "/api/v1/alerts/history/stats", Action: "GET", Description: "Alert history stats"},
		{Name: "认领告警", Resource: "/api/v1/alerts/acks", Action: "POST", Description: "Acknowledge alert"},
		{Name: "取消认领告警", Resource: "/api/v1/alerts/acks", Action: "DELETE", Description: "Clear alert ack"},
		{Name: "查询告警认领", Resource: "/api/v1/alerts/acks", Action: "GET", Description: "Get active alert ack"},
		{Name: "告警进展列表", Resource: "/api/v1/alerts/notes", Action: "GET", Description: "List alert progress notes"},
		{Name: "添加告警进展", Resource: "/api/v1/alerts/notes", Action: "POST", Description: "Create alert progress note"},
		{Name: "告警数据源列表", Resource: "/api/v1/alerts/datasources", Action: "GET", Description: "List alert datasources"},
		{Name: "告警数据源连通性检测", Resource: "/api/v1/alerts/datasources/:id/ping", Action: "GET", Description: "Ping Prometheus datasource"},
		{Name: "创建告警数据源", Resource: "/api/v1/alerts/datasources", Action: "POST", Description: "Create alert datasource"},
		{Name: "更新告警数据源", Resource: "/api/v1/alerts/datasources/:id", Action: "PUT", Description: "Update alert datasource"},
		{Name: "删除告警数据源", Resource: "/api/v1/alerts/datasources/:id", Action: "DELETE", Description: "Delete alert datasource"},
		{Name: "Prometheus 活跃告警快照", Resource: "/api/v1/alerts/datasources/:id/prometheus-alerts", Action: "GET", Description: "GET /api/v1/alerts proxy"},
		{Name: "Alertmanager 静默列表", Resource: "/api/v1/alerts/datasources/:id/alertmanager-silences", Action: "GET", Description: "GET /api/v2/silences proxy"},
		{Name: "PromQL 即时查询", Resource: "/api/v1/alerts/datasources/:id/query", Action: "POST", Description: "Prometheus instant query"},
		{Name: "PromQL 范围查询", Resource: "/api/v1/alerts/datasources/:id/query_range", Action: "POST", Description: "Prometheus range query"},
		{Name: "告警静默列表", Resource: "/api/v1/alerts/silences", Action: "GET", Description: "List alert silences"},
		{Name: "创建告警静默", Resource: "/api/v1/alerts/silences", Action: "POST", Description: "Create alert silence"},
		{Name: "批量创建告警静默", Resource: "/api/v1/alerts/silences/batch", Action: "POST", Description: "Batch create alert silences"},
		{Name: "更新告警静默", Resource: "/api/v1/alerts/silences/:id", Action: "PUT", Description: "Update alert silence"},
		{Name: "删除告警静默", Resource: "/api/v1/alerts/silences/:id", Action: "DELETE", Description: "Delete alert silence"},
		{Name: "维护窗口列表", Resource: "/api/v1/alerts/maintenance-windows", Action: "GET", Description: "List alert maintenance windows"},
		{Name: "创建维护窗口", Resource: "/api/v1/alerts/maintenance-windows", Action: "POST", Description: "Create alert maintenance window"},
		{Name: "更新维护窗口", Resource: "/api/v1/alerts/maintenance-windows/:id", Action: "PUT", Description: "Update alert maintenance window"},
		{Name: "删除维护窗口", Resource: "/api/v1/alerts/maintenance-windows/:id", Action: "DELETE", Description: "Delete alert maintenance window"},
		{Name: "告警抑制规则列表", Resource: "/api/v1/alerts/inhibition-rules", Action: "GET", Description: "List alert inhibition rules"},
		{Name: "创建告警抑制规则", Resource: "/api/v1/alerts/inhibition-rules", Action: "POST", Description: "Create alert inhibition rule"},
		{Name: "更新告警抑制规则", Resource: "/api/v1/alerts/inhibition-rules/:id", Action: "PUT", Description: "Update alert inhibition rule"},
		{Name: "删除告警抑制规则", Resource: "/api/v1/alerts/inhibition-rules/:id", Action: "DELETE", Description: "Delete alert inhibition rule"},
		{Name: "刷新告警抑制缓存", Resource: "/api/v1/alerts/inhibition-rules/refresh-cache", Action: "POST", Description: "Refresh inhibition rule cache"},
		{Name: "监控告警规则列表", Resource: "/api/v1/alerts/monitor-rules", Action: "GET", Description: "List monitor alert rules"},
		{Name: "创建监控告警规则", Resource: "/api/v1/alerts/monitor-rules", Action: "POST", Description: "Create monitor alert rule"},
		{Name: "告警规则模板列表", Resource: "/api/v1/alerts/rule-templates", Action: "GET", Description: "List alert rule templates"},
		{Name: "从模板创建监控规则", Resource: "/api/v1/alerts/monitor-rules/from-template", Action: "POST", Description: "Create monitor rule from template"},
		{Name: "更新监控告警规则", Resource: "/api/v1/alerts/monitor-rules/:id", Action: "PUT", Description: "Update monitor alert rule"},
		{Name: "删除监控告警规则", Resource: "/api/v1/alerts/monitor-rules/:id", Action: "DELETE", Description: "Delete monitor alert rule"},
		{Name: "监控规则处理人", Resource: "/api/v1/alerts/monitor-rules/:id/assignees", Action: "GET", Description: "List rule assignees"},
		{Name: "配置监控规则处理人", Resource: "/api/v1/alerts/monitor-rules/:id/assignees", Action: "PUT", Description: "Upsert rule assignees"},
		{Name: "监控规则变更待审列表", Resource: "/api/v1/alerts/monitor-rule-changes", Action: "GET", Description: "List pending monitor rule change requests"},
		{Name: "提交监控规则变更审批", Resource: "/api/v1/alerts/monitor-rule-changes", Action: "POST", Description: "Propose monitor rule change"},
		{Name: "批准监控规则变更", Resource: "/api/v1/alerts/monitor-rule-changes/:id/approve", Action: "POST", Description: "Approve monitor rule change"},
		{Name: "驳回监控规则变更", Resource: "/api/v1/alerts/monitor-rule-changes/:id/reject", Action: "POST", Description: "Reject monitor rule change"},
		{Name: "PromQL 收藏列表", Resource: "/api/v1/alerts/promql-saved-queries", Action: "GET", Description: "List promql saved queries"},
		{Name: "创建 PromQL 收藏", Resource: "/api/v1/alerts/promql-saved-queries", Action: "POST", Description: "Create promql saved query"},
		{Name: "删除 PromQL 收藏", Resource: "/api/v1/alerts/promql-saved-queries/:id", Action: "DELETE", Description: "Delete promql saved query"},
		{Name: "导出历史告警 CSV", Resource: "/api/v1/alerts/his-events/export.csv", Action: "GET", Description: "Export alert history events as CSV"},
		{Name: "值班班次列表", Resource: "/api/v1/alerts/duty-blocks", Action: "GET", Description: "List alert duty blocks"},
		{Name: "创建值班班次", Resource: "/api/v1/alerts/duty-blocks", Action: "POST", Description: "Create alert duty block"},
		{Name: "更新值班班次", Resource: "/api/v1/alerts/duty-blocks/:id", Action: "PUT", Description: "Update alert duty block"},
		{Name: "删除值班班次", Resource: "/api/v1/alerts/duty-blocks/:id", Action: "DELETE", Description: "Delete alert duty block"},
		{Name: "值班日历", Resource: "/api/v1/alerts/duty-blocks/calendar", Action: "GET", Description: "List duty calendar"},
		{Name: "校验值班班次", Resource: "/api/v1/alerts/duty-blocks/validate", Action: "POST", Description: "Validate duty blocks"},
		{Name: "值班交接", Resource: "/api/v1/alerts/duty-blocks/:id/handoff", Action: "POST", Description: "Handoff duty block"},
		{Name: "告警订阅节点列表", Resource: "/api/v1/alerts/subscriptions", Action: "GET", Description: "List alert subscription nodes"},
		{Name: "告警订阅树", Resource: "/api/v1/alerts/subscriptions/tree", Action: "GET", Description: "Get alert subscription tree"},
		{Name: "创建告警订阅节点", Resource: "/api/v1/alerts/subscriptions", Action: "POST", Description: "Create alert subscription node"},
		{Name: "更新告警订阅节点", Resource: "/api/v1/alerts/subscriptions/:id", Action: "PUT", Description: "Update alert subscription node"},
		{Name: "删除告警订阅节点", Resource: "/api/v1/alerts/subscriptions/:id", Action: "DELETE", Description: "Delete alert subscription node"},
		{Name: "移动告警订阅节点", Resource: "/api/v1/alerts/subscriptions/:id/move", Action: "POST", Description: "Move alert subscription node"},
		{Name: "从策略迁移订阅", Resource: "/api/v1/alerts/subscriptions/migrate-from-policies", Action: "POST", Description: "Migrate subscriptions from policies"},
		{Name: "克隆项目路由", Resource: "/api/v1/alerts/subscriptions/clone-from-project", Action: "POST", Description: "Clone project routing subscriptions"},
		{Name: "告警路由向导", Resource: "/api/v1/alerts/subscriptions/wizard", Action: "POST", Description: "Create routing node via wizard"},
		{Name: "接收组列表", Resource: "/api/v1/alerts/receiver-groups", Action: "GET", Description: "List alert receiver groups"},
		{Name: "创建接收组", Resource: "/api/v1/alerts/receiver-groups", Action: "POST", Description: "Create alert receiver group"},
		{Name: "更新接收组", Resource: "/api/v1/alerts/receiver-groups/:id", Action: "PUT", Description: "Update alert receiver group"},
		{Name: "删除接收组", Resource: "/api/v1/alerts/receiver-groups/:id", Action: "DELETE", Description: "Delete alert receiver group"},
		{Name: "云到期规则列表", Resource: "/api/v1/alerts/cloud-expiry-rules", Action: "GET", Description: "List cloud expiry rules"},
		{Name: "创建云到期规则", Resource: "/api/v1/alerts/cloud-expiry-rules", Action: "POST", Description: "Create cloud expiry rule"},
		{Name: "更新云到期规则", Resource: "/api/v1/alerts/cloud-expiry-rules/:id", Action: "PUT", Description: "Update cloud expiry rule"},
		{Name: "删除云到期规则", Resource: "/api/v1/alerts/cloud-expiry-rules/:id", Action: "DELETE", Description: "Delete cloud expiry rule"},
		{Name: "立即评估云到期", Resource: "/api/v1/alerts/cloud-expiry-rules/evaluate-now", Action: "POST", Description: "Evaluate cloud expiry rules now"},
		{Name: "告警质量报告", Resource: "/api/v1/alerts/quality-report", Action: "GET", Description: "Alert quality report"},
	}
}

