package cmd

import "yunshu/internal/model"

func seedPermissionsK8s() []model.Permission {
	return []model.Permission{
		{Name: "K8s 动作码目录", Resource: "/api/v1/k8s-policies/actions", Action: "GET", Description: "List k8s scope action codes (reference)"},
		{Name: "K8s 能力包目录", Resource: "/api/v1/k8s-policies/capabilities", Action: "GET", Description: "List k8s cluster capability catalog"},
		{Name: "K8s API 路径目录", Resource: "/api/v1/k8s-policies/paths", Action: "GET", Description: "List k8s scope API paths (reference)"},
		{Name: "K8s 集群档位列表", Resource: "/api/v1/k8s-policies", Action: "GET", Description: "List k8s cluster access grants by role"},
		{Name: "K8s 集群档位预设下发", Resource: "/api/v1/k8s-policies/grant-preset", Action: "POST", Description: "Upsert k8s cluster access preset or capabilities per role/cluster"},
		{Name: "K8s 集群档位删除", Resource: "/api/v1/k8s-policies/cluster-grants/:id", Action: "DELETE", Description: "Delete one k8s cluster access grant"},
		{Name: "K8s 集群已授权矩阵", Resource: "/api/v1/k8s-policies/cluster-auth-matrix", Action: "GET", Description: "List cluster auth matrix expanded by user"},
		{Name: "K8s 用户已授权集群", Resource: "/api/v1/k8s-policies/user-cluster-auth", Action: "GET", Description: "List clusters authorized for a user"},
		{Name: "K8s 我的集群档位", Resource: "/api/v1/k8s-policies/my-access", Action: "GET", Description: "Get current user effective k8s access tier for a cluster"},
		{Name: "K8s 集群档位批量删除", Resource: "/api/v1/k8s-policies/cluster-grants/batch-delete", Action: "POST", Description: "Batch delete k8s cluster access grants"},
		{Name: "K8s 按 NS 拆分档位", Resource: "/api/v1/k8s-policies/split-by-namespaces", Action: "POST", Description: "Split k8s scoped policy presets by namespace"},
		{Name: "K8s 命名空间黑名单列表", Resource: "/api/v1/k8s-namespace-deny-rules", Action: "GET", Description: "List k8s namespace deny rules"},
		{Name: "K8s 命名空间黑名单新增", Resource: "/api/v1/k8s-namespace-deny-rules", Action: "POST", Description: "Create k8s namespace deny rule"},
		{Name: "K8s 命名空间黑名单删除", Resource: "/api/v1/k8s-namespace-deny-rules/:id", Action: "DELETE", Description: "Delete k8s namespace deny rule"},
		{Name: "K8s 命名空间白名单列表", Resource: "/api/v1/k8s-namespace-allow-rules", Action: "GET", Description: "List k8s namespace allow rules"},
		{Name: "K8s 命名空间白名单新增", Resource: "/api/v1/k8s-namespace-allow-rules", Action: "POST", Description: "Create k8s namespace allow rule"},
		{Name: "K8s 命名空间白名单删除", Resource: "/api/v1/k8s-namespace-allow-rules/:id", Action: "DELETE", Description: "Delete k8s namespace allow rule"},
		{Name: "集群列表", Resource: "/api/v1/clusters", Action: "GET", Description: "View k8s clusters"},
		{Name: "集群详情", Resource: "/api/v1/clusters/:id", Action: "GET", Description: "View k8s cluster detail"},
		{Name: "创建集群", Resource: "/api/v1/clusters", Action: "POST", Description: "Create k8s cluster"},
		{Name: "更新集群", Resource: "/api/v1/clusters/:id", Action: "PUT", Description: "Update k8s cluster"},
		{Name: "删除集群", Resource: "/api/v1/clusters/:id", Action: "DELETE", Description: "Delete k8s cluster"},
		{Name: "启停集群", Resource: "/api/v1/clusters/:id/status", Action: "PUT", Description: "Enable/disable k8s cluster"},
		{Name: "集群连接状态", Resource: "/api/v1/clusters/:id/status", Action: "GET", Description: "Check k8s cluster status"},
		{Name: "集群命名空间", Resource: "/api/v1/clusters/:id/namespaces", Action: "GET", Description: "List cluster namespaces"},
		{Name: "组件状态列表", Resource: "/api/v1/clusters/:id/component-statuses", Action: "GET", Description: "List control plane component statuses"},
		{Name: "集群 API 资源发现", Resource: "/api/v1/clusters/:id/api-resources", Action: "GET", Description: "Discovery API resources like kubectl api-resources"},
		{Name: "K8s 资源 Watch（SSE）", Resource: "/api/v1/k8s/resource-watch/stream", Action: "GET", Description: "Kubernetes watch streamed as Server-Sent Events"},
		{Name: "K8s 全局搜索", Resource: "/api/v1/k8s/search", Action: "GET", Description: "Search k8s resources"},
		{Name: "K8s 资源拓扑", Resource: "/api/v1/k8s/topology", Action: "GET", Description: "Get k8s resource topology graph"},
		{Name: "K8s Event 转发规则列表", Resource: "/api/v1/k8s/event-forward/rules", Action: "GET", Description: "List k8s event forward rules"},
		{Name: "K8s Event 转发规则详情", Resource: "/api/v1/k8s/event-forward/rules/:id", Action: "GET", Description: "Get k8s event forward rule"},
		{Name: "K8s Event 转发规则创建", Resource: "/api/v1/k8s/event-forward/rules", Action: "POST", Description: "Create k8s event forward rule"},
		{Name: "K8s Event 转发规则更新", Resource: "/api/v1/k8s/event-forward/rules/:id", Action: "PUT", Description: "Update k8s event forward rule"},
		{Name: "K8s Event 转发规则删除", Resource: "/api/v1/k8s/event-forward/rules/:id", Action: "DELETE", Description: "Delete k8s event forward rule"},
		{Name: "K8s Event 转发 Worker 参数", Resource: "/api/v1/k8s/event-forward/settings", Action: "GET", Description: "Get k8s event forward worker settings"},
		{Name: "K8s Event 转发 Worker 更新", Resource: "/api/v1/k8s/event-forward/settings", Action: "PUT", Description: "Update k8s event forward worker settings"},
		{Name: "K8s Event 转发投递记录", Resource: "/api/v1/k8s/event-forward/events", Action: "GET", Description: "List forwarded k8s events including dead letters"},
		{Name: "K8s Event 转发死信重投", Resource: "/api/v1/k8s/event-forward/events/:id/requeue", Action: "POST", Description: "Requeue dead-letter forwarded event"},
		{Name: "Pod 列表", Resource: "/api/v1/pods", Action: "GET", Description: "List pods"},
		{Name: "Pod 详情", Resource: "/api/v1/pods/detail", Action: "GET", Description: "Get pod detail"},
		{Name: "Pod 诊断", Resource: "/api/v1/pods/diagnose", Action: "GET", Description: "Diagnose pod issues"},
		{Name: "Pod 事件", Resource: "/api/v1/pods/events", Action: "GET", Description: "List pod events"},
		{Name: "Pod 日志", Resource: "/api/v1/pods/logs", Action: "GET", Description: "Get pod logs"},
		{Name: "Pod 日志下载", Resource: "/api/v1/pods/logs/download", Action: "GET", Description: "Download pod logs"},
		{Name: "Pod 日志流", Resource: "/api/v1/pods/logs/stream", Action: "GET", Description: "Stream pod logs"},
		{Name: "Pod 文件列表", Resource: "/api/v1/pods/files", Action: "GET", Description: "List pod files"},
		{Name: "Pod 文件读取", Resource: "/api/v1/pods/file", Action: "GET", Description: "Read pod file content"},
		{Name: "Pod 文件下载", Resource: "/api/v1/pods/file/download", Action: "GET", Description: "Download pod file"},
		{Name: "Pod 文件上传", Resource: "/api/v1/pods/file/upload", Action: "POST", Description: "Upload file to pod"},
		{Name: "Pod 文件删除", Resource: "/api/v1/pods/file/delete", Action: "POST", Description: "Delete pod file"},
		{Name: "Pod Exec", Resource: "/api/v1/pods/exec", Action: "POST", Description: "Exec command in pod"},
		{Name: "Pod 临时调试容器", Resource: "/api/v1/pods/debug", Action: "POST", Description: "Inject ephemeral debug container"},
		{Name: "Pod 交互式终端", Resource: "/api/v1/pods/exec/ws", Action: "GET", Description: "Interactive exec terminal via websocket"},
		{Name: "Pod 重启", Resource: "/api/v1/pods/restart", Action: "POST", Description: "Restart pod"},
		{Name: "Pod YAML 创建", Resource: "/api/v1/pods/create/yaml", Action: "POST", Description: "Create pod by yaml"},
		{Name: "Pod 快捷创建", Resource: "/api/v1/pods/create/simple", Action: "POST", Description: "Create pod quickly"},
		{Name: "编辑并重建 Pod", Resource: "/api/v1/pods/update/simple", Action: "POST", Description: "Update pod by recreate"},
		{Name: "删除 Pod", Resource: "/api/v1/pods", Action: "DELETE", Description: "Delete pod"},
		{Name: "命名空间列表", Resource: "/api/v1/namespaces", Action: "GET", Description: "List namespaces"},
		{Name: "命名空间详情", Resource: "/api/v1/namespaces/detail", Action: "GET", Description: "Get namespace detail"},
		{Name: "命名空间应用 YAML", Resource: "/api/v1/namespaces/apply", Action: "POST", Description: "Apply namespace yaml"},
		{Name: "删除命名空间", Resource: "/api/v1/namespaces", Action: "DELETE", Description: "Delete namespace"},
		{Name: "Node 列表", Resource: "/api/v1/nodes", Action: "GET", Description: "List nodes"},
		{Name: "Node 详情", Resource: "/api/v1/nodes/detail", Action: "GET", Description: "Get node detail"},
		{Name: "Node 调度状态", Resource: "/api/v1/nodes/schedulability", Action: "POST", Description: "Cordon or uncordon node"},
		{Name: "Node 污点", Resource: "/api/v1/nodes/taints", Action: "PUT", Description: "Replace node taints"},
		{Name: "Node Drain", Resource: "/api/v1/nodes/drain", Action: "POST", Description: "Drain node workloads"},
		{Name: "Node Drain 进度", Resource: "/api/v1/nodes/drain-status", Action: "GET", Description: "Get node drain status"},
		{Name: "RBAC Role 列表", Resource: "/api/v1/rbac/roles", Action: "GET", Description: "List Roles"},
		{Name: "RBAC RoleBinding 列表", Resource: "/api/v1/rbac/rolebindings", Action: "GET", Description: "List RoleBindings"},
		{Name: "RBAC ClusterRole 列表", Resource: "/api/v1/rbac/clusterroles", Action: "GET", Description: "List ClusterRoles"},
		{Name: "RBAC ClusterRoleBinding 列表", Resource: "/api/v1/rbac/clusterrolebindings", Action: "GET", Description: "List ClusterRoleBindings"},
		{Name: "RBAC 详情", Resource: "/api/v1/rbac/detail", Action: "GET", Description: "Get RBAC detail"},
		{Name: "RBAC 应用 YAML", Resource: "/api/v1/rbac/apply", Action: "POST", Description: "Apply RBAC yaml"},
		{Name: "RBAC 删除", Resource: "/api/v1/rbac", Action: "DELETE", Description: "Delete RBAC resource"},
		{Name: "ServiceAccount 列表", Resource: "/api/v1/serviceaccounts", Action: "GET", Description: "List serviceaccounts"},
		{Name: "ServiceAccount 详情", Resource: "/api/v1/serviceaccounts/detail", Action: "GET", Description: "Get serviceaccount detail"},
		{Name: "ServiceAccount 应用 YAML", Resource: "/api/v1/serviceaccounts/apply", Action: "POST", Description: "Apply serviceaccount yaml"},
		{Name: "ServiceAccount 删除", Resource: "/api/v1/serviceaccounts", Action: "DELETE", Description: "Delete serviceaccount"},
		{Name: "Deployment 列表", Resource: "/api/v1/deployments", Action: "GET", Description: "List deployments"},
		{Name: "Deployment 详情", Resource: "/api/v1/deployments/detail", Action: "GET", Description: "Get deployment detail"},
		{Name: "Deployment 应用 YAML", Resource: "/api/v1/deployments/apply", Action: "POST", Description: "Apply deployment yaml"},
		{Name: "Deployment 扩缩容", Resource: "/api/v1/deployments/scale", Action: "POST", Description: "Scale deployment"},
		{Name: "Deployment 垂直扩缩", Resource: "/api/v1/deployments/container-resources", Action: "POST", Description: "Patch deployment container resources"},
		{Name: "Deployment 重启", Resource: "/api/v1/deployments/restart", Action: "POST", Description: "Restart deployment"},
		{Name: "Deployment 回滚", Resource: "/api/v1/deployments/rollout-undo", Action: "POST", Description: "Undo deployment rollout"},
		{Name: "Deployment 历史版本", Resource: "/api/v1/deployments/revisions", Action: "GET", Description: "List deployment rollout revisions"},
		{Name: "Deployment 关联 Pods", Resource: "/api/v1/deployments/pods", Action: "GET", Description: "List deployment related pods"},
		{Name: "Deployment 发布状态", Resource: "/api/v1/deployments/rollout-status", Action: "GET", Description: "Get deployment rollout status"},
		{Name: "删除 Deployment", Resource: "/api/v1/deployments", Action: "DELETE", Description: "Delete deployment"},
		{Name: "StatefulSet 列表", Resource: "/api/v1/statefulsets", Action: "GET", Description: "List statefulsets"},
		{Name: "StatefulSet 详情", Resource: "/api/v1/statefulsets/detail", Action: "GET", Description: "Get statefulset detail"},
		{Name: "StatefulSet 应用 YAML", Resource: "/api/v1/statefulsets/apply", Action: "POST", Description: "Apply statefulset yaml"},
		{Name: "StatefulSet 扩缩容", Resource: "/api/v1/statefulsets/scale", Action: "POST", Description: "Scale statefulset"},
		{Name: "StatefulSet 垂直扩缩", Resource: "/api/v1/statefulsets/container-resources", Action: "POST", Description: "Patch statefulset container resources"},
		{Name: "StatefulSet 重启", Resource: "/api/v1/statefulsets/restart", Action: "POST", Description: "Restart statefulset"},
		{Name: "StatefulSet 历史版本", Resource: "/api/v1/statefulsets/revisions", Action: "GET", Description: "List statefulset controller revisions"},
		{Name: "StatefulSet 回滚", Resource: "/api/v1/statefulsets/rollout-undo", Action: "POST", Description: "Undo statefulset rollout"},
		{Name: "StatefulSet 关联 Pods", Resource: "/api/v1/statefulsets/pods", Action: "GET", Description: "List statefulset related pods"},
		{Name: "删除 StatefulSet", Resource: "/api/v1/statefulsets", Action: "DELETE", Description: "Delete statefulset"},
		{Name: "DaemonSet 垂直扩缩", Resource: "/api/v1/daemonsets/container-resources", Action: "POST", Description: "Patch daemonset container resources"},
		{Name: "DaemonSet 列表", Resource: "/api/v1/daemonsets", Action: "GET", Description: "List daemonsets"},
		{Name: "DaemonSet 详情", Resource: "/api/v1/daemonsets/detail", Action: "GET", Description: "Get daemonset detail"},
		{Name: "DaemonSet 应用 YAML", Resource: "/api/v1/daemonsets/apply", Action: "POST", Description: "Apply daemonset yaml"},
		{Name: "DaemonSet 重启", Resource: "/api/v1/daemonsets/restart", Action: "POST", Description: "Restart daemonset"},
		{Name: "DaemonSet 历史版本", Resource: "/api/v1/daemonsets/revisions", Action: "GET", Description: "List daemonset controller revisions"},
		{Name: "DaemonSet 回滚", Resource: "/api/v1/daemonsets/rollout-undo", Action: "POST", Description: "Undo daemonset rollout"},
		{Name: "DaemonSet 关联 Pods", Resource: "/api/v1/daemonsets/pods", Action: "GET", Description: "List daemonset related pods"},
		{Name: "删除 DaemonSet", Resource: "/api/v1/daemonsets", Action: "DELETE", Description: "Delete daemonset"},
		{Name: "Job 列表", Resource: "/api/v1/jobs", Action: "GET", Description: "List jobs"},
		{Name: "Job 详情", Resource: "/api/v1/jobs/detail", Action: "GET", Description: "Get job detail"},
		{Name: "Job 关联 Pods", Resource: "/api/v1/jobs/pods", Action: "GET", Description: "List job related pods"},
		{Name: "Job 重新执行", Resource: "/api/v1/jobs/rerun", Action: "POST", Description: "Rerun a job"},
		{Name: "Job 垂直扩缩", Resource: "/api/v1/jobs/container-resources", Action: "POST", Description: "Patch job container resources"},
		{Name: "Job 应用 YAML", Resource: "/api/v1/jobs/apply", Action: "POST", Description: "Apply job yaml"},
		{Name: "删除 Job", Resource: "/api/v1/jobs", Action: "DELETE", Description: "Delete job"},
		{Name: "CronJob 列表", Resource: "/api/v1/cronjobs", Action: "GET", Description: "List cronjobs"},
		{Name: "CronJob 列表V2", Resource: "/api/v1/cronjobs/v2", Action: "GET", Description: "List cronjobs with suspend and last schedule"},
		{Name: "CronJob 详情", Resource: "/api/v1/cronjobs/detail", Action: "GET", Description: "Get cronjob detail"},
		{Name: "CronJob 关联 Pods", Resource: "/api/v1/cronjobs/pods", Action: "GET", Description: "List cronjob related pods"},
		{Name: "CronJob 应用 YAML", Resource: "/api/v1/cronjobs/apply", Action: "POST", Description: "Apply cronjob yaml"},
		{Name: "CronJob 垂直扩缩", Resource: "/api/v1/cronjobs/container-resources", Action: "POST", Description: "Patch cronjob container resources"},
		{Name: "CronJob 暂停/恢复", Resource: "/api/v1/cronjobs/suspend", Action: "POST", Description: "Suspend/resume cronjob"},
		{Name: "CronJob 触发执行", Resource: "/api/v1/cronjobs/trigger", Action: "POST", Description: "Trigger cronjob once"},
		{Name: "删除 CronJob", Resource: "/api/v1/cronjobs", Action: "DELETE", Description: "Delete cronjob"},
		{Name: "ConfigMap 列表", Resource: "/api/v1/configmaps", Action: "GET", Description: "List configmaps"},
		{Name: "ConfigMap 详情", Resource: "/api/v1/configmaps/detail", Action: "GET", Description: "Get configmap detail"},
		{Name: "ConfigMap 应用 YAML", Resource: "/api/v1/configmaps/apply", Action: "POST", Description: "Apply configmap yaml"},
		{Name: "删除 ConfigMap", Resource: "/api/v1/configmaps", Action: "DELETE", Description: "Delete configmap"},
		{Name: "Secret 列表", Resource: "/api/v1/secrets", Action: "GET", Description: "List secrets"},
		{Name: "Secret 详情", Resource: "/api/v1/secrets/detail", Action: "GET", Description: "Get secret detail"},
		{Name: "Secret 应用 YAML", Resource: "/api/v1/secrets/apply", Action: "POST", Description: "Apply secret yaml"},
		{Name: "删除 Secret", Resource: "/api/v1/secrets", Action: "DELETE", Description: "Delete secret"},
		{Name: "Service 列表", Resource: "/api/v1/k8s-services", Action: "GET", Description: "List services"},
		{Name: "Service 详情", Resource: "/api/v1/k8s-services/detail", Action: "GET", Description: "Get service detail"},
		{Name: "Service 应用 YAML", Resource: "/api/v1/k8s-services/apply", Action: "POST", Description: "Apply service yaml"},
		{Name: "删除 Service", Resource: "/api/v1/k8s-services", Action: "DELETE", Description: "Delete service"},
		{Name: "PersistentVolume 列表", Resource: "/api/v1/persistentvolumes", Action: "GET", Description: "List persistent volumes"},
		{Name: "PersistentVolume 详情", Resource: "/api/v1/persistentvolumes/detail", Action: "GET", Description: "Get persistent volume detail"},
		{Name: "PersistentVolume 应用 YAML", Resource: "/api/v1/persistentvolumes/apply", Action: "POST", Description: "Apply persistent volume yaml"},
		{Name: "删除 PersistentVolume", Resource: "/api/v1/persistentvolumes", Action: "DELETE", Description: "Delete persistent volume"},
		{Name: "PersistentVolumeClaim 列表", Resource: "/api/v1/persistentvolumeclaims", Action: "GET", Description: "List persistent volume claims"},
		{Name: "PersistentVolumeClaim 详情", Resource: "/api/v1/persistentvolumeclaims/detail", Action: "GET", Description: "Get persistent volume claim detail"},
		{Name: "PersistentVolumeClaim 应用 YAML", Resource: "/api/v1/persistentvolumeclaims/apply", Action: "POST", Description: "Apply persistent volume claim yaml"},
		{Name: "删除 PersistentVolumeClaim", Resource: "/api/v1/persistentvolumeclaims", Action: "DELETE", Description: "Delete persistent volume claim"},
		{Name: "StorageClass 列表", Resource: "/api/v1/storageclasses", Action: "GET", Description: "List storage classes"},
		{Name: "StorageClass 详情", Resource: "/api/v1/storageclasses/detail", Action: "GET", Description: "Get storage class detail"},
		{Name: "StorageClass 应用 YAML", Resource: "/api/v1/storageclasses/apply", Action: "POST", Description: "Apply storage class yaml"},
		{Name: "删除 StorageClass", Resource: "/api/v1/storageclasses", Action: "DELETE", Description: "Delete storage class"},
		{Name: "Ingress 列表", Resource: "/api/v1/ingresses", Action: "GET", Description: "List ingresses"},
		{Name: "Ingress 详情", Resource: "/api/v1/ingresses/detail", Action: "GET", Description: "Get ingress detail"},
		{Name: "Ingress 诊断", Resource: "/api/v1/ingresses/diagnose", Action: "GET", Description: "Diagnose ingress issues"},
		{Name: "Ingress 应用 YAML", Resource: "/api/v1/ingresses/apply", Action: "POST", Description: "Apply ingress yaml"},
		{Name: "IngressClass 列表", Resource: "/api/v1/ingresses/classes", Action: "GET", Description: "List ingress classes"},
		{Name: "IngressClass 详情", Resource: "/api/v1/ingresses/classes/detail", Action: "GET", Description: "Get ingress class detail"},
		{Name: "IngressClass 应用 YAML", Resource: "/api/v1/ingresses/classes/apply", Action: "POST", Description: "Apply ingress class yaml"},
		{Name: "删除 IngressClass", Resource: "/api/v1/ingresses/classes", Action: "DELETE", Description: "Delete ingress class"},
		{Name: "重启 Ingress-Nginx Pods", Resource: "/api/v1/ingresses/nginx/restart", Action: "POST", Description: "Restart ingress-nginx controller pods (requires cluster admin tier + confirm=true)"},
		{Name: "删除 Ingress", Resource: "/api/v1/ingresses", Action: "DELETE", Description: "Delete ingress"},
		{Name: "HPA 列表", Resource: "/api/v1/horizontal-pod-autoscalers", Action: "GET", Description: "List HorizontalPodAutoscaler"},
		{Name: "HPA 详情", Resource: "/api/v1/horizontal-pod-autoscalers/detail", Action: "GET", Description: "Get HPA YAML"},
		{Name: "HPA 应用 YAML", Resource: "/api/v1/horizontal-pod-autoscalers/apply", Action: "POST", Description: "Apply HPA yaml"},
		{Name: "删除 HPA", Resource: "/api/v1/horizontal-pod-autoscalers", Action: "DELETE", Description: "Delete HPA"},
		{Name: "Harbor 信息", Resource: "/api/v1/helm/harbor/info", Action: "GET", Description: "Get Harbor helm repo info"},
		{Name: "Harbor Chart 列表", Resource: "/api/v1/helm/harbor/charts", Action: "GET", Description: "List Harbor helm charts"},
		{Name: "Harbor Chart 版本", Resource: "/api/v1/helm/harbor/charts/versions", Action: "GET", Description: "List Harbor chart versions"},
		{Name: "Helm Release 列表", Resource: "/api/v1/helm/releases", Action: "GET", Description: "List helm releases"},
		{Name: "Helm Release 详情", Resource: "/api/v1/helm/releases/detail", Action: "GET", Description: "Get helm release detail"},
		{Name: "Helm Release 历史", Resource: "/api/v1/helm/releases/history", Action: "GET", Description: "Get helm release history"},
		{Name: "Helm Release Values", Resource: "/api/v1/helm/releases/values", Action: "GET", Description: "Get helm release values"},
		{Name: "Helm 安装", Resource: "/api/v1/helm/releases/install", Action: "POST", Description: "Install helm release from Harbor"},
		{Name: "Helm 升级", Resource: "/api/v1/helm/releases/upgrade", Action: "POST", Description: "Upgrade helm release"},
		{Name: "Helm 回滚", Resource: "/api/v1/helm/releases/rollback", Action: "POST", Description: "Rollback helm release"},
		{Name: "Helm 卸载", Resource: "/api/v1/helm/releases", Action: "DELETE", Description: "Uninstall helm release"},
		{Name: "网络策略列表", Resource: "/api/v1/network-policies", Action: "GET", Description: "List network policies"},
		{Name: "网络策略详情", Resource: "/api/v1/network-policies/detail", Action: "GET", Description: "Get network policy detail"},
		{Name: "网络策略应用 YAML", Resource: "/api/v1/network-policies/apply", Action: "POST", Description: "Apply network policy yaml"},
		{Name: "删除网络策略", Resource: "/api/v1/network-policies", Action: "DELETE", Description: "Delete network policy"},
		{Name: "工作负载预检", Resource: "/api/v1/deployments/preview-apply", Action: "POST", Description: "Preview workload apply"},
		{Name: "工作负载快照", Resource: "/api/v1/deployments/snapshots", Action: "GET", Description: "List workload snapshots"},
		{Name: "工作负载回滚", Resource: "/api/v1/deployments/snapshots/rollback", Action: "POST", Description: "Rollback workload snapshot"},
		{Name: "Event 列表", Resource: "/api/v1/events", Action: "GET", Description: "List events"},
		{Name: "Event 分组列表", Resource: "/api/v1/events/grouped", Action: "GET", Description: "List events grouped"},
		{Name: "CRD 列表", Resource: "/api/v1/crds", Action: "GET", Description: "List custom resource definitions"},
		{Name: "CRD 详情", Resource: "/api/v1/crds/detail", Action: "GET", Description: "Get custom resource definition detail"},
		{Name: "CRD 应用 YAML", Resource: "/api/v1/crds/apply", Action: "POST", Description: "Apply custom resource definition yaml"},
		{Name: "删除 CRD", Resource: "/api/v1/crds", Action: "DELETE", Description: "Delete custom resource definition"},
		{Name: "K8s CR 模板列表", Resource: "/api/v1/k8s-cr-templates", Action: "GET", Description: "List k8s CR/YAML templates"},
		{Name: "创建 K8s CR 模板", Resource: "/api/v1/k8s-cr-templates", Action: "POST", Description: "Create k8s CR template"},
		{Name: "更新 K8s CR 模板", Resource: "/api/v1/k8s-cr-templates/:id", Action: "PUT", Description: "Update k8s CR template"},
		{Name: "删除 K8s CR 模板", Resource: "/api/v1/k8s-cr-templates/:id", Action: "DELETE", Description: "Delete k8s CR template"},
		{Name: "CR 资源类型列表", Resource: "/api/v1/crs/resources", Action: "GET", Description: "List custom resource types"},
		{Name: "CR 实例列表", Resource: "/api/v1/crs", Action: "GET", Description: "List custom resources"},
		{Name: "CR 实例详情", Resource: "/api/v1/crs/detail", Action: "GET", Description: "Get custom resource detail"},
		{Name: "CR 实例应用 YAML", Resource: "/api/v1/crs/apply", Action: "POST", Description: "Apply custom resource yaml"},
		{Name: "删除 CR 实例", Resource: "/api/v1/crs", Action: "DELETE", Description: "Delete custom resource"},
	}
}

