/** auto-generated by scripts/generate-page-registry.mjs — do not edit */
import { lazy, type ComponentType, type LazyExoticComponent } from 'react';

function resolveExport(mod: Record<string, unknown>, exportName: string): { default: ComponentType<object> } {
  const direct = mod[exportName] as ComponentType<object> | undefined;
  const fallback = mod.default as ComponentType<object> | undefined;
  const pageLike = Object.entries(mod).find(([k, v]) => k !== 'default' && /page$/i.test(k) && typeof v === 'function')?.[1] as
    | ComponentType<object>
    | undefined;
  const Comp = direct ?? fallback ?? pageLike;
  if (!Comp) throw new Error(`页面未导出 ${exportName}`);
  return { default: Comp };
}

const loaders: Record<string, () => Promise<{ default: ComponentType<object> }>> = {
  'ai-approvals-page': () => import('../pages/ai-approvals-page').then((m) => resolveExport(m, 'AiApprovalsPage')),
  'ai-assistant-page': () => import('../pages/ai-assistant-page').then((m) => resolveExport(m, 'AiAssistantPage')),
  'ai-center-page': () => import('../pages/ai-center-page').then((m) => resolveExport(m, 'AiCenterPage')),
  'ai-investigations-page': () => import('../pages/ai-investigations-page').then((m) => resolveExport(m, 'AiInvestigationsPage')),
  'alert-channels-page': () => import('../pages/alert-channels-page').then((m) => resolveExport(m, 'AlertChannelsPage')),
  'alert-config-center-page': () => import('../pages/alert-config-center-page').then((m) => resolveExport(m, 'AlertConfigCenterPage')),
  'alert-duty-page': () => import('../pages/alert-duty-page').then((m) => resolveExport(m, 'AlertDutyPage')),
  'alert-events-page': () => import('../pages/alert-events-page').then((m) => resolveExport(m, 'AlertEventsPage')),
  'alert-maintenance-page': () => import('../pages/alert-maintenance-page').then((m) => resolveExport(m, 'AlertMaintenancePage')),
  'alert-monitor-platform-page': () => import('../pages/alert-monitor-platform-page').then((m) => resolveExport(m, 'AlertMonitorPlatformPage')),
  'alert-quality-page': () => import('../pages/alert-quality-page').then((m) => resolveExport(m, 'AlertQualityPage')),
  'banned-ips-page': () => import('../pages/banned-ips-page').then((m) => resolveExport(m, 'BannedIpsPage')),
  'cicd-approval-flow-page': () => import('../pages/cicd-approval-flow-page').then((m) => resolveExport(m, 'CicdApprovalFlowPage')),
  'cicd-build-records-page': () => import('../pages/cicd-build-records-page').then((m) => resolveExport(m, 'CicdBuildRecordsPage')),
  'cicd-image-browser-page': () => import('../pages/cicd-image-browser-page').then((m) => resolveExport(m, 'CicdImageBrowserPage')),
  'cicd-registries-page': () => import('../pages/cicd-registries-page').then((m) => resolveExport(m, 'CicdRegistriesPage')),
  'cicd-release-records-page': () => import('../pages/cicd-release-records-page').then((m) => resolveExport(m, 'CicdReleaseRecordsPage')),
  'cicd-services-page': () => import('../pages/cicd-services-page').then((m) => resolveExport(m, 'CicdServicesPage')),
  'cicd-todo-page': () => import('../pages/cicd-todo-page').then((m) => resolveExport(m, 'CicdTodoPage')),
  'cluster-api-resources-page': () => import('../pages/cluster-api-resources-page').then((m) => resolveExport(m, 'ClusterApiResourcesPage')),
  'cluster-page': () => import('../pages/cluster-page').then((m) => resolveExport(m, 'ClusterPage')),
  'component-status-page': () => import('../pages/component-status-page').then((m) => resolveExport(m, 'ComponentStatusPage')),
  'configmaps-page': () => import('../pages/configmaps-page').then((m) => resolveExport(m, 'ConfigmapsPage')),
  'crds-page': () => import('../pages/crds-page').then((m) => resolveExport(m, 'CrdsPage')),
  'cronjobs-page': () => import('../pages/cronjobs-page').then((m) => resolveExport(m, 'CronjobsPage')),
  'crs-page': () => import('../pages/crs-page').then((m) => resolveExport(m, 'CrsPage')),
  'daemonsets-page': () => import('../pages/daemonsets-page').then((m) => resolveExport(m, 'DaemonsetsPage')),
  'dashboard-page': () => import('../pages/dashboard-page').then((m) => resolveExport(m, 'DashboardPage')),
  'dbmgmt-access-requests-page': () => import('../pages/dbmgmt-access-requests-page').then((m) => resolveExport(m, 'DbmgmtAccessRequestsPage')),
  'dbmgmt-app-user-apply-page': () => import('../pages/dbmgmt-app-user-apply-page').then((m) => resolveExport(m, 'DbmgmtAppUserApplyPage')),
  'dbmgmt-approval-flow-page': () => import('../pages/dbmgmt-approval-flow-page').then((m) => resolveExport(m, 'DbmgmtApprovalFlowPage')),
  'dbmgmt-audit-page': () => import('../pages/dbmgmt-audit-page').then((m) => resolveExport(m, 'DbmgmtAuditPage')),
  'dbmgmt-console-page': () => import('../pages/dbmgmt-console-page').then((m) => resolveExport(m, 'DbmgmtConsolePage')),
  'dbmgmt-database-apply-page': () => import('../pages/dbmgmt-database-apply-page').then((m) => resolveExport(m, 'DbmgmtDatabaseApplyPage')),
  'dbmgmt-grants-page': () => import('../pages/dbmgmt-grants-page').then((m) => resolveExport(m, 'DbmgmtGrantsPage')),
  'dbmgmt-instance-detail-page': () => import('../pages/dbmgmt-instance-detail-page').then((m) => resolveExport(m, 'DbmgmtInstanceDetailPage')),
  'dbmgmt-instances-page': () => import('../pages/dbmgmt-instances-page').then((m) => resolveExport(m, 'DbmgmtInstancesPage')),
  'dbmgmt-ticket-detail-page': () => import('../pages/dbmgmt-ticket-detail-page').then((m) => resolveExport(m, 'DbmgmtTicketDetailPage')),
  'dbmgmt-tickets-page': () => import('../pages/dbmgmt-tickets-page').then((m) => resolveExport(m, 'DbmgmtTicketsPage')),
  'dbmgmt-todo-page': () => import('../pages/dbmgmt-todo-page').then((m) => resolveExport(m, 'DbmgmtTodoPage')),
  'departments-page': () => import('../pages/departments-page').then((m) => resolveExport(m, 'DepartmentsPage')),
  'deployments-page': () => import('../pages/deployments-page').then((m) => resolveExport(m, 'DeploymentsPage')),
  'dict-entries-page': () => import('../pages/dict-entries-page').then((m) => resolveExport(m, 'DictEntriesPage')),
  'esmgmt-connections-page': () => import('../pages/esmgmt-connections-page').then((m) => resolveExport(m, 'EsmgmtConnectionsPage')),
  'esmgmt-console-page': () => import('../pages/esmgmt-console-page').then((m) => resolveExport(m, 'EsmgmtConsolePage')),
  'esmgmt-overview-page': () => import('../pages/esmgmt-overview-page').then((m) => resolveExport(m, 'EsmgmtOverviewPage')),
  'events-page': () => import('../pages/events-page').then((m) => resolveExport(m, 'EventsPage')),
  'helm-charts-page': () => import('../pages/helm-charts-page').then((m) => resolveExport(m, 'HelmChartsPage')),
  'helm-releases-page': () => import('../pages/helm-releases-page').then((m) => resolveExport(m, 'HelmReleasesPage')),
  'horizontal-pod-autoscalers-page': () => import('../pages/horizontal-pod-autoscalers-page').then((m) => resolveExport(m, 'HorizontalPodAutoscalersPage')),
  'ingress-classes-page': () => import('../pages/ingress-classes-page').then((m) => resolveExport(m, 'IngressClassesPage')),
  'ingresses-page': () => import('../pages/ingresses-page').then((m) => resolveExport(m, 'IngressesPage')),
  'jobs-page': () => import('../pages/jobs-page').then((m) => resolveExport(m, 'JobsPage')),
  'k8s-cr-templates-page': () => import('../pages/k8s-cr-templates-page').then((m) => resolveExport(m, 'K8sCrTemplatesPage')),
  'k8s-event-forward-page': () => import('../pages/k8s-event-forward-page').then((m) => resolveExport(m, 'K8sEventForwardPage')),
  'k8s-resource-topology-page': () => import('../pages/k8s-resource-topology-page').then((m) => resolveExport(m, 'K8sResourceTopologyPage')),
  'k8s-scoped-policies-page': () => import('../pages/k8s-scoped-policies-page').then((m) => resolveExport(m, 'K8sScopedPoliciesPage')),
  'k8s-services-page': () => import('../pages/k8s-services-page').then((m) => resolveExport(m, 'K8sServicesPage')),
  'log-retention-page': () => import('../pages/log-retention-page').then((m) => resolveExport(m, 'LogRetentionPage')),
  'loggie-status-page': () => import('../pages/loggie-status-page').then((m) => resolveExport(m, 'LoggieStatusPage')),
  'login-logs-page': () => import('../pages/login-logs-page').then((m) => resolveExport(m, 'LoginLogsPage')),
  'menus-page': () => import('../pages/menus-page').then((m) => resolveExport(m, 'MenusPage')),
  'mysql-backup-page': () => import('../pages/mysql-backup-page').then((m) => resolveExport(m, 'MysqlBackupPage')),
  'namespaces-page': () => import('../pages/namespaces-page').then((m) => resolveExport(m, 'NamespacesPage')),
  'network-policies-page': () => import('../pages/network-policies-page').then((m) => resolveExport(m, 'NetworkPoliciesPage')),
  'nodes-page': () => import('../pages/nodes-page').then((m) => resolveExport(m, 'NodesPage')),
  'operation-logs-page': () => import('../pages/operation-logs-page').then((m) => resolveExport(m, 'OperationLogsPage')),
  'permissions-page': () => import('../pages/permissions-page').then((m) => resolveExport(m, 'PermissionsPage')),
  'persistentvolumeclaims-page': () => import('../pages/persistentvolumeclaims-page').then((m) => resolveExport(m, 'PersistentvolumeclaimsPage')),
  'persistentvolumes-page': () => import('../pages/persistentvolumes-page').then((m) => resolveExport(m, 'PersistentvolumesPage')),
  'personal-settings-page': () => import('../pages/personal-settings-page').then((m) => resolveExport(m, 'PersonalSettingsPage')),
  'platform-templates-page': () => import('../pages/platform-templates-page').then((m) => resolveExport(m, 'PlatformTemplatesPage')),
  'plugins-page': () => import('../pages/plugins-page').then((m) => resolveExport(m, 'PluginsPage')),
  'pod-page': () => import('../pages/pod-page').then((m) => resolveExport(m, 'PodPage')),
  'policies-page': () => import('../pages/policies-page').then((m) => resolveExport(m, 'PoliciesPage')),
  'project-cluster-log-page': () => import('../pages/project-cluster-log-page').then((m) => resolveExport(m, 'ProjectClusterLogPage')),
  'project-collect-config-page': () => import('../pages/project-collect-config-page').then((m) => resolveExport(m, 'ProjectCollectConfigPage')),
  'project-inspect-page': () => import('../pages/project-inspect-page').then((m) => resolveExport(m, 'ProjectInspectPage')),
  'project-log-sources-page': () => import('../pages/project-log-sources-page').then((m) => resolveExport(m, 'ProjectLogSourcesPage')),
  'project-logs-page': () => import('../pages/project-logs-page').then((m) => resolveExport(m, 'ProjectLogsPage')),
  'project-members-page': () => import('../pages/project-members-page').then((m) => resolveExport(m, 'ProjectMembersPage')),
  'project-servers-page': () => import('../pages/project-servers-page').then((m) => resolveExport(m, 'ProjectServersPage')),
  'project-services-page': () => import('../pages/project-services-page').then((m) => resolveExport(m, 'ProjectServicesPage')),
  'projects-page': () => import('../pages/projects-page').then((m) => resolveExport(m, 'ProjectsPage')),
  'rbac-clusterrolebindings-page': () => import('../pages/rbac-clusterrolebindings-page').then((m) => resolveExport(m, 'RbacClusterrolebindingsPage')),
  'rbac-clusterroles-page': () => import('../pages/rbac-clusterroles-page').then((m) => resolveExport(m, 'RbacClusterrolesPage')),
  'rbac-rolebindings-page': () => import('../pages/rbac-rolebindings-page').then((m) => resolveExport(m, 'RbacRolebindingsPage')),
  'rbac-roles-page': () => import('../pages/rbac-roles-page').then((m) => resolveExport(m, 'RbacRolesPage')),
  'registrations-page': () => import('../pages/registrations-page').then((m) => resolveExport(m, 'RegistrationsPage')),
  'roles-page': () => import('../pages/roles-page').then((m) => resolveExport(m, 'RolesPage')),
  'secrets-page': () => import('../pages/secrets-page').then((m) => resolveExport(m, 'SecretsPage')),
  'server-console-page': () => import('../pages/server-console-page').then((m) => resolveExport(m, 'ServerConsolePage')),
  'service-catalog-page': () => import('../pages/service-catalog-page').then((m) => resolveExport(m, 'ServiceCatalogPage')),
  'service-portrait-page': () => import('../pages/service-portrait-page').then((m) => resolveExport(m, 'ServicePortraitPage')),
  'serviceaccounts-page': () => import('../pages/serviceaccounts-page').then((m) => resolveExport(m, 'ServiceaccountsPage')),
  'statefulsets-page': () => import('../pages/statefulsets-page').then((m) => resolveExport(m, 'StatefulsetsPage')),
  'storageclasses-page': () => import('../pages/storageclasses-page').then((m) => resolveExport(m, 'StorageclassesPage')),
  'user-groups-page': () => import('../pages/user-groups-page').then((m) => resolveExport(m, 'UserGroupsPage')),
  'users-page': () => import('../pages/users-page').then((m) => resolveExport(m, 'UsersPage')),
  'workflow-definitions-page': () => import('../pages/workflow-definitions-page').then((m) => resolveExport(m, 'WorkflowDefinitionsPage')),
  'workflow-inbox-page': () => import('../pages/workflow-inbox-page').then((m) => resolveExport(m, 'WorkflowInboxPage')),
  'workflow-tickets-page': () => import('../pages/workflow-tickets-page').then((m) => resolveExport(m, 'WorkflowTicketsPage')),
};

export function createLazyLegacyPage(componentField: string): LazyExoticComponent<ComponentType<object>> | null {
  const normalized = componentField.trim().replace(/^\//, '').replace(/\\/g, '/').replace(/\.tsx$/i, '');
  if (!normalized) return null;
  const id = normalized.endsWith('-page') ? normalized : `${normalized}-page`;
  const loader = loaders[id];
  if (!loader) return null;
  return lazy(loader);
}

export function listLegacyPageIds(): string[] {
  return Object.keys(loaders).sort();
}
