// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

// Injectors from wire.go:

// InitializeCore wires config, logger, and MySQL (no Redis).
func InitializeCore(configPath string) (*Infra, error) {
	config, err := NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(config)
	if err != nil {
		return nil, err
	}
	db, err := NewDB(config, logger)
	if err != nil {
		return nil, err
	}
	infra := &Infra{
		Config: config,
		Logger: logger,
		DB:     db,
	}
	return infra, nil
}

// InitializeInfra wires full infrastructure including Redis.
func InitializeInfra(configPath string) (*Infra, error) {
	config, err := NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(config)
	if err != nil {
		return nil, err
	}
	db, err := NewDB(config, logger)
	if err != nil {
		return nil, err
	}
	client, err := NewRedis(config)
	if err != nil {
		return nil, err
	}
	infra := &Infra{
		Config: config,
		Logger: logger,
		DB:     db,
		Redis:  client,
	}
	return infra, nil
}
