{{- if and .Values.enabled .Values.secretConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-base.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "config-base.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.secretConfigs }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
