package router

import "github.com/gin-gonic/gin"

func RegisterAIRoutes(api *gin.RouterGroup, d AIRouteDeps) {
	if d == nil || d.AIHandler() == nil {
		return
	}
	h := d.AIHandler()
	g := api.Group("/ai")
	g.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	g.GET("/status", h.Status)
	g.POST("/ping", h.Ping)
	g.POST("/chat", h.Chat)
	g.POST("/chat/stream", h.ChatStream)
	g.GET("/sessions", h.ListSessions)
	g.POST("/sessions", h.CreateSession)
	g.GET("/sessions/:id", h.GetSession)
	g.PATCH("/sessions/:id", h.UpdateSession)
	g.DELETE("/sessions/:id", h.DeleteSession)
	g.POST("/sessions/:id/clear", h.ClearSession)
	g.POST("/investigations", h.StartInvestigation)
	g.GET("/investigations", h.ListInvestigations)
	g.GET("/investigations/:id", h.GetInvestigation)
	g.POST("/k8s/pod-diagnose", h.PodDiagnose)
	g.POST("/k8s/generate-yaml", h.GenerateK8sYAML)
	g.POST("/cicd/build-fail", h.CicdBuildFail)
	g.POST("/alert/explain", h.AlertExplain)
	g.POST("/logs/analyze", h.LogAnalyze)
	g.POST("/logs/pipeline-adjust", h.PipelineAdjust)
	g.GET("/approvals", h.ListApprovals)
	g.POST("/approvals/:id/review", h.ReviewApproval)
	g.POST("/approvals/:id/execute", h.ExecuteApproval)
	g.POST("/knowledge/sync", h.SyncKnowledge)
	g.POST("/knowledge/embed", h.EmbedKnowledge)
	g.GET("/center/overview", h.CenterOverview)
	g.GET("/center/tool-runtime-health", h.ToolRuntimeHealth)
	g.POST("/center/reseed", h.ReseedCenter)
	g.GET("/center/prompts", h.ListPrompts)
	g.POST("/center/prompts", h.CreatePrompt)
	g.GET("/center/prompts/:id/versions", h.ListPromptVersions)
	g.POST("/center/prompts/:id/publish", h.PublishPrompt)
	g.POST("/center/prompts/:id/versions/:vid/rollback", h.RollbackPrompt)
	g.GET("/center/prompts/:id", h.GetPrompt)
	g.PUT("/center/prompts/:id", h.UpdatePrompt)
	g.DELETE("/center/prompts/:id", h.DeletePrompt)
	g.GET("/center/models", h.ListLLMModels)
	g.POST("/center/models", h.CreateLLMModel)
	g.PUT("/center/models/:id", h.UpdateLLMModel)
	g.DELETE("/center/models/:id", h.DeleteLLMModel)
	g.POST("/center/models/:id/default", h.SetDefaultLLMModel)
	g.GET("/center/tools", h.ListCenterTools)
	g.POST("/center/tools", h.CreateTool)
	g.GET("/center/tools/:id", h.GetTool)
	g.PUT("/center/tools/:id", h.UpdateTool)
	g.PATCH("/center/tools/:id", h.UpdateToolEnabled)
	g.DELETE("/center/tools/:id", h.DeleteTool)
	g.GET("/center/cases", h.ListCases)
	g.POST("/center/cases", h.CreateCase)
	g.GET("/center/cases/:id", h.GetCase)
	g.PUT("/center/cases/:id", h.UpdateCase)
	g.DELETE("/center/cases/:id", h.DeleteCase)
	g.GET("/center/sops", h.ListSOPs)
	g.POST("/center/sops", h.CreateSOP)
	g.GET("/center/sops/:id", h.GetSOP)
	g.PUT("/center/sops/:id", h.UpdateSOP)
	g.DELETE("/center/sops/:id", h.DeleteSOP)
	g.GET("/center/knowledge-bases", h.ListKBs)
	g.POST("/center/knowledge-bases", h.CreateKB)
	g.PUT("/center/knowledge-bases/:id", h.UpdateKB)
	g.DELETE("/center/knowledge-bases/:id", h.DeleteKB)
	g.GET("/center/kb-documents", h.ListKBDocuments)
	g.POST("/center/kb-documents", h.CreateKBDocument)
	g.GET("/center/kb-documents/:id", h.GetKBDocument)
	g.PUT("/center/kb-documents/:id", h.UpdateKBDocument)
	g.DELETE("/center/kb-documents/:id", h.DeleteKBDocument)
	g.GET("/center/eval/cases", h.ListEvalCases)
	g.POST("/center/eval/cases", h.CreateEvalCase)
	g.POST("/center/eval/run", h.RunEval)
	g.GET("/center/eval/runs", h.ListEvalRuns)
	g.GET("/center/eval/runs/:id", h.GetEvalRun)
	g.GET("/center/eval/cases/:id", h.GetEvalCase)
	g.PUT("/center/eval/cases/:id", h.UpdateEvalCase)
	g.DELETE("/center/eval/cases/:id", h.DeleteEvalCase)
}
