package router

import (
	"yunshu/internal/middleware"

	"github.com/gin-gonic/gin"
)

// RegisterProjectRoutes 多租户项目、成员、服务配置与 ES 日志检索。
func RegisterProjectRoutes(api *gin.RouterGroup, d ProjectRouteDeps) {
	projectRoutes := api.Group("/projects")
	projectRoutes.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	projectRoutes.GET("", d.ProjectHandler().List)
	projectRoutes.POST("", d.ProjectHandler().Create)
	projectScoped := projectRoutes.Group("/:id", middleware.RequireProjectMemberAccess(d.ProjectMemberRepo(), d.ProjectRepo(), d.AppLogger()))
	projectScoped.PUT("", d.ProjectHandler().Update)
	projectScoped.POST("/archive", d.ProjectHandler().Archive)
	projectScoped.POST("/restore", d.ProjectHandler().Restore)
	projectScoped.DELETE("", d.ProjectHandler().Delete)
	projectScoped.GET("/members", d.ProjectHandler().ListProjectMembers)
	projectScoped.POST("/members", d.ProjectHandler().AddProjectMember)
	projectScoped.PUT("/members/:memberId", d.ProjectHandler().UpdateProjectMember)
	projectScoped.DELETE("/members/:memberId", d.ProjectHandler().RemoveProjectMember)
	projectScoped.GET("/services", d.ProjectHandler().ListServices)
	projectScoped.POST("/services", d.ProjectHandler().UpsertService)
	projectScoped.DELETE("/services/:serviceId", d.ProjectHandler().DeleteService)
	projectScoped.GET("/log-sources", d.ProjectHandler().ListLogSources)
	projectScoped.POST("/log-sources", d.ProjectHandler().UpsertLogSource)
	projectScoped.DELETE("/log-sources/:logSourceId", d.ProjectHandler().DeleteLogSource)
	projectScoped.GET("/logs/search", d.ProjectHandler().SearchLogs)
	projectScoped.GET("/logs/overview", d.ProjectHandler().LogOverview)
	projectScoped.GET("/logs/topn", d.ProjectHandler().LogTopN)
	projectScoped.GET("/logs/fields", d.ProjectHandler().DiscoverLogFields)
	projectScoped.GET("/logs/patterns", d.ProjectHandler().ListLogPatterns)
	projectScoped.GET("/logs/anomalies", d.ProjectHandler().ListLogAnomalies)
	projectScoped.PUT("/logs/anomalies/:anomaly_id", d.ProjectHandler().UpdateLogAnomaly)
	projectScoped.GET("/logs/context", d.ProjectHandler().LogContext)
	projectScoped.GET("/logs/export", d.ProjectHandler().ExportLogs)
	projectScoped.GET("/log-retention", d.LogPlatformHandler().GetProjectRetention)
	projectScoped.PUT("/log-retention", d.LogPlatformHandler().UpsertProjectRetention)
	projectScoped.DELETE("/log-retention", d.LogPlatformHandler().DeleteProjectRetention)
	projectScoped.POST("/loggie/bootstrap", d.LoggieHandler().Bootstrap)
	projectScoped.GET("/loggie/status", d.LoggieHandler().ListStatus)
	projectScoped.GET("/loggie/bootstrap-sources", d.LoggieHandler().PreviewBootstrapSources)
	projectScoped.GET("/loggie/pipeline/download", d.LoggieHandler().DownloadPipeline)
	projectScoped.POST("/loggie/deploy", d.LoggieHandler().DeployConfig)
	projectScoped.POST("/loggie/install", d.LoggieHandler().InstallLoggie)
	projectScoped.POST("/loggie/uninstall", d.LoggieHandler().UninstallLoggie)
	projectScoped.POST("/loggie/start", d.LoggieHandler().StartLoggie)
	projectScoped.POST("/loggie/stop", d.LoggieHandler().StopLoggie)
	projectScoped.POST("/loggie/restart", d.LoggieHandler().RestartLoggie)
	projectScoped.POST("/loggie/sync", d.LoggieHandler().SyncFromLogSources)
	if d.ClusterLogHandler() != nil {
		projectScoped.GET("/cluster-log/rules", d.ClusterLogHandler().ListRules)
		projectScoped.POST("/cluster-log/rules", d.ClusterLogHandler().CreateRule)
		projectScoped.PUT("/cluster-log/rules/:rule_id", d.ClusterLogHandler().UpdateRule)
		projectScoped.DELETE("/cluster-log/rules/:rule_id", d.ClusterLogHandler().DeleteRule)
		projectScoped.GET("/cluster-log/agents", d.ClusterLogHandler().ListAgents)
		projectScoped.GET("/cluster-log/pipelines/preview", d.ClusterLogHandler().PreviewPipelines)
		projectScoped.PUT("/cluster-log/pipelines", d.ClusterLogHandler().SavePipelines)
		projectScoped.POST("/cluster-log/deploy", d.ClusterLogHandler().Deploy)
		projectScoped.GET("/cluster-log/status", d.ClusterLogHandler().RefreshStatus)
		projectScoped.GET("/log-pipelines", d.ClusterLogHandler().ListPipelinesRepo)
		projectScoped.POST("/log-pipelines", d.ClusterLogHandler().CreatePipelineRepo)
		projectScoped.POST("/log-pipelines/sync-from-cluster", d.ClusterLogHandler().SyncPipelineRepoFromCluster)
		projectScoped.GET("/log-pipelines/:pipeline_id/versions", d.ClusterLogHandler().ListPipelineVersions)
		projectScoped.POST("/log-pipelines/:pipeline_id/versions/:version_id/rollback", d.ClusterLogHandler().RollbackPipelineVersion)
		projectScoped.GET("/log-pipelines/:pipeline_id", d.ClusterLogHandler().GetPipelineRepo)
		projectScoped.PUT("/log-pipelines/:pipeline_id", d.ClusterLogHandler().UpdatePipelineRepo)
		projectScoped.DELETE("/log-pipelines/:pipeline_id", d.ClusterLogHandler().DeletePipelineRepo)
		projectScoped.POST("/log-pipelines/:pipeline_id/apply", d.ClusterLogHandler().ApplyPipelineRepo)
		projectScoped.GET("/log-parse-profiles", d.ClusterLogHandler().ListParseProfiles)
		projectScoped.GET("/log-saved-queries", d.ClusterLogHandler().ListSavedLogQueries)
		projectScoped.POST("/log-saved-queries", d.ClusterLogHandler().CreateSavedLogQuery)
		projectScoped.DELETE("/log-saved-queries/:query_id", d.ClusterLogHandler().DeleteSavedLogQuery)
		projectScoped.GET("/log-drop-rules", d.ClusterLogHandler().ListLogDropRules)
		projectScoped.POST("/log-drop-rules", d.ClusterLogHandler().CreateLogDropRule)
		projectScoped.PUT("/log-drop-rules/:rule_id", d.ClusterLogHandler().UpdateLogDropRule)
		projectScoped.DELETE("/log-drop-rules/:rule_id", d.ClusterLogHandler().DeleteLogDropRule)
	}
	projectScoped.POST("/loggie/deploy-yaml", d.LoggieHandler().DeployCustomYAML)
	projectScoped.GET("/service-catalog", d.ProjectCatalogHandler().ListCatalog)
	projectScoped.POST("/service-catalog", d.ProjectCatalogHandler().UpsertCatalog)
	projectScoped.GET("/service-catalog/:catalogId", d.ProjectCatalogHandler().GetCatalog)
	projectScoped.GET("/service-catalog/:catalogId/portrait", d.ProjectCatalogHandler().GetPortrait)
	projectScoped.DELETE("/service-catalog/:catalogId", d.ProjectCatalogHandler().DeleteCatalog)
	projectScoped.POST("/service-catalog/:catalogId/links", d.ProjectCatalogHandler().AddLink)
	projectScoped.DELETE("/service-catalog/:catalogId/links/:linkId", d.ProjectCatalogHandler().DeleteLink)
	projectScoped.GET("/change-events", d.ProjectCatalogHandler().ListChangeEvents)
}
