package router

import (
	"github.com/gin-gonic/gin"
)

// RegisterK8sRoutes Kubernetes 集群与资源管理、K8s 权限策略、总览面板。
func RegisterK8sRoutes(api *gin.RouterGroup, d *RouteDeps) {
	// 当前用户档位查询：仅需登录，不依赖 Casbin（用于前端隐藏 Exec/变更按钮）
	k8sMyAccess := api.Group("/k8s-policies")
	k8sMyAccess.Use(d.authMiddleware, d.opAudit)
	k8sMyAccess.GET("/my-access", d.k8sScopedPolicyHandler.MyAccess)

	k8sPolicies := api.Group("/k8s-policies")
	k8sPolicies.Use(d.authMiddleware, d.authorize, d.opAudit)
	k8sPolicies.GET("/actions", d.k8sScopedPolicyHandler.Actions)
	k8sPolicies.GET("/capabilities", d.k8sScopedPolicyHandler.Capabilities)
	k8sPolicies.GET("/paths", d.k8sScopedPolicyHandler.Paths)
	k8sPolicies.GET("", d.k8sScopedPolicyHandler.ListByRole)
	k8sPolicies.GET("/cluster-auth-matrix", d.k8sScopedPolicyHandler.ClusterAuthMatrix)
	k8sPolicies.GET("/user-cluster-auth", d.k8sScopedPolicyHandler.UserClusterAuth)
	k8sPolicies.POST("/grant-preset", d.k8sScopedPolicyHandler.GrantPreset)
	k8sPolicies.POST("/split-by-namespaces", d.k8sScopedPolicyHandler.SplitByNamespaces)
	k8sPolicies.DELETE("/cluster-grants/:id", d.k8sScopedPolicyHandler.DeleteClusterGrant)
	k8sPolicies.POST("/cluster-grants/batch-delete", d.k8sScopedPolicyHandler.DeleteClusterGrantsBatch)

	k8sNsDeny := api.Group("/k8s-namespace-deny-rules")
	k8sNsDeny.Use(d.authMiddleware, d.authorize, d.opAudit)
	k8sNsDeny.GET("", d.k8sNamespaceDenyHandler.List)
	k8sNsDeny.POST("", d.k8sNamespaceDenyHandler.Create)
	k8sNsDeny.DELETE("/:id", d.k8sNamespaceDenyHandler.Delete)

	k8sNsAllow := api.Group("/k8s-namespace-allow-rules")
	k8sNsAllow.Use(d.authMiddleware, d.authorize, d.opAudit)
	k8sNsAllow.GET("", d.k8sNamespaceAllowHandler.List)
	k8sNsAllow.POST("", d.k8sNamespaceAllowHandler.Create)
	k8sNsAllow.DELETE("/:id", d.k8sNamespaceAllowHandler.Delete)

	// Kubernetes cluster management (Kom SDK)
	clusters := api.Group("/clusters")
	clusters.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	clusters.GET("", d.clusterHandler.List)
	clusters.GET("/:id", d.clusterHandler.Detail)
	clusters.POST("", d.clusterHandler.Create)
	clusters.PUT("/:id", d.clusterHandler.Update)
	clusters.DELETE("/:id", d.clusterHandler.Delete)
	clusters.PUT("/:id/status", d.clusterHandler.SetStatus)
	clusters.GET("/:id/status", d.clusterHandler.Status)
	clusters.GET("/:id/namespaces", d.clusterHandler.Namespaces)
	clusters.GET("/:id/component-statuses", d.clusterHandler.ComponentStatuses)
	clusters.GET("/:id/api-resources", d.k8sDiscoveryHandler.ListAPIResources)

	ef := api.Group("/k8s/event-forward")
	// 平台级转发配置（非单集群资源操作），仅 Casbin，不挂 K8sScopeAuthorize。
	ef.Use(d.authMiddleware, d.authorize, d.opAudit)
	ef.GET("/rules", d.k8sEventForwardHandler.ListRules)
	ef.POST("/rules", d.k8sEventForwardHandler.CreateRule)
	ef.GET("/rules/:id", d.k8sEventForwardHandler.GetRule)
	ef.PUT("/rules/:id", d.k8sEventForwardHandler.UpdateRule)
	ef.DELETE("/rules/:id", d.k8sEventForwardHandler.DeleteRule)
	ef.GET("/settings", d.k8sEventForwardHandler.GetSettings)
	ef.PUT("/settings", d.k8sEventForwardHandler.UpdateSettings)
	ef.GET("/events", d.k8sEventForwardHandler.ListForwardedEvents)
	ef.POST("/events/:id/requeue", d.k8sEventForwardHandler.RequeueDeadEvent)

	pods := api.Group("/pods")
	pods.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	pods.GET("", d.podHandler.List)
	pods.GET("/detail", d.podHandler.Detail)
	pods.GET("/diagnose", d.podHandler.Diagnose)
	pods.GET("/events", d.podHandler.Events)
	pods.GET("/logs", d.podHandler.Logs)
	pods.GET("/logs/download", d.podHandler.LogsDownload)
	pods.GET("/logs/stream", d.podHandler.LogsStream)
	pods.GET("/files", d.podHandler.ListFiles)
	pods.GET("/file", d.podHandler.ReadFile)
	pods.GET("/file/download", d.podHandler.DownloadFile)
	pods.POST("/file/upload", d.podHandler.UploadFile)
	pods.POST("/file/delete", d.podHandler.DeleteFile)
	pods.POST("/exec", d.podHandler.Exec)
	pods.POST("/debug", d.podHandler.DebugEphemeral)
	// Interactive exec via WebSocket (ticket from POST /auth/ws-ticket)
	podsWS := api.Group("/pods")
	podsWS.Use(d.wsAuthMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	podsWS.GET("/exec/ws", d.podHandler.ExecWS)
	pods.POST("/restart", d.podHandler.Restart)
	pods.POST("/create/yaml", d.podHandler.CreateByYAML)
	pods.POST("/create/simple", d.podHandler.CreateSimple)
	pods.POST("/update/simple", d.podHandler.UpdateSimple)
	pods.DELETE("", d.podHandler.Delete)

	namespaces := api.Group("/namespaces")
	namespaces.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	namespaces.GET("", d.namespaceHandler.List)
	namespaces.GET("/detail", d.namespaceHandler.Detail)
	namespaces.POST("/apply", d.namespaceHandler.Apply)
	namespaces.DELETE("", d.namespaceHandler.Delete)

	nodes := api.Group("/nodes")
	nodes.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	nodes.GET("", d.nodeHandler.List)
	nodes.GET("/detail", d.nodeHandler.Detail)
	nodes.GET("/drain-status", d.nodeHandler.DrainStatus)
	nodes.POST("/schedulability", d.nodeHandler.SetSchedulability)
	nodes.POST("/drain", d.nodeHandler.Drain)
	nodes.PUT("/taints", d.nodeHandler.ReplaceTaints)

	// Workloads
	deployments := api.Group("/deployments")
	deployments.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	deployments.GET("", d.workloadHandler.ListDeployments)
	deployments.GET("/detail", d.workloadHandler.DeploymentDetail)
	deployments.GET("/revisions", d.workloadHandler.ListDeploymentRevisions)
	deployments.GET("/rollout-status", d.workloadHandler.DeploymentRolloutStatus)
	deployments.POST("/rollout-undo", d.workloadHandler.DeploymentRolloutUndo)
	deployments.POST("/apply", d.workloadHandler.Apply)
	deployments.POST("/preview-apply", d.workloadHandler.PreviewApply)
	deployments.GET("/snapshots", d.workloadHandler.ListSnapshots)
	deployments.POST("/snapshots/rollback", d.workloadHandler.RollbackSnapshot)
	deployments.POST("/scale", d.workloadHandler.DeploymentScale)
	deployments.POST("/container-resources", d.workloadHandler.DeploymentPatchContainerResources)
	deployments.POST("/restart", d.workloadHandler.DeploymentRestart)
	deployments.DELETE("", d.workloadHandler.DeleteDeployment)

	statefulsets := api.Group("/statefulsets")
	statefulsets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	statefulsets.GET("", d.workloadHandler.ListStatefulSets)
	statefulsets.GET("/detail", d.workloadHandler.StatefulSetDetail)
	statefulsets.GET("/revisions", d.workloadHandler.ListStatefulSetRevisions)
	statefulsets.POST("/rollout-undo", d.workloadHandler.StatefulSetRolloutUndo)
	statefulsets.POST("/apply", d.workloadHandler.Apply)
	statefulsets.POST("/preview-apply", d.workloadHandler.PreviewApply)
	statefulsets.POST("/scale", d.workloadHandler.StatefulSetScale)
	statefulsets.POST("/container-resources", d.workloadHandler.StatefulSetPatchContainerResources)
	statefulsets.POST("/restart", d.workloadHandler.StatefulSetRestart)
	statefulsets.DELETE("", d.workloadHandler.DeleteStatefulSet)

	daemonsets := api.Group("/daemonsets")
	daemonsets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	daemonsets.GET("", d.workloadHandler.ListDaemonSets)
	daemonsets.GET("/detail", d.workloadHandler.DaemonSetDetail)
	daemonsets.GET("/revisions", d.workloadHandler.ListDaemonSetRevisions)
	daemonsets.POST("/rollout-undo", d.workloadHandler.DaemonSetRolloutUndo)
	daemonsets.POST("/apply", d.workloadHandler.Apply)
	daemonsets.POST("/container-resources", d.workloadHandler.DaemonSetPatchContainerResources)
	daemonsets.POST("/restart", d.workloadHandler.DaemonSetRestart)
	daemonsets.DELETE("", d.workloadHandler.DeleteDaemonSet)

	cronjobs := api.Group("/cronjobs")
	cronjobs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	cronjobs.GET("", d.workloadHandler.ListCronJobs)
	cronjobs.GET("/v2", d.workloadHandler.ListCronJobsV2)
	cronjobs.GET("/detail", d.workloadHandler.CronJobDetail)
	cronjobs.GET("/pods", d.workloadHandler.CronJobPods)
	cronjobs.POST("/apply", d.workloadHandler.Apply)
	cronjobs.POST("/container-resources", d.workloadHandler.CronJobPatchContainerResources)
	cronjobs.POST("/suspend", d.workloadHandler.CronJobSuspend)
	cronjobs.POST("/trigger", d.workloadHandler.CronJobTrigger)
	cronjobs.DELETE("", d.workloadHandler.DeleteCronJob)

	jobs := api.Group("/jobs")
	jobs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	jobs.GET("", d.workloadHandler.ListJobs)
	jobs.GET("/detail", d.workloadHandler.JobDetail)
	jobs.GET("/pods", d.workloadHandler.JobPods)
	jobs.POST("/rerun", d.workloadHandler.JobRerun)
	jobs.POST("/container-resources", d.workloadHandler.JobPatchContainerResources)
	jobs.POST("/apply", d.workloadHandler.Apply)
	jobs.DELETE("", d.workloadHandler.DeleteJob)

	// related pods
	deployments.GET("/pods", d.workloadHandler.DeploymentPods)
	statefulsets.GET("/pods", d.workloadHandler.StatefulSetPods)
	daemonsets.GET("/pods", d.workloadHandler.DaemonSetPods)

	configmaps := api.Group("/configmaps")
	configmaps.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	configmaps.GET("", d.configHandler.ListConfigMaps)
	configmaps.GET("/detail", d.configHandler.ConfigMapDetail)
	configmaps.POST("/apply", d.configHandler.Apply)
	configmaps.DELETE("", d.configHandler.DeleteConfigMap)

	secrets := api.Group("/secrets")
	secrets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	secrets.GET("", d.configHandler.ListSecrets)
	secrets.GET("/detail", d.configHandler.SecretDetail)
	secrets.GET("/reveal", d.configHandler.RevealSecret)
	secrets.POST("/apply", d.configHandler.Apply)
	secrets.DELETE("", d.configHandler.DeleteSecret)

	persistentvolumes := api.Group("/persistentvolumes")
	persistentvolumes.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	persistentvolumes.GET("", d.storageHandler.ListPVs)
	persistentvolumes.GET("/detail", d.storageHandler.Detail)
	persistentvolumes.POST("/apply", d.storageHandler.Apply)
	persistentvolumes.DELETE("", d.storageHandler.Delete)

	persistentvolumeclaims := api.Group("/persistentvolumeclaims")
	persistentvolumeclaims.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	persistentvolumeclaims.GET("", d.storageHandler.ListPVCs)
	persistentvolumeclaims.GET("/detail", d.storageHandler.Detail)
	persistentvolumeclaims.POST("/apply", d.storageHandler.Apply)
	persistentvolumeclaims.DELETE("", d.storageHandler.Delete)

	storageclasses := api.Group("/storageclasses")
	storageclasses.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	storageclasses.GET("", d.storageHandler.ListStorageClasses)
	storageclasses.GET("/detail", d.storageHandler.Detail)
	storageclasses.POST("/apply", d.storageHandler.Apply)
	storageclasses.DELETE("", d.storageHandler.Delete)

	k8sServices := api.Group("/k8s-services")
	k8sServices.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	k8sServices.GET("", d.serviceResourceHandler.List)
	k8sServices.GET("/detail", d.serviceResourceHandler.Detail)
	k8sServices.POST("/apply", d.serviceResourceHandler.Apply)
	k8sServices.DELETE("", d.serviceResourceHandler.Delete)

	ingresses := api.Group("/ingresses")
	ingresses.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	ingresses.GET("", d.ingressHandler.List)
	ingresses.GET("/detail", d.ingressHandler.Detail)
	ingresses.GET("/diagnose", d.ingressHandler.Diagnose)
	ingresses.POST("/apply", d.ingressHandler.Apply)
	ingresses.POST("/nginx/restart", d.ingressHandler.RestartNginxPods)
	ingresses.DELETE("", d.ingressHandler.Delete)
	ingresses.GET("/classes", d.ingressHandler.ListClasses)
	ingresses.GET("/classes/detail", d.ingressHandler.DetailClass)
	ingresses.POST("/classes/apply", d.ingressHandler.ApplyClass)
	ingresses.DELETE("/classes", d.ingressHandler.DeleteClass)

	networkPolicies := api.Group("/network-policies")
	networkPolicies.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	networkPolicies.GET("", d.networkPolicyHandler.List)
	networkPolicies.GET("/detail", d.networkPolicyHandler.Detail)
	networkPolicies.POST("/apply", d.networkPolicyHandler.Apply)
	networkPolicies.DELETE("", d.networkPolicyHandler.Delete)

	helmHarbor := api.Group("/helm/harbor")
	helmHarbor.Use(d.authMiddleware, d.authorize, d.opAudit)
	helmHarbor.GET("/info", d.helmHandler.HarborInfo)
	helmHarbor.GET("/charts", d.helmHandler.ListCharts)
	helmHarbor.GET("/charts/versions", d.helmHandler.ChartVersions)

	helmReleases := api.Group("/helm/releases")
	helmReleases.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	helmReleases.GET("", d.helmHandler.ListReleases)
	helmReleases.GET("/detail", d.helmHandler.GetRelease)
	helmReleases.GET("/history", d.helmHandler.GetReleaseHistory)
	helmReleases.GET("/values", d.helmHandler.GetReleaseValues)
	helmReleases.POST("/install", d.helmHandler.Install)
	helmReleases.POST("/upgrade", d.helmHandler.Upgrade)
	helmReleases.POST("/rollback", d.helmHandler.Rollback)
	helmReleases.DELETE("", d.helmHandler.Uninstall)

	horizontalPodAutoscalers := api.Group("/horizontal-pod-autoscalers")
	horizontalPodAutoscalers.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	horizontalPodAutoscalers.GET("", d.k8sHPAHandler.List)
	horizontalPodAutoscalers.GET("/detail", d.k8sHPAHandler.Detail)
	horizontalPodAutoscalers.POST("/apply", d.k8sHPAHandler.Apply)
	horizontalPodAutoscalers.DELETE("", d.k8sHPAHandler.Delete)

	k8sTools := api.Group("/k8s")
	k8sTools.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	k8sTools.GET("/search", d.k8sSearchHandler.Search)
	if d.platformFeatures != nil {
		crTpl := api.Group("/k8s-cr-templates")
		crTpl.Use(d.authMiddleware, d.authorize, d.opAudit)
		crTpl.GET("", d.platformFeatures.ListCrTemplates)
		crTpl.POST("", d.platformFeatures.CreateCrTemplate)
		crTpl.PUT("/:id", d.platformFeatures.UpdateCrTemplate)
		crTpl.DELETE("/:id", d.platformFeatures.DeleteCrTemplate)
	}
	k8sTools.GET("/topology", d.workloadHandler.Topology)

	k8sResourceWatch := api.Group("/k8s/resource-watch")
	k8sResourceWatch.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	k8sResourceWatch.GET("/stream", d.k8sResourceWatchHandler.Stream)

	events := api.Group("/events")
	events.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	events.GET("", d.eventHandler.List)
	events.GET("/grouped", d.eventHandler.ListGrouped)

	crds := api.Group("/crds")
	crds.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	crds.GET("", d.crdHandler.List)
	crds.GET("/detail", d.crdHandler.Detail)
	crds.POST("/apply", d.crdHandler.Apply)
	crds.DELETE("", d.crdHandler.Delete)

	crs := api.Group("/crs")
	crs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	crs.GET("/resources", d.crHandler.ListResources)
	crs.GET("", d.crHandler.List)
	crs.GET("/detail", d.crHandler.Detail)
	crs.POST("/apply", d.crHandler.Apply)
	crs.DELETE("", d.crHandler.Delete)

	rbac := api.Group("/rbac")
	rbac.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	rbac.GET("/roles", d.rbacHandler.ListRoles)
	rbac.GET("/rolebindings", d.rbacHandler.ListRoleBindings)
	rbac.GET("/clusterroles", d.rbacHandler.ListClusterRoles)
	rbac.GET("/clusterrolebindings", d.rbacHandler.ListClusterRoleBindings)
	rbac.GET("/detail", d.rbacHandler.Detail)
	rbac.POST("/apply", d.rbacHandler.Apply)
	rbac.DELETE("", d.rbacHandler.Delete)

	serviceAccounts := api.Group("/serviceaccounts")
	serviceAccounts.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	serviceAccounts.GET("", d.serviceAccountHandler.List)
	serviceAccounts.GET("/detail", d.serviceAccountHandler.Detail)
	serviceAccounts.POST("/apply", d.serviceAccountHandler.Apply)
	serviceAccounts.DELETE("", d.serviceAccountHandler.Delete)

	overview := api.Group("/overview")
	overview.Use(d.authMiddleware, d.authorize, d.opAudit)
	overview.GET("", d.overviewHandler.Get)
	overview.GET("/project-launches", d.overviewHandler.ProjectLaunches)
	overview.GET("/release-by-person", d.overviewHandler.ReleaseByPerson)
}
