package router

import (
	"github.com/gin-gonic/gin"
)

// RegisterK8sRoutes Kubernetes 集群与资源管理、K8s 权限策略、总览面板。
func RegisterK8sRoutes(api *gin.RouterGroup, d K8sRouteDeps) {
	// 当前用户档位查询：仅需登录，不依赖 Casbin（用于前端隐藏 Exec/变更按钮）
	k8sMyAccess := api.Group("/k8s-policies")
	k8sMyAccess.Use(d.AuthMiddleware(), d.OpAudit())
	k8sMyAccess.GET("/my-access", d.K8sScopedPolicyHandler().MyAccess)

	k8sPolicies := api.Group("/k8s-policies")
	k8sPolicies.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	k8sPolicies.GET("/actions", d.K8sScopedPolicyHandler().Actions)
	k8sPolicies.GET("/capabilities", d.K8sScopedPolicyHandler().Capabilities)
	k8sPolicies.GET("/paths", d.K8sScopedPolicyHandler().Paths)
	k8sPolicies.GET("", d.K8sScopedPolicyHandler().ListByRole)
	k8sPolicies.GET("/cluster-auth-matrix", d.K8sScopedPolicyHandler().ClusterAuthMatrix)
	k8sPolicies.GET("/user-cluster-auth", d.K8sScopedPolicyHandler().UserClusterAuth)
	k8sPolicies.POST("/grant-preset", d.K8sScopedPolicyHandler().GrantPreset)
	k8sPolicies.POST("/split-by-namespaces", d.K8sScopedPolicyHandler().SplitByNamespaces)
	k8sPolicies.DELETE("/cluster-grants/:id", d.K8sScopedPolicyHandler().DeleteClusterGrant)
	k8sPolicies.POST("/cluster-grants/batch-delete", d.K8sScopedPolicyHandler().DeleteClusterGrantsBatch)

	k8sNsDeny := api.Group("/k8s-namespace-deny-rules")
	k8sNsDeny.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	k8sNsDeny.GET("", d.K8sNamespaceDenyHandler().List)
	k8sNsDeny.POST("", d.K8sNamespaceDenyHandler().Create)
	k8sNsDeny.DELETE("/:id", d.K8sNamespaceDenyHandler().Delete)

	k8sNsAllow := api.Group("/k8s-namespace-allow-rules")
	k8sNsAllow.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	k8sNsAllow.GET("", d.K8sNamespaceAllowHandler().List)
	k8sNsAllow.POST("", d.K8sNamespaceAllowHandler().Create)
	k8sNsAllow.DELETE("/:id", d.K8sNamespaceAllowHandler().Delete)

	// Kubernetes cluster management (Kom SDK)
	clusters := api.Group("/clusters")
	clusters.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	clusters.GET("", d.ClusterHandler().List)
	clusters.GET("/:id", d.ClusterHandler().Detail)
	clusters.POST("", d.ClusterHandler().Create)
	clusters.PUT("/:id", d.ClusterHandler().Update)
	clusters.DELETE("/:id", d.ClusterHandler().Delete)
	clusters.PUT("/:id/status", d.ClusterHandler().SetStatus)
	clusters.GET("/:id/status", d.ClusterHandler().Status)
	clusters.GET("/:id/namespaces", d.ClusterHandler().Namespaces)
	clusters.GET("/:id/component-statuses", d.ClusterHandler().ComponentStatuses)
	clusters.GET("/:id/api-resources", d.K8sDiscoveryHandler().ListAPIResources)

	ef := api.Group("/k8s/event-forward")
	// 平台级转发配置（非单集群资源操作），仅 Casbin，不挂 K8sScopeAuthorize。
	ef.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	ef.GET("/rules", d.K8sEventForwardHandler().ListRules)
	ef.POST("/rules", d.K8sEventForwardHandler().CreateRule)
	ef.GET("/rules/:id", d.K8sEventForwardHandler().GetRule)
	ef.PUT("/rules/:id", d.K8sEventForwardHandler().UpdateRule)
	ef.DELETE("/rules/:id", d.K8sEventForwardHandler().DeleteRule)
	ef.GET("/settings", d.K8sEventForwardHandler().GetSettings)
	ef.PUT("/settings", d.K8sEventForwardHandler().UpdateSettings)
	ef.GET("/events", d.K8sEventForwardHandler().ListForwardedEvents)
	ef.POST("/events/:id/requeue", d.K8sEventForwardHandler().RequeueDeadEvent)

	pods := api.Group("/pods")
	pods.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	pods.GET("", d.PodHandler().List)
	pods.GET("/detail", d.PodHandler().Detail)
	pods.GET("/diagnose", d.PodHandler().Diagnose)
	pods.GET("/events", d.PodHandler().Events)
	pods.GET("/logs", d.PodHandler().Logs)
	pods.GET("/logs/download", d.PodHandler().LogsDownload)
	pods.GET("/logs/stream", d.PodHandler().LogsStream)
	pods.GET("/files", d.PodHandler().ListFiles)
	pods.GET("/file", d.PodHandler().ReadFile)
	pods.GET("/file/download", d.PodHandler().DownloadFile)
	pods.POST("/file/upload", d.PodHandler().UploadFile)
	pods.POST("/file/delete", d.PodHandler().DeleteFile)
	pods.POST("/exec", d.PodHandler().Exec)
	pods.GET("/debug/image", d.PodHandler().DebugImageDefault)
	pods.POST("/debug", d.PodHandler().DebugEphemeral)
	// Interactive exec via WebSocket (ticket from POST /auth/ws-ticket)
	podsWS := api.Group("/pods")
	podsWS.Use(d.WSAuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	podsWS.GET("/exec/ws", d.PodHandler().ExecWS)
	pods.POST("/restart", d.PodHandler().Restart)
	pods.POST("/create/yaml", d.PodHandler().CreateByYAML)
	pods.POST("/create/simple", d.PodHandler().CreateSimple)
	pods.POST("/update/simple", d.PodHandler().UpdateSimple)
	pods.DELETE("", d.PodHandler().Delete)

	namespaces := api.Group("/namespaces")
	namespaces.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	namespaces.GET("", d.NamespaceHandler().List)
	namespaces.GET("/detail", d.NamespaceHandler().Detail)
	namespaces.POST("/apply", d.NamespaceHandler().Apply)
	namespaces.DELETE("", d.NamespaceHandler().Delete)

	nodes := api.Group("/nodes")
	nodes.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	nodes.GET("", d.NodeHandler().List)
	nodes.GET("/detail", d.NodeHandler().Detail)
	nodes.GET("/drain-status", d.NodeHandler().DrainStatus)
	nodes.POST("/schedulability", d.NodeHandler().SetSchedulability)
	nodes.POST("/drain", d.NodeHandler().Drain)
	nodes.PUT("/taints", d.NodeHandler().ReplaceTaints)

	// Workloads
	deployments := api.Group("/deployments")
	deployments.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	deployments.GET("", d.WorkloadHandler().ListDeployments)
	deployments.GET("/detail", d.WorkloadHandler().DeploymentDetail)
	deployments.GET("/revisions", d.WorkloadHandler().ListDeploymentRevisions)
	deployments.GET("/rollout-status", d.WorkloadHandler().DeploymentRolloutStatus)
	deployments.POST("/rollout-undo", d.WorkloadHandler().DeploymentRolloutUndo)
	deployments.POST("/apply", d.WorkloadHandler().Apply)
	deployments.POST("/preview-apply", d.WorkloadHandler().PreviewApply)
	deployments.GET("/snapshots", d.WorkloadHandler().ListSnapshots)
	deployments.POST("/snapshots/rollback", d.WorkloadHandler().RollbackSnapshot)
	deployments.POST("/scale", d.WorkloadHandler().DeploymentScale)
	deployments.POST("/container-resources", d.WorkloadHandler().DeploymentPatchContainerResources)
	deployments.POST("/restart", d.WorkloadHandler().DeploymentRestart)
	deployments.DELETE("", d.WorkloadHandler().DeleteDeployment)

	statefulsets := api.Group("/statefulsets")
	statefulsets.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	statefulsets.GET("", d.WorkloadHandler().ListStatefulSets)
	statefulsets.GET("/detail", d.WorkloadHandler().StatefulSetDetail)
	statefulsets.GET("/revisions", d.WorkloadHandler().ListStatefulSetRevisions)
	statefulsets.POST("/rollout-undo", d.WorkloadHandler().StatefulSetRolloutUndo)
	statefulsets.POST("/apply", d.WorkloadHandler().Apply)
	statefulsets.POST("/preview-apply", d.WorkloadHandler().PreviewApply)
	statefulsets.POST("/scale", d.WorkloadHandler().StatefulSetScale)
	statefulsets.POST("/container-resources", d.WorkloadHandler().StatefulSetPatchContainerResources)
	statefulsets.POST("/restart", d.WorkloadHandler().StatefulSetRestart)
	statefulsets.DELETE("", d.WorkloadHandler().DeleteStatefulSet)

	daemonsets := api.Group("/daemonsets")
	daemonsets.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	daemonsets.GET("", d.WorkloadHandler().ListDaemonSets)
	daemonsets.GET("/detail", d.WorkloadHandler().DaemonSetDetail)
	daemonsets.GET("/revisions", d.WorkloadHandler().ListDaemonSetRevisions)
	daemonsets.POST("/rollout-undo", d.WorkloadHandler().DaemonSetRolloutUndo)
	daemonsets.POST("/apply", d.WorkloadHandler().Apply)
	daemonsets.POST("/container-resources", d.WorkloadHandler().DaemonSetPatchContainerResources)
	daemonsets.POST("/restart", d.WorkloadHandler().DaemonSetRestart)
	daemonsets.DELETE("", d.WorkloadHandler().DeleteDaemonSet)

	cronjobs := api.Group("/cronjobs")
	cronjobs.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	cronjobs.GET("", d.WorkloadHandler().ListCronJobs)
	cronjobs.GET("/v2", d.WorkloadHandler().ListCronJobsV2)
	cronjobs.GET("/detail", d.WorkloadHandler().CronJobDetail)
	cronjobs.GET("/pods", d.WorkloadHandler().CronJobPods)
	cronjobs.POST("/apply", d.WorkloadHandler().Apply)
	cronjobs.POST("/container-resources", d.WorkloadHandler().CronJobPatchContainerResources)
	cronjobs.POST("/suspend", d.WorkloadHandler().CronJobSuspend)
	cronjobs.POST("/trigger", d.WorkloadHandler().CronJobTrigger)
	cronjobs.DELETE("", d.WorkloadHandler().DeleteCronJob)

	jobs := api.Group("/jobs")
	jobs.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	jobs.GET("", d.WorkloadHandler().ListJobs)
	jobs.GET("/detail", d.WorkloadHandler().JobDetail)
	jobs.GET("/pods", d.WorkloadHandler().JobPods)
	jobs.POST("/rerun", d.WorkloadHandler().JobRerun)
	jobs.POST("/container-resources", d.WorkloadHandler().JobPatchContainerResources)
	jobs.POST("/apply", d.WorkloadHandler().Apply)
	jobs.DELETE("", d.WorkloadHandler().DeleteJob)

	// related pods
	deployments.GET("/pods", d.WorkloadHandler().DeploymentPods)
	statefulsets.GET("/pods", d.WorkloadHandler().StatefulSetPods)
	daemonsets.GET("/pods", d.WorkloadHandler().DaemonSetPods)

	configmaps := api.Group("/configmaps")
	configmaps.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	configmaps.GET("", d.ConfigHandler().ListConfigMaps)
	configmaps.GET("/detail", d.ConfigHandler().ConfigMapDetail)
	configmaps.POST("/apply", d.ConfigHandler().Apply)
	configmaps.DELETE("", d.ConfigHandler().DeleteConfigMap)

	secrets := api.Group("/secrets")
	secrets.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	secrets.GET("", d.ConfigHandler().ListSecrets)
	secrets.GET("/detail", d.ConfigHandler().SecretDetail)
	secrets.GET("/reveal", d.ConfigHandler().RevealSecret)
	secrets.POST("/apply", d.ConfigHandler().Apply)
	secrets.DELETE("", d.ConfigHandler().DeleteSecret)

	persistentvolumes := api.Group("/persistentvolumes")
	persistentvolumes.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	persistentvolumes.GET("", d.StorageHandler().ListPVs)
	persistentvolumes.GET("/detail", d.StorageHandler().Detail)
	persistentvolumes.POST("/apply", d.StorageHandler().Apply)
	persistentvolumes.DELETE("", d.StorageHandler().Delete)

	persistentvolumeclaims := api.Group("/persistentvolumeclaims")
	persistentvolumeclaims.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	persistentvolumeclaims.GET("", d.StorageHandler().ListPVCs)
	persistentvolumeclaims.GET("/detail", d.StorageHandler().Detail)
	persistentvolumeclaims.POST("/apply", d.StorageHandler().Apply)
	persistentvolumeclaims.DELETE("", d.StorageHandler().Delete)

	storageclasses := api.Group("/storageclasses")
	storageclasses.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	storageclasses.GET("", d.StorageHandler().ListStorageClasses)
	storageclasses.GET("/detail", d.StorageHandler().Detail)
	storageclasses.POST("/apply", d.StorageHandler().Apply)
	storageclasses.DELETE("", d.StorageHandler().Delete)

	k8sServices := api.Group("/k8s-services")
	k8sServices.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	k8sServices.GET("", d.ServiceResourceHandler().List)
	k8sServices.GET("/detail", d.ServiceResourceHandler().Detail)
	k8sServices.POST("/apply", d.ServiceResourceHandler().Apply)
	k8sServices.DELETE("", d.ServiceResourceHandler().Delete)

	ingresses := api.Group("/ingresses")
	ingresses.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	ingresses.GET("", d.IngressHandler().List)
	ingresses.GET("/detail", d.IngressHandler().Detail)
	ingresses.GET("/diagnose", d.IngressHandler().Diagnose)
	ingresses.POST("/apply", d.IngressHandler().Apply)
	ingresses.POST("/nginx/restart", d.IngressHandler().RestartNginxPods)
	ingresses.DELETE("", d.IngressHandler().Delete)
	ingresses.GET("/classes", d.IngressHandler().ListClasses)
	ingresses.GET("/classes/detail", d.IngressHandler().DetailClass)
	ingresses.POST("/classes/apply", d.IngressHandler().ApplyClass)
	ingresses.DELETE("/classes", d.IngressHandler().DeleteClass)

	networkPolicies := api.Group("/network-policies")
	networkPolicies.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	networkPolicies.GET("", d.NetworkPolicyHandler().List)
	networkPolicies.GET("/detail", d.NetworkPolicyHandler().Detail)
	networkPolicies.POST("/apply", d.NetworkPolicyHandler().Apply)
	networkPolicies.DELETE("", d.NetworkPolicyHandler().Delete)

	helmHarbor := api.Group("/helm/harbor")
	helmHarbor.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	helmHarbor.GET("/info", d.HelmHandler().HarborInfo)
	helmHarbor.GET("/charts", d.HelmHandler().ListCharts)
	helmHarbor.GET("/charts/versions", d.HelmHandler().ChartVersions)

	helmReleases := api.Group("/helm/releases")
	helmReleases.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	helmReleases.GET("", d.HelmHandler().ListReleases)
	helmReleases.GET("/detail", d.HelmHandler().GetRelease)
	helmReleases.GET("/history", d.HelmHandler().GetReleaseHistory)
	helmReleases.GET("/values", d.HelmHandler().GetReleaseValues)
	helmReleases.POST("/install", d.HelmHandler().Install)
	helmReleases.POST("/upgrade", d.HelmHandler().Upgrade)
	helmReleases.POST("/rollback", d.HelmHandler().Rollback)
	helmReleases.DELETE("", d.HelmHandler().Uninstall)

	horizontalPodAutoscalers := api.Group("/horizontal-pod-autoscalers")
	horizontalPodAutoscalers.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	horizontalPodAutoscalers.GET("", d.K8sHPAHandler().List)
	horizontalPodAutoscalers.GET("/detail", d.K8sHPAHandler().Detail)
	horizontalPodAutoscalers.POST("/apply", d.K8sHPAHandler().Apply)
	horizontalPodAutoscalers.DELETE("", d.K8sHPAHandler().Delete)

	k8sTools := api.Group("/k8s")
	k8sTools.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	k8sTools.GET("/search", d.K8sSearchHandler().Search)
	if d.PlatformFeaturesHandler() != nil {
		crTpl := api.Group("/k8s-cr-templates")
		crTpl.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
		crTpl.GET("", d.PlatformFeaturesHandler().ListCrTemplates)
		crTpl.GET("/:id", d.PlatformFeaturesHandler().GetCrTemplate)
		crTpl.POST("", d.PlatformFeaturesHandler().CreateCrTemplate)
		crTpl.PUT("/:id", d.PlatformFeaturesHandler().UpdateCrTemplate)
		crTpl.DELETE("/:id", d.PlatformFeaturesHandler().DeleteCrTemplate)
	}
	k8sTools.GET("/topology", d.WorkloadHandler().Topology)

	k8sResourceWatch := api.Group("/k8s/resource-watch")
	k8sResourceWatch.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	k8sResourceWatch.GET("/stream", d.K8sResourceWatchHandler().Stream)

	events := api.Group("/events")
	events.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	events.GET("", d.EventHandler().List)
	events.GET("/grouped", d.EventHandler().ListGrouped)

	crds := api.Group("/crds")
	crds.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	crds.GET("", d.CRDHandler().List)
	crds.GET("/detail", d.CRDHandler().Detail)
	crds.POST("/apply", d.CRDHandler().Apply)
	crds.DELETE("", d.CRDHandler().Delete)

	crs := api.Group("/crs")
	crs.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	crs.GET("/resources", d.CRHandler().ListResources)
	crs.GET("", d.CRHandler().List)
	crs.GET("/detail", d.CRHandler().Detail)
	crs.POST("/apply", d.CRHandler().Apply)
	crs.DELETE("", d.CRHandler().Delete)

	rbac := api.Group("/rbac")
	rbac.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	rbac.GET("/roles", d.RBACHandler().ListRoles)
	rbac.GET("/rolebindings", d.RBACHandler().ListRoleBindings)
	rbac.GET("/clusterroles", d.RBACHandler().ListClusterRoles)
	rbac.GET("/clusterrolebindings", d.RBACHandler().ListClusterRoleBindings)
	rbac.GET("/detail", d.RBACHandler().Detail)
	rbac.POST("/apply", d.RBACHandler().Apply)
	rbac.DELETE("", d.RBACHandler().Delete)

	serviceAccounts := api.Group("/serviceaccounts")
	serviceAccounts.Use(d.AuthMiddleware(), d.Authorize(), d.K8sScopeAuthorize(), d.OpAudit())
	serviceAccounts.GET("", d.ServiceAccountHandler().List)
	serviceAccounts.GET("/detail", d.ServiceAccountHandler().Detail)
	serviceAccounts.POST("/apply", d.ServiceAccountHandler().Apply)
	serviceAccounts.DELETE("", d.ServiceAccountHandler().Delete)

	overview := api.Group("/overview")
	overview.Use(d.AuthMiddleware(), d.Authorize(), d.OpAudit())
	overview.GET("", d.OverviewHandler().Get)
	overview.GET("/screen", d.OverviewHandler().Screen)
	overview.GET("/project-launches", d.OverviewHandler().ProjectLaunches)
	overview.GET("/release-by-person", d.OverviewHandler().ReleaseByPerson)
}
