// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"yunshu/internal/bootstrap"
	"yunshu/internal/handler"
	"yunshu/internal/service/ai"
	"yunshu/internal/service/alert"
	"yunshu/internal/service/k8s"
	"yunshu/internal/service/k8s/eventforward"
	"yunshu/internal/service/overview"
	"yunshu/internal/service/project"
	"yunshu/internal/service/system"
)

import (
	_ "yunshu/internal/plugins/all"
)

// Injectors from wire.go:

// InitializeRouteDeps is the Wire entry for HTTP route dependencies.
func InitializeRouteDeps(app *bootstrap.App) (*RouteDeps, error) {
	db := provideDB(app)
	routerRouteRepositories := newRouteRepositories(db)
	v := routerRouteRepositories.LoginLog
	v2 := system.NewLoginLogService(v)
	v3 := routerRouteRepositories.OperationLog
	v4 := system.NewOperationLogService(v3)
	v5 := routerRouteRepositories.User
	client := provideRedis(app)
	authConfig := provideAuthConfig(app)
	sender := provideMailer(app)
	routerAppRouteConfig := provideAppRouteConfig(app)
	appDisplayName := routerAppRouteConfig.AppName
	v6 := provideAuthService(v5, client, authConfig, sender, appDisplayName)
	v7 := routerRouteRepositories.Role
	v8 := routerRouteRepositories.Department
	syncedEnforcer := provideEnforcer(app)
	v9 := routerRouteRepositories.ProjectMember
	v10 := routerRouteRepositories.AlertRuleAssignee
	v11 := routerRouteRepositories.AlertMonitorRule
	v12 := routerRouteRepositories.AlertDatasource
	alertRuleAssigneeService := alert.NewAlertRuleAssigneeService(v10, v11, v12, v5, v9, v8)
	v13 := system.NewUserService(v5, v7, v8, syncedEnforcer, v9, alertRuleAssigneeService)
	v14 := system.NewDepartmentService(v8, v5, alertRuleAssigneeService)
	v15 := system.NewRoleService(v7, v5, syncedEnforcer)
	v16 := routerRouteRepositories.Permission
	v17 := system.NewPermissionService(v16, syncedEnforcer)
	v18 := system.NewPolicyService(v7, v16, syncedEnforcer)
	v19 := routerRouteRepositories.Menu
	v20 := routerRouteRepositories.K8sClusterAccess
	pluginsConfig := providePluginsConfig(app)
	v21 := system.NewPolicyGovernanceService(v5, v7, v16, v19, v9, v20, syncedEnforcer, pluginsConfig)
	v22 := routerRouteRepositories.K8sNsDeny
	v23 := routerRouteRepositories.K8sNsAllow
	v24 := routerRouteRepositories.UserGroup
	v25 := routerRouteRepositories.Cluster
	v26 := k8s.NewK8sScopedPolicyService(v7, v16, v20, v22, v23, v24, v5, v25)
	v27 := k8s.NewK8sNamespaceDenyService(v22)
	v28 := k8s.NewK8sNamespaceAllowService(v23)
	v29 := routerRouteRepositories.Project
	v30 := system.NewUserGroupService(v24, v5, v9, v29)
	v31 := routerRouteRepositories.RegRequest
	v32 := provideRegistrationService(v31, v5, client, authConfig, sender, appDisplayName)
	v33 := system.NewMenuService(v19)
	v34 := routerRouteRepositories.DictEntry
	v35 := system.NewDictEntryService(v34)
	v36 := routerRouteRepositories.AlertSilence
	v37 := alert.NewAlertSilenceService(v36)
	v38 := routerRouteRepositories.AlertDuty
	v39 := alert.NewAlertDutyService(v38, v11, v5)
	v40 := routerRouteRepositories.AlertReceiverGroup
	v41 := alert.NewReceiverGroupCache(v40)
	alertConfig := provideAlertConfig(app)
	v42 := routerRouteRepositories.AlertMaintenance
	v43 := alert.NewAlertMaintenanceService(v42)
	securityEncryptionKey := routerAppRouteConfig.EncryptionKey
	v44 := routerRouteRepositories.AlertEvent
	v45 := routerRouteRepositories.AlertChannel
	v46 := routerRouteRepositories.AlertFiringDelivery
	v47 := routerRouteRepositories.CloudExpiryRule
	v48 := routerRouteRepositories.CloudAccount
	alertStateService := provideAlertStateService(client, v44, v46, alertConfig)
	v49 := routerRouteRepositories.AlertSubscription
	v50 := routerRouteRepositories.AlertInhibitionRule
	v51 := provideAlertServiceOptions(v37, v43, alertRuleAssigneeService, v39, v41, securityEncryptionKey, v44, v45, v11, v12, v29, v46, v47, v48, alertStateService, v49, v50)
	v52 := provideAlertService(db, client, sender, alertConfig, v51)
	v53 := alert.NewCloudExpiryRuleService(v47)
	v54 := alert.NewAlertDatasourceService(v12)
	v55 := alert.NewAlertMonitorRuleService(v11, v12, client)
	v56, err := provideK8sRuntimeService(v25, v22, v23, v9, securityEncryptionKey)
	if err != nil {
		return nil, err
	}
	v57 := k8s.NewK8sClusterService(v25, v34, v56, v22, v23, v9, v20)
	v58 := k8s.NewK8sPodService(v56, v22, v23)
	v59 := k8s.NewK8sNamespaceService(v56, v22, v23)
	v60 := k8s.NewK8sNodeService(v56)
	v61 := k8s.NewK8sWorkloadService(v56, db)
	v62 := k8s.NewK8sConfigService(v56)
	v63 := k8s.NewK8sStorageService(v56)
	v64 := k8s.NewK8sServiceResourceService(v56)
	v65 := k8s.NewK8sIngressService(v56, v20)
	v66 := k8s.NewK8sNetworkPolicyService(v56)
	v67 := k8s.NewK8sDiscoveryService(v56)
	v68 := k8s.NewK8sHPAService(v56)
	cicdConfig := provideCicdConfig(app)
	v69 := provideK8sHelmService(v56, db, cicdConfig)
	v70 := k8s.NewK8sEventService(v56, v22, v23)
	v71 := k8s.NewK8sCRDService(v56)
	v72 := k8s.NewK8sCRService(v56)
	v73 := k8s.NewK8sRBACService(v56)
	v74 := k8s.NewK8sServiceAccountService(v56)
	v75 := routerRouteRepositories.Overview
	v76 := providePluginsEnabled(app)
	v77 := overview.NewOverviewService(v75, v56, client, v9, v20, v76)
	v78 := routerRouteRepositories.Server
	v79 := routerRouteRepositories.ServerGroup
	v80 := routerRouteRepositories.Service
	v81 := routerRouteRepositories.LogSource
	v82 := project.NewProjectMgmtService(v29, v78, v79, v80, v81, v9, v5, v8)
	v83 := routerRouteRepositories.ServiceCatalog
	v84 := project.NewServiceCatalogService(v83, v29, db)
	v85 := routerRouteRepositories.ChangeEvent
	v86 := project.NewChangeEventService(v85, v29, db)
	v87, err := provideCMDBService(db, v78, v79, v48, v9, securityEncryptionKey)
	if err != nil {
		return nil, err
	}
	service := provideCicdService(db, v78, v29, v24, v5, v9, cicdConfig, sender, appDisplayName, v59)
	v88 := routerRouteRepositories.MysqlBackup
	v89, err := provideMysqlBackupService(v88, v78, v29, v5, db, securityEncryptionKey, sender, appDisplayName)
	if err != nil {
		return nil, err
	}
	v90 := routerRouteRepositories.Dbmgmt
	dbmgmtConfig := provideDbmgmtConfig(app)
	dbmgmtService, err := provideDbmgmtService(v90, v78, v29, v24, v5, db, securityEncryptionKey, sender, appDisplayName, dbmgmtConfig)
	if err != nil {
		return nil, err
	}
	v91 := provideElasticsearchProvider(app)
	v92 := provideLogSearchService(v91, v78)
	v93 := routerRouteRepositories.LogRetention
	v94 := provideLogRetentionService(v91, v93)
	v95 := provideKafkaProvider(app)
	v96 := provideKafkaToESService(v95, v91)
	v97 := routerRouteRepositories.LoggieAgent
	loggieConfig := provideLoggieConfig(app)
	v98, err := provideLoggieAgentService(v97, v78, v81, v29, v80, v91, v95, securityEncryptionKey, loggieConfig)
	if err != nil {
		return nil, err
	}
	clusterLogService := provideClusterLogService(db, v29, v91, v95, v56, loggieConfig)
	v99 := alert.NewAlertReceiverGroupService(v40, v41)
	v100 := routerRouteRepositories.K8sEventForward
	v101 := eventforward.NewK8sEventForwardAdminService(v100)
	v102 := k8s.NewK8sSearchService(v56, v25, v9, v20, v22, v23)
	inspectService := provideInspectService(db, client, v54, v29, sender, appDisplayName)
	aiConfig := provideAIConfig(app)
	aiService := ai.NewService(db, aiConfig, v57, v58, v61, v59, v70, v92, v91, service, v52)
	esmgmtService, err := provideEsmgmtService(db, securityEncryptionKey, v91)
	if err != nil {
		return nil, err
	}
	routerRouteServices := &routeServices{
		LoginLog:             v2,
		OperationLog:         v4,
		Auth:                 v6,
		User:                 v13,
		Department:           v14,
		Role:                 v15,
		Permission:           v17,
		Policy:               v18,
		PolicyGovernance:     v21,
		K8sScopedPolicy:      v26,
		K8sNamespaceDeny:     v27,
		K8sNamespaceAllow:    v28,
		UserGroup:            v30,
		Registration:         v32,
		Menu:                 v33,
		DictEntry:            v35,
		AlertSilence:         v37,
		AlertDuty:            v39,
		AlertAssignee:        alertRuleAssigneeService,
		AlertReceiverCache:   v41,
		Alert:                v52,
		CloudExpiryRule:      v53,
		AlertDatasource:      v54,
		AlertMonitorRule:     v55,
		K8sRuntime:           v56,
		K8sCluster:           v57,
		K8sPod:               v58,
		K8sNamespace:         v59,
		K8sNode:              v60,
		K8sWorkload:          v61,
		K8sConfig:            v62,
		K8sStorage:           v63,
		K8sServiceResource:   v64,
		K8sIngress:           v65,
		K8sNetworkPolicy:     v66,
		K8sDiscovery:         v67,
		K8sHPA:               v68,
		K8sHelm:              v69,
		K8sEvent:             v70,
		K8sCRD:               v71,
		K8sCR:                v72,
		K8sRBAC:              v73,
		K8sServiceAccount:    v74,
		Overview:             v77,
		ProjectMgmt:          v82,
		ServiceCatalog:       v84,
		ChangeEvent:          v86,
		CMDB:                 v87,
		Cicd:                 service,
		MysqlBackup:          v89,
		Dbmgmt:               dbmgmtService,
		LogSearch:            v92,
		LogRetention:         v94,
		KafkaToES:            v96,
		LoggieAgent:          v98,
		ClusterLog:           clusterLogService,
		AlertReceiverGroup:   v99,
		K8sEventForwardAdmin: v101,
		K8sSearch:            v102,
		AlertMaintenance:     v43,
		Inspect:              inspectService,
		AI:                   aiService,
		Esmgmt:               esmgmtService,
	}
	systemHandler := provideSystemHandler(app)
	pluginHandler := handler.NewPluginHandler(pluginsConfig)
	authHandler := handler.NewAuthHandler(v6, v2)
	loginLogHandler := handler.NewLoginLogHandler(v2)
	operationLogHandler := handler.NewOperationLogHandler(v4)
	userHandler := handler.NewUserHandler(v13)
	departmentHandler := handler.NewDepartmentHandler(v14)
	roleHandler := handler.NewRoleHandler(v15)
	permissionHandler := handler.NewPermissionHandler(v17, pluginsConfig)
	policyHandler := handler.NewPolicyHandler(v18, v21, v17, pluginsConfig)
	k8sScopedPolicyHandler := handler.NewK8sScopedPolicyHandler(v26)
	k8sNamespaceDenyHandler := handler.NewK8sNamespaceDenyHandler(v27)
	k8sNamespaceAllowHandler := handler.NewK8sNamespaceAllowHandler(v28)
	userGroupHandler := handler.NewUserGroupHandler(v30)
	registrationHandler := handler.NewRegistrationHandler(v32)
	menuHandler := handler.NewMenuHandler(v33, pluginsConfig, syncedEnforcer)
	dictEntryHandler := handler.NewDictEntryHandler(v35)
	adminHandler := handler.NewAdminHandler(client)
	alertHandler := handler.NewAlertHandler(v52)
	alertPlatformHandler := handler.NewAlertPlatformHandler(v54, v37, v43, v55, alertRuleAssigneeService, v39)
	alertSubscriptionHandler := provideAlertSubscriptionHandler(v52)
	alertInhibitionHandler := provideAlertInhibitionHandler(v52)
	alertReceiverGroupHandler := handler.NewAlertReceiverGroupHandler(v99)
	cloudExpiryRuleHandler := handler.NewCloudExpiryRuleHandler(v53, v52)
	clusterHandler := handler.NewClusterHandler(v57)
	podHandler := handler.NewPodHandler(v58)
	namespaceHandler := handler.NewNamespaceHandler(v59)
	nodeHandler := handler.NewNodeHandler(v60)
	workloadHandler := handler.NewWorkloadHandler(v61)
	configHandler := handler.NewConfigHandler(v62)
	storageHandler := handler.NewStorageHandler(v63)
	serviceResourceHandler := handler.NewServiceResourceHandler(v64)
	ingressHandler := handler.NewIngressHandler(v65)
	networkPolicyHandler := handler.NewNetworkPolicyHandler(v66)
	k8sDiscoveryHandler := handler.NewK8sDiscoveryHandler(v67)
	k8sHPAHandler := handler.NewK8sHPAHandler(v68)
	helmHandler := handler.NewHelmHandler(v69)
	k8sResourceWatchHandler := handler.NewK8sResourceWatchHandler(v56)
	k8sSearchHandler := handler.NewK8sSearchHandler(v102)
	k8sEventForwardHandler := handler.NewK8sEventForwardHandler(v101)
	eventHandler := handler.NewEventHandler(v70)
	crdHandler := handler.NewCRDHandler(v71)
	crHandler := handler.NewCRHandler(v72)
	rbacHandler := handler.NewRBACHandler(v73)
	serviceAccountHandler := handler.NewServiceAccountHandler(v74)
	overviewHandler := handler.NewOverviewHandler(v77)
	projectHandler := handler.NewProjectHandler(v82, v92)
	projectCatalogHandler := handler.NewProjectCatalogHandler(v84, v86)
	cmdbHandler := handler.NewCMDBHandler(v87)
	mysqlBackupHandler := handler.NewMysqlBackupHandler(v89)
	dbmgmtHandler := handler.NewDbmgmtHandler(dbmgmtService)
	cicdHandler := handler.NewCicdHandler(service)
	logPlatformHandler := handler.NewLogPlatformHandler(v94, v96)
	loggieHandler := handler.NewLoggieHandler(v98)
	clusterLogHandler := handler.NewClusterLogHandler(clusterLogService)
	inspectHandler := handler.NewInspectHandler(inspectService)
	aiHandler := handler.NewAIHandler(aiService)
	esmgmtHandler := handler.NewEsmgmtHandler(esmgmtService)
	routerRouteHandlers := &routeHandlers{
		System:             systemHandler,
		Plugin:             pluginHandler,
		Auth:               authHandler,
		LoginLog:           loginLogHandler,
		OperationLog:       operationLogHandler,
		User:               userHandler,
		Department:         departmentHandler,
		Role:               roleHandler,
		Permission:         permissionHandler,
		Policy:             policyHandler,
		K8sScopedPolicy:    k8sScopedPolicyHandler,
		K8sNamespaceDeny:   k8sNamespaceDenyHandler,
		K8sNamespaceAllow:  k8sNamespaceAllowHandler,
		UserGroup:          userGroupHandler,
		Registration:       registrationHandler,
		Menu:               menuHandler,
		DictEntry:          dictEntryHandler,
		Admin:              adminHandler,
		Alert:              alertHandler,
		AlertPlatform:      alertPlatformHandler,
		AlertSubscription:  alertSubscriptionHandler,
		AlertInhibition:    alertInhibitionHandler,
		AlertReceiverGroup: alertReceiverGroupHandler,
		CloudExpiryRule:    cloudExpiryRuleHandler,
		Cluster:            clusterHandler,
		Pod:                podHandler,
		Namespace:          namespaceHandler,
		Node:               nodeHandler,
		Workload:           workloadHandler,
		Config:             configHandler,
		Storage:            storageHandler,
		ServiceResource:    serviceResourceHandler,
		Ingress:            ingressHandler,
		NetworkPolicy:      networkPolicyHandler,
		K8sDiscovery:       k8sDiscoveryHandler,
		K8sHPA:             k8sHPAHandler,
		Helm:               helmHandler,
		K8sResourceWatch:   k8sResourceWatchHandler,
		K8sSearch:          k8sSearchHandler,
		K8sEventForward:    k8sEventForwardHandler,
		Event:              eventHandler,
		CRD:                crdHandler,
		CR:                 crHandler,
		RBAC:               rbacHandler,
		ServiceAccount:     serviceAccountHandler,
		Overview:           overviewHandler,
		Project:            projectHandler,
		ProjectCatalog:     projectCatalogHandler,
		CMDB:               cmdbHandler,
		MysqlBackup:        mysqlBackupHandler,
		Dbmgmt:             dbmgmtHandler,
		Cicd:               cicdHandler,
		LogPlatform:        logPlatformHandler,
		Loggie:             loggieHandler,
		ClusterLog:         clusterLogHandler,
		Inspect:            inspectHandler,
		AI:                 aiHandler,
		Esmgmt:             esmgmtHandler,
	}
	routeDeps, err := provideRouteDeps(app, routerRouteRepositories, routerRouteServices, routerRouteHandlers)
	if err != nil {
		return nil, err
	}
	return routeDeps, nil
}

// wire.go:

func provideRouteDeps(
	app *bootstrap.App,
	repos *routeRepositories,
	svcs *routeServices,
	handlers *routeHandlers,
) (*RouteDeps, error) {
	return assembleRouteDeps(app, repos, svcs, handlers)
}
