// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"gorm.io/gorm"
	"yunshu/internal/bootstrap"
	"yunshu/internal/grpc/client"
)

// Injectors from wire.go:

// InitializeRouteDeps is the Wire entry for HTTP route dependencies.
func InitializeRouteDeps(app *bootstrap.App, runtimeClient *client.RuntimeClient) (*routeDeps, error) {
	db := provideDB(app)
	routerRouteRepositories := provideRouteRepositories(db)
	routerRouteServices, err := provideRouteServices(app, routerRouteRepositories)
	if err != nil {
		return nil, err
	}
	routerRouteDeps, err := provideRouteDeps(app, runtimeClient, routerRouteRepositories, routerRouteServices)
	if err != nil {
		return nil, err
	}
	return routerRouteDeps, nil
}

// wire.go:

func provideDB(app *bootstrap.App) *gorm.DB {
	return app.DB
}

func provideRouteRepositories(db *gorm.DB) *routeRepositories {
	return newRouteRepositories(db)
}

func provideRouteDeps(app *bootstrap.App, runtimeClient *client.RuntimeClient, repos *routeRepositories, svcs *routeServices) (*routeDeps, error) {
	return assembleRouteDeps(app, runtimeClient, repos, svcs)
}
